LetzElPhC: src/wfc/wfc.h File Reference
wfc.h File Reference
#include <mpi.h>
#include <stdbool.h>
#include "elphC.h"
Functions
void rotateGvecs (const ELPH_float *Gvecs, const ELPH_float *sym, const ND_int ngvecs, const ELPH_float *lat_vec, const bool inverse, const bool crystal, ELPH_float *G0, ELPH_float *Gvec_out)
void su2rotate (const int nspinor, const ND_int npw, const ND_int nsets, const ELPH_cmplx *su2mat, ELPH_cmplx *wfc)
void apply_trans_wfc (const ELPH_float *trans_vec, const ELPH_float *kvec, const ND_int nsets, const ND_int npw, const ELPH_float *gvecs, ELPH_cmplx *wfc_G, const bool conjugate)
void get_fft_box (const ELPH_float EcutRy, const ELPH_float *blat, ND_int *fft_box, MPI_Comm commK)
void SU2mat (const ELPH_float *sym_in, const ND_int nspinor, const bool invert_sym, const bool time_rev, ELPH_cmplx *su2mat)
void Sort_pw (const ND_int npw_tot, const ND_int npw_loc, const ND_int *fft_dims, const ELPH_float *gvec_in, const ELPH_cmplx *wfc_in, const ND_int nsets, ND_int *npw_loc_out, ND_int *nG_xy, int **gvec_out, ELPH_cmplx **wfc_out, MPI_Comm mpi_comm)
Function Documentation
apply_trans_wfc()
void apply_trans_wfc (const ELPH_float * trans_vec, const ELPH_float * kvec, const ND_int nsets, const ND_int npw, const ELPH_float * gvecs, ELPH_cmplx * wfc_G, const bool conjugate)
Definition at line 15 of file trans_wfc.c.
{
    /*
    This is an in-place function. wfc_G (nsets,npw) will be over written.
    If conjugate is true, the output is conjugated
    T(a) C_G * e^{i(G+k).r} = C_G * e^{i(G+k).r} * e^{-i(G+k).a}
    note : trans_vec, kvec, gvecs can be in crystal/cart coordinates but
    we must use the same for all. kvec and gvecs must be in 2*pi units
    when using cart coordinates.
    */
    // first compute the phase from k i.e e^{-ik*a}
    ELPH_cmplx kphase = cexp(-I * 2 * ELPH_PI * dot3_macro(kvec, trans_vec));
    for (ND_int iset = 0; iset < nsets; ++iset)
    {
        ELPH_cmplx* wfc_G_tmp = wfc_G + iset * npw;
        ELPH_OMP_PAR_FOR_SIMD
        for (ND_int ig = 0; ig < npw; ++ig)
        {
            const ELPH_float* gvec_tmp = gvecs + 3 * ig;
            ELPH_cmplx gphase = kphase * cexp(-I * 2 * ELPH_PI *
                                              dot3_macro(gvec_tmp, trans_vec));
            wfc_G_tmp[ig] *= gphase;
            if (conjugate)
            {
                wfc_G_tmp[ig] = conj(wfc_G_tmp[ig]);
            }
        }
    }
}
References dot3_macro, ELPH_OMP_PAR_FOR_SIMD, and ELPH_PI.
Referenced by add_elphNonLocal(), electronic_reps(), and elphLocal().
get_fft_box()
void get_fft_box (const ELPH_float EcutRy, const ELPH_float * blat, ND_int * fft_box, MPI_Comm commK)
Calculate FFT box (Nx, Ny, Nz). The dimensions are determined by:
The energy cutoff (EcutRy) which defines the maximum kinetic energy.
Each cpu will atleast have one Z stick i.e Nx * Ny > comm_size. So this is cpu dependent
The initial dimensions are calculated as: N_i = 2*round(sqrt(Ecut)/|b_i| + 1) + 1 If the initial grid would be too small for parallelization (Nx*Ny < num_processes), the grid is scaled up by a factor to ensure each process gets at least one Gz stick.
Parameters
[in] EcutRy Energy cutoff in Rydberg units
[in] blat Array of reciprocal lattice vectors (9 elements, 3x3 matrix)
[out] fft_box Array to store the computed FFT box dimensions (Nx, Ny, Nz)
[in] commK MPI communicator for k-point parallelization
Attention
The function uses MPI Bcast so it must be called by all processes in commK
Definition at line 8 of file gen_fftbox.c.
{
    const ELPH_float b0_norm =
        sqrt(blat[0] * blat[0] + blat[3] * blat[3] + blat[6] * blat[6]);
    const ELPH_float b1_norm =
        sqrt(blat[1] * blat[1] + blat[4] * blat[4] + blat[7] * blat[7]);
    const ELPH_float b2_norm =
        sqrt(blat[2] * blat[2] + blat[5] * blat[5] + blat[8] * blat[8]);
    const ELPH_float Ecut_sqrt = sqrt(EcutRy);
    //
    ND_int Nx = rint(Ecut_sqrt / b0_norm + 1);
    ND_int Ny = rint(Ecut_sqrt / b1_norm + 1);
    ND_int Nz = rint(Ecut_sqrt / b2_norm + 1);
    // we have -ve index gvecs and 0, so 2*N + 1
    Nx = 2 * Nx + 1;
    Ny = 2 * Ny + 1;
    Nz = 2 * Nz + 1;
    //
    int comm_size, comm_rank;
    int mpi_error = MPI_Comm_size(commK, &comm_size);
    MPI_error_msg(mpi_error);
    mpi_error = MPI_Comm_rank(commK, &comm_rank);
    MPI_error_msg(mpi_error);
    // check if all cpus can accomidate atleast one gstick
    if (Nx * Ny < comm_size)
    {
        // the factor 1.01 is for numerical round off.
        double factor = sqrt((1.01 * (double)comm_size) / (Nx * Ny * 1.0));
        Nx = rint(1 + factor * Nx);
        Ny = rint(1 + factor * Ny);
        // make them odd
        if (0 == Nx % 2)
        {
            ++Nx;
        }
        if (0 == Ny % 2)
        {
            ++Ny;
        }
    }
    //
    fft_box[0] = Nx;
    fft_box[1] = Ny;
    fft_box[2] = Nz;
    // Make sure we have same number on all cpus. Does it happen?
    // Maybe who knows if we 4.499999999 and 4.5000000001
    // will yeild different numbers.
    mpi_error = MPI_Allreduce(MPI_IN_PLACE, fft_box, 3, ELPH_MPI_ND_INT,
                              MPI_MAX, commK);
    MPI_error_msg(mpi_error);
    return;
}
References ELPH_MPI_ND_INT, and MPI_error_msg.
Referenced by dV_add_longrange(), and interpolation_driver().
rotateGvecs()
void rotateGvecs (const ELPH_float * Gvecs, const ELPH_float * sym, const ND_int ngvecs, const ELPH_float * lat_vec, const bool inverse, const bool crystal, ELPH_float * G0, ELPH_float * Gvec_out)
Definition at line 15 of file rotate_Gvecs.c.
{
    /*
    this function rotates G vectors i.e \sum_j {Sij*Gj}
    Inputs :
    Gvecs -> unrotated gvecs ( in cart)
    sym -> 3x3 symmetric matrix
    ngvecs -> number of gvecs
    lat_vec -> lattice vectors a[i] = lat[:,i]
    inverse -> if true applies S^-1 instead of S
    crystal -> output in crystal coordinates. G0 will also be converted to
    crystal coordinates G0 --> (3) a const G vec all to all output vectors (in
    cart). Output : Gvec_out -> rotated Gvecs
    */
    /*
    need to do
    G@S^T-> cart
    G@S^T@lat_vec = G@(lat_vec^T@S)^T -> G_crys
    */
    for (ND_int i = 0; i < 3 * ngvecs; ++i)
    {
        Gvec_out[i] = 0;
    }
    ELPH_float sym_temp[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    const ELPH_float Iden3x3[9] = {1, 0, 0, 0, 1, 0, 0, 0, 1};
    char transsym = 'N';
    if (inverse)
    {
        transsym = 'T';
    }
    const ELPH_float* lat_temp = Iden3x3;
    if (crystal)
    {
        lat_temp = lat_vec;
    }
    Gemm3x3f(lat_temp, 'T', sym, transsym, sym_temp);
    matmul_float('N', 'T', Gvecs, sym_temp, Gvec_out, 1.0, 0.0, 3, 3, 3, ngvecs,
                 3, 3);
    if (G0 != NULL)
    {
        if (crystal)
        {
            // convert G0 to crystal.  //
            ELPH_float G0_temp[3];
            memcpy(G0_temp, G0, sizeof(ELPH_float) * 3);
            MatVec3f(lat_vec, G0_temp, true, G0);
        }
        ELPH_OMP_PAR_FOR_SIMD
        for (ND_int i = 0; i < ngvecs; ++i)
        {
            Gvec_out[3 * i] += G0[0];
            Gvec_out[3 * i + 1] += G0[1];
            Gvec_out[3 * i + 2] += G0[2];
        }
    }
}
References ELPH_OMP_PAR_FOR_SIMD, Gemm3x3f(), matmul_float(), and MatVec3f().
Referenced by electronic_reps(), and elphLocal().
Sort_pw()
void Sort_pw (const ND_int npw_tot, const ND_int npw_loc, const ND_int * fft_dims, const ELPH_float * gvec_in, const ELPH_cmplx * wfc_in, const ND_int nsets, ND_int * npw_loc_out, ND_int * nG_xy, int ** gvec_out, ELPH_cmplx ** wfc_out, MPI_Comm mpi_comm)
Definition at line 14 of file sortpw.c.
{
    /*
    This function sorts pws and wfcs and group them into z columns
    */
    /*
    First gather wfc and gvecs
    return local number of pws after sorting
    Note that buffers gvec_out and wfc_out must be
    freed outside of this function manually !
    */
    int my_rank, Comm_size, mpi_error;
    mpi_error = MPI_Comm_size(mpi_comm, &Comm_size);
    MPI_error_msg(mpi_error);
    mpi_error = MPI_Comm_rank(mpi_comm, &my_rank);
    MPI_error_msg(mpi_error);
    ELPH_float* all_Gvecs = NULL;
    ELPH_cmplx* wfc_root_buf = NULL;
    ELPH_cmplx* wfc_root_buf_sort = NULL;
    int* gvec_buf = NULL;
    int* counts_recv = NULL;
    int* displacements = NULL;
    int* counts_send = NULL;
    int* disp_send = NULL;
    ND_int* start_xy = NULL;
    ND_int* indices = NULL;
    ND_int* gxy_loc_comm = NULL;  // local number of gxy in each cpu
    if (npw_loc != get_mpi_local_size_idx(npw_tot, NULL, mpi_comm))
    {
        error_msg("npws mismatch while sorting");
    }
    if (my_rank == 0)
    {
        all_Gvecs = malloc(sizeof(ELPH_float) * npw_tot * 3);
        CHECK_ALLOC(all_Gvecs);
        gvec_buf = malloc(sizeof(int) * npw_tot * 3);
        CHECK_ALLOC(gvec_buf);
        counts_recv = malloc(4 * sizeof(int) * Comm_size);
        CHECK_ALLOC(counts_recv);
        indices = malloc(sizeof(ND_int) * npw_tot);
        CHECK_ALLOC(indices);
        start_xy = malloc(sizeof(ND_int) * fft_dims[0] * fft_dims[1]);
        CHECK_ALLOC(start_xy);
        gxy_loc_comm = malloc(sizeof(ND_int) * Comm_size);
        CHECK_ALLOC(gxy_loc_comm);
        displacements = counts_recv + Comm_size;
        counts_send = counts_recv + 2 * Comm_size;
        disp_send = counts_recv + 3 * Comm_size;
    }
    int pw_loc_int = npw_loc;
    mpi_error = MPI_Gather(&pw_loc_int, 1, MPI_INT, counts_recv, 1, MPI_INT, 0,
                           mpi_comm);
    MPI_error_msg(mpi_error);
    if (my_rank == 0)
    {
        int disp_rectemp = 0;
        for (int i = 0; i < Comm_size; ++i)
        {
            counts_recv[i] *= 3;
            displacements[i] = disp_rectemp;
            disp_rectemp += counts_recv[i];
        }
    }
    // gather to the root node
    mpi_error =
        MPI_Gatherv(gvec_in, 3 * npw_loc, ELPH_MPI_float, all_Gvecs,
                    counts_recv, displacements, ELPH_MPI_float, 0, mpi_comm);
    MPI_error_msg(mpi_error);
    Sorted_gvecs_idxs(npw_tot, all_Gvecs, indices);
    ND_int xycount;
    if (my_rank == 0)
    {
        xycount = 0;
        // initialize with gvecs which are out of the box
        int Gx_prev = fft_dims[0] + 10;
        int Gy_prev = fft_dims[1] + 10;
        for (ND_int ig = 0; ig < npw_tot; ++ig)
        {
            ND_int idx_temp = indices[ig];
            gvec_buf[3 * ig] = rint(all_Gvecs[3 * idx_temp]);
            gvec_buf[3 * ig + 1] = rint(all_Gvecs[3 * idx_temp + 1]);
            gvec_buf[3 * ig + 2] = rint(all_Gvecs[3 * idx_temp + 2]);
            if (gvec_buf[3 * ig + 1] != Gy_prev || gvec_buf[3 * ig] != Gx_prev)
            {
                Gx_prev = gvec_buf[3 * ig];
                Gy_prev = gvec_buf[3 * ig + 1];
                start_xy[xycount] = ig;
                ++xycount;
            }
        }
    }
    mpi_error = MPI_Bcast(&xycount, 1, ELPH_MPI_ND_INT, 0, mpi_comm);
    MPI_error_msg(mpi_error);
    *nG_xy = get_mpi_local_size_idx(xycount, NULL, mpi_comm);
    mpi_error = MPI_Gather(nG_xy, 1, ELPH_MPI_ND_INT, gxy_loc_comm, 1,
                           ELPH_MPI_ND_INT, 0, mpi_comm);
    MPI_error_msg(mpi_error);
    if (my_rank == 0)
    {
        /* calc the npw for each cpu */
        ND_int xy_disp = 0;
        for (int i = 0; i < Comm_size; ++i)
        {
            // this is number of pw per code
            ND_int xy_in_this_cpu = gxy_loc_comm[i];
            ND_int xy_prev = xy_disp;
            xy_disp += xy_in_this_cpu;
            if (xy_disp < xycount)
            {
                counts_send[i] = start_xy[xy_disp] - start_xy[xy_prev];
            }
            else
            {
                counts_send[i] = npw_tot - start_xy[xy_prev];
            }
            counts_send[i] *= 3;
            disp_send[i] = 3 * start_xy[xy_prev];
        }
    }
    int npw_this_cpu;
    mpi_error = MPI_Scatter(counts_send, 1, MPI_INT, &npw_this_cpu, 1, MPI_INT,
                            0, mpi_comm);
    MPI_error_msg(mpi_error);
    // note we send 3*npws, so we divide by 3 now
    npw_this_cpu = npw_this_cpu / 3;
    *npw_loc_out = npw_this_cpu;
    *gvec_out = malloc(sizeof(int) * 3 * npw_this_cpu);
    CHECK_ALLOC(*gvec_out);
    // scatter gvecs
    mpi_error = MPI_Scatterv(gvec_buf, counts_send, disp_send, MPI_INT,
                             *gvec_out, 3 * npw_this_cpu, MPI_INT, 0, mpi_comm);
    MPI_error_msg(mpi_error);
    free(gxy_loc_comm);
    free(start_xy);
    free(all_Gvecs);
    free(gvec_buf);
    *wfc_out = malloc(sizeof(ELPH_cmplx) * npw_this_cpu * nsets);
    CHECK_ALLOC(*wfc_out);
    if (my_rank == 0)
    {
        wfc_root_buf = malloc(sizeof(ELPH_cmplx) * npw_tot);
        CHECK_ALLOC(wfc_root_buf);
        wfc_root_buf_sort = malloc(sizeof(ELPH_cmplx) * npw_tot);
        CHECK_ALLOC(wfc_root_buf_sort);
        for (int i = 0; i < Comm_size; ++i)
        {
            counts_send[i] /= 3;
            disp_send[i] /= 3;
            displacements[i] /= 3;
            counts_recv[i] /= 3;
        }
    }
    for (ND_int iset = 0; iset < nsets; ++iset)
    {
        const ELPH_cmplx* wfin = wfc_in + iset * npw_loc;
        ELPH_cmplx* wfout = *wfc_out + iset * npw_this_cpu;
        mpi_error = MPI_Gatherv(wfin, npw_loc, ELPH_MPI_cmplx, wfc_root_buf,
                                counts_recv, displacements, ELPH_MPI_cmplx, 0,
                                mpi_comm);
        MPI_error_msg(mpi_error);
        /* sort */
        if (my_rank == 0)
        {
            for (ND_int ig = 0; ig < npw_tot; ++ig)
            {
                ND_int idx_temp = indices[ig];
                wfc_root_buf_sort[ig] = wfc_root_buf[idx_temp];
            }
        }
        mpi_error = MPI_Scatterv(wfc_root_buf_sort, counts_send, disp_send,
                                 ELPH_MPI_cmplx, wfout, npw_this_cpu,
                                 ELPH_MPI_cmplx, 0, mpi_comm);
        MPI_error_msg(mpi_error);
    }
    free(indices);
    free(wfc_root_buf);
    free(wfc_root_buf_sort);
    free(counts_recv);
}
References CHECK_ALLOC, ELPH_MPI_cmplx, ELPH_MPI_float, ELPH_MPI_ND_INT, error_msg, get_mpi_local_size_idx(), MPI_error_msg, and Sorted_gvecs_idxs().
Referenced by elphLocal().
SU2mat()
void SU2mat (const ELPH_float * sym_in, const ND_int nspinor, const bool invert_sym, const bool time_rev, ELPH_cmplx * su2mat)
Definition at line 16 of file su2mat.c.
{
    if (nspinor == 1)
    {
        su2mat[0] = 1.0;
        return;
    }
    /* Convert to proper rotations */
    ELPH_float det = det3x3(sym_in);
    // printf("det : %f \n",det);
    if (fabs(fabs(det) - 1) > 1e-4)
    {
        error_msg("Wrong symmetric matrices");
    }
    ELPH_float sym[9];
    for (int i = 0; i < 9; ++i)
    {
        sym[i] = sym_in[i] / det;
    }
    ELPH_cmplx pauli0[4] = {1, 0, 0, 1};
    ELPH_cmplx paulix[4] = {0, 1, 1, 0};
    ELPH_cmplx pauliy[4] = {0, -I, I, 0};
    ELPH_cmplx pauliz[4] = {1, 0, 0, -1};
    ELPH_float alpha, beta, delta;
    if (fabs(sym[6] + 1) < ELPH_EPS)
    {
        alpha = 0;
        beta = ELPH_PI / 2.0;
        delta = atan2(sym[1], sym[2]);
    }
    else if (fabs(sym[6] - 1) < ELPH_EPS)
    {
        alpha = 0;
        beta = -ELPH_PI / 2.0;
        delta = atan2(-sym[1], -sym[2]);
    }
    else
    {
        beta = -asin(sym[6]);
        alpha = atan2(sym[3] / cos(beta), sym[0] / cos(beta));
        delta = atan2(sym[7] / cos(beta), sym[8] / cos(beta));
    }
    alpha = alpha / 2;
    beta = beta / 2;
    delta = delta / 2;
    ELPH_cmplx su_delta[4], su_beta[4], su_alpha[4];
    for (int i = 0; i < 4; ++i)
    {
        su_delta[i] = cos(delta) * pauli0[i] - I * sin(delta) * paulix[i];
        su_beta[i] = cos(beta) * pauli0[i] - I * sin(beta) * pauliy[i];
        su_alpha[i] = cos(alpha) * pauli0[i] - I * sin(alpha) * pauliz[i];
    }
    ELPH_cmplx tempsu[4];
    matmul_Cmpl2x2(su_beta, su_delta, tempsu);
    matmul_Cmpl2x2(su_alpha, tempsu, su2mat);
    // In case of time reversel we have -I*sigma_y
    if (time_rev)
    { /* Note this is not commutative */
        ELPH_cmplx a1, b1, c1, d1;
        a1 = su2mat[0];
        b1 = su2mat[1];
        c1 = su2mat[2];
        d1 = su2mat[3];
        su2mat[0] = -c1;
        su2mat[1] = -d1;
        su2mat[2] = a1;
        su2mat[3] = b1;
/* The below if def is due to backward compatiblity. In Yambo ver <= 5.12, the
pauli matrix are not correct. so due to this it picks up an additional phase
factor of -1 for time_rev matrix */
#if defined(YAMBO_LT_5_1)
        for (int is11 = 0; is11 < 4; ++is11)
        {
            su2mat[is11] = -su2mat[is11];
        }
#endif
    }
    if (invert_sym)
    {
        ELPH_cmplx b1 = conj(su2mat[1]);
        su2mat[0] = conj(su2mat[0]);
        su2mat[3] = conj(su2mat[3]);
        su2mat[1] = conj(su2mat[2]);
        su2mat[2] = b1;
    }
}
References det3x3(), ELPH_EPS, ELPH_PI, error_msg, and matmul_Cmpl2x2().
Referenced by add_elphNonLocal(), electronic_reps(), elphLocal(), and rotate_dvscf().
su2rotate()
void su2rotate (const int nspinor, const ND_int npw, const ND_int nsets, const ELPH_cmplx * su2mat, ELPH_cmplx * wfc)
Definition at line 13 of file su2rotate.c.
{
    /*
    \sum_j su_ij *wfc_njG -> wfc_niG
    Note this is inplace operation, so it will modify the input
    */
    if (nspinor != 2)
    {
        return;
    }
    ND_int stride_wfc = nspinor * npw;  // i.e 2*npw
    for (ND_int iset = 0; iset < nsets; ++iset)
    {
        ELPH_cmplx* wfc_up = wfc + iset * stride_wfc;
        ELPH_cmplx* wfc_dw = wfc + iset * stride_wfc + npw;
        ELPH_OMP_PAR_FOR_SIMD
        for (ND_int ipw = 0; ipw < npw; ++ipw)
        {
            ELPH_cmplx temp = wfc_up[ipw] * su2mat[0] + wfc_dw[ipw] * su2mat[1];
            wfc_dw[ipw] = wfc_up[ipw] * su2mat[2] + wfc_dw[ipw] * su2mat[3];
            wfc_up[ipw] = temp;
        }
    }
}
References ELPH_OMP_PAR_FOR_SIMD.
Referenced by add_elphNonLocal(), electronic_reps(), and elphLocal().