LetzElPhC: src/wfc/trans_wfc.c File Reference
trans_wfc.c File Reference
#include <complex.h>
#include <stdbool.h>
#include "common/constants.h"
#include "common/numerical_func.h"
#include "common/omp_pragma_def.h"
#include "elphC.h"
#include "wfc.h"
Functions
void apply_trans_wfc (const ELPH_float *trans_vec, const ELPH_float *kvec, const ND_int nsets, const ND_int npw, const ELPH_float *gvecs, ELPH_cmplx *wfc_G, const bool conjugate)
Function Documentation
apply_trans_wfc()
void apply_trans_wfc (const ELPH_float * trans_vec, const ELPH_float * kvec, const ND_int nsets, const ND_int npw, const ELPH_float * gvecs, ELPH_cmplx * wfc_G, const bool conjugate)
Definition at line 15 of file trans_wfc.c.
{
    /*
    This is an in-place function. wfc_G (nsets,npw) will be over written.
    If conjugate is true, the output is conjugated
    T(a) C_G * e^{i(G+k).r} = C_G * e^{i(G+k).r} * e^{-i(G+k).a}
    note : trans_vec, kvec, gvecs can be in crystal/cart coordinates but
    we must use the same for all. kvec and gvecs must be in 2*pi units
    when using cart coordinates.
    */
    // first compute the phase from k i.e e^{-ik*a}
    ELPH_cmplx kphase = cexp(-I * 2 * ELPH_PI * dot3_macro(kvec, trans_vec));
    for (ND_int iset = 0; iset < nsets; ++iset)
    {
        ELPH_cmplx* wfc_G_tmp = wfc_G + iset * npw;
        ELPH_OMP_PAR_FOR_SIMD
        for (ND_int ig = 0; ig < npw; ++ig)
        {
            const ELPH_float* gvec_tmp = gvecs + 3 * ig;
            ELPH_cmplx gphase = kphase * cexp(-I * 2 * ELPH_PI *
                                              dot3_macro(gvec_tmp, trans_vec));
            wfc_G_tmp[ig] *= gphase;
            if (conjugate)
            {
                wfc_G_tmp[ig] = conj(wfc_G_tmp[ig]);
            }
        }
    }
}
References dot3_macro, ELPH_OMP_PAR_FOR_SIMD, and ELPH_PI.
Referenced by add_elphNonLocal(), electronic_reps(), and elphLocal().