LetzElPhC: src/wfc/gsort.c File Reference
gsort.c File Reference
#include "gsort.h"
#include <math.h>
#include <stdlib.h>
#include "common/error.h"
#include "elphC.h"
Macros
#define COMP_AB(A, B)
Functions
static int gsort_cmp (const void *a, const void *b)
void Sorted_gvecs_idxs (const ND_int npw, ELPH_float *gvecs, ND_int *indices)
void find_gvecs_idxs (const ND_int nsearchs, ELPH_float *search_gvecs, const ND_int npw, ELPH_float *gvecs, ND_int *out_idx)
Macro Definition Documentation
COMP_AB
#define COMP_AB (A, B)
Value:
((A > B) - (A < B))
Definition at line 12 of file gsort.c.
Referenced by gsort_cmp().
Function Documentation
find_gvecs_idxs()
void find_gvecs_idxs (const ND_int nsearchs, ELPH_float * search_gvecs, const ND_int npw, ELPH_float * gvecs, ND_int * out_idx)
Definition at line 49 of file gsort.c.
{
    /*
    find the indices of elements in search_gvecs in gvecs list
    // gvecs and search_gvecs are in crystal coordinates
    size of out_idx : nsearchs
    */
    if (gvecs == NULL || search_gvecs == NULL)
    {
        return;
    }
    ELPH_float** gvec_ptrs = malloc(sizeof(ELPH_float*) * npw);
    CHECK_ALLOC(gvec_ptrs);
    /* fill the array */
    for (ND_int i = 0; i < npw; ++i)
    {
        gvec_ptrs[i] = gvecs + 3 * i;
    }
    qsort(gvec_ptrs, npw, sizeof(ELPH_float*), gsort_cmp);
    // now we find the match index in gvec_ptrs
    for (ND_int isearch = 0; isearch < nsearchs; ++isearch)
    {
        ELPH_float* tmp_gvec = search_gvecs + 3 * isearch;
        ELPH_float** search_ptr =
            bsearch(&tmp_gvec, gvec_ptrs, npw, sizeof(ELPH_float*), gsort_cmp);
        if (search_ptr != NULL)
        {
            out_idx[isearch] = (*search_ptr - gvecs) / 3;
        }
        else
        {
            out_idx[isearch] = -1;
        }
    }
    free(gvec_ptrs);
}
References CHECK_ALLOC, and gsort_cmp().
Referenced by electronic_reps().
gsort_cmp()
int gsort_cmp (const void * a, const void * b) static
Definition at line 95 of file gsort.c.
{
    /*
    First sorts along x, then y and finally z
    */
    ELPH_float* v1 = *(ELPH_float**)a;
    ELPH_float* v2 = *(ELPH_float**)b;
    ND_int Gax, Gay, Gaz;
    ND_int Gbx, Gby, Gbz;
    Gax = rint(v1[0]);
    Gay = rint(v1[1]);
    Gaz = rint(v1[2]);
    Gbx = rint(v2[0]);
    Gby = rint(v2[1]);
    Gbz = rint(v2[2]);
    if (Gax == Gbx)
    {
        if (Gay == Gby)
        {
            return COMP_AB(Gaz, Gbz);
        }
        else
        {
            return COMP_AB(Gay, Gby);
        }
    }
    else
    {
        return COMP_AB(Gax, Gbx);
    }
}
References COMP_AB.
Referenced by find_gvecs_idxs(), and Sorted_gvecs_idxs().
Sorted_gvecs_idxs()
void Sorted_gvecs_idxs (const ND_int npw, ELPH_float * gvecs, ND_int * indices)
Definition at line 16 of file gsort.c.
{
    /*
    Sort gvecs into groups(zcoloumns with same (x,y)).
    return sorted indices (like np.argsort)
    // gvecs in crystal coordinates
    */
    if (gvecs == NULL)
    {
        return;
    }
    ELPH_float** gvec_ptrs = malloc(sizeof(ELPH_float*) * npw);
    CHECK_ALLOC(gvec_ptrs);
    /* fill the struct */
    for (ND_int i = 0; i < npw; ++i)
    {
        gvec_ptrs[i] = gvecs + 3 * i;
    }
    qsort(gvec_ptrs, npw, sizeof(ELPH_float*), gsort_cmp);
    // store the sorted indices
    for (ND_int i = 0; i < npw; ++i)
    {
        indices[i] = (gvec_ptrs[i] - gvecs) / 3;
    }
    free(gvec_ptrs);
}
References CHECK_ALLOC, and gsort_cmp().
Referenced by Sort_pw().