LetzElPhC: src/phonon/phonon.h File Reference
phonon.h File Reference
#include "common/dtypes.h"
#include "elphC.h"
Functions
void mass_normalize_pol_vecs (const ELPH_float *atomic_masses, const ND_int nsets, const ND_int natoms, const ELPH_float power, ELPH_cmplx *pol_vecs)
void pol_vecs_to_dyn (const ELPH_float *omega, const ND_int natom, const ELPH_float *atomic_masses, ELPH_cmplx *pol_vecs)
void add_ph_dyn_long_range (const ELPH_float *qpt, struct Lattice *lattice, struct Phonon *phonon, const ND_int *Ggrid, const ND_int sign, const ELPH_float *atomic_masses, ELPH_cmplx *dyn_mat_asr, ELPH_cmplx *dyn_mat)
void compute_dyn_lr_asr_correction (struct Lattice *lattice, struct Phonon *phonon, const ND_int *Ggrid, const ELPH_float *atomic_masses, ELPH_cmplx *dyn_mat_asr)
Function Documentation
add_ph_dyn_long_range()
void add_ph_dyn_long_range (const ELPH_float * qpt, struct Lattice * lattice, struct Phonon * phonon, const ND_int * Ggrid, const ND_int sign, const ELPH_float * atomic_masses, ELPH_cmplx * dyn_mat_asr, ELPH_cmplx * dyn_mat)
Definition at line 27 of file dyn_long_range.c.
{
    // compute the long range part
    add_ph_dyn_long_range_internal(qpt, lattice, phonon, Ggrid, sign,
                                   atomic_masses, dyn_mat);
    // now subtract the asr correction
    //
    ELPH_float factor = -1;
    if (sign < 0)
    {
        factor = -factor;
    }
    ND_int nmodes = lattice->natom * 3;
    //
    for (ND_int ia = 0; ia < lattice->natom; ++ia)
    {
        ELPH_cmplx* tmp_buf_ia = dyn_mat_asr + ia * 9;
        for (ND_int i = 0; i < 3; ++i)
        {
            for (ND_int j = 0; j < 3; ++j)
            {
                dyn_mat[(ia * 3 + i) * nmodes + ia * 3 + j] +=
                    factor * tmp_buf_ia[3 * i + j];
            }
        }
    }
}
References add_ph_dyn_long_range_internal(), and Lattice::natom.
Referenced by interpolation_driver().
compute_dyn_lr_asr_correction()
void compute_dyn_lr_asr_correction (struct Lattice * lattice, struct Phonon * phonon, const ND_int * Ggrid, const ELPH_float * atomic_masses, ELPH_cmplx * dyn_mat_asr)
Definition at line 59 of file dyn_long_range.c.
{
    // ASR for the lr non-analytical dynamical matrix.
    // (dyn_mat_asr) : (natom, 3, 3)
    // See X. Gonze  PhysRevB.50.13035
    //
    for (ND_int i = 0; i < lattice->natom * 9; ++i)
    {
        dyn_mat_asr[i] = 0.0;
    }
    if (!phonon->epsilon || !phonon->Zborn)
    {
        return;
    }
    ND_int nmodes = 3 * lattice->natom;
    ELPH_cmplx* tmp_dyn_mat = calloc(nmodes * nmodes, sizeof(*tmp_dyn_mat));
    CHECK_ALLOC(tmp_dyn_mat);
    // let the comiplers remove this loop.
    for (ND_int i = 0; i < nmodes * nmodes; ++i)
    {
        tmp_dyn_mat[i] = 0.0;
    }
    ELPH_float qpt_zero[3] = {0.0, 0.0, 0.0};
    add_ph_dyn_long_range_internal(qpt_zero, lattice, phonon, Ggrid, 1,
                                   atomic_masses, tmp_dyn_mat);
    //
    for (ND_int ia = 0; ia < lattice->natom; ++ia)
    {
        ELPH_cmplx* tmp_buf_ia = dyn_mat_asr + ia * 9;
        for (ND_int ja = 0; ja < lattice->natom; ++ja)
        {
            for (ND_int i = 0; i < 3; ++i)
            {
                for (ND_int j = 0; j < 3; ++j)
                {
                    tmp_buf_ia[3 * i + j] +=
                        tmp_dyn_mat[(ia * 3 + i) * nmodes + ja * 3 + j];
                }
            }
        }
    }
    free(tmp_dyn_mat);
}
References add_ph_dyn_long_range_internal(), CHECK_ALLOC, Phonon::epsilon, Lattice::natom, and Phonon::Zborn.
Referenced by interpolation_driver().
mass_normalize_pol_vecs()
void mass_normalize_pol_vecs (const ELPH_float * atomic_masses, const ND_int nsets, const ND_int natoms, const ELPH_float power, ELPH_cmplx * pol_vecs)
Definition at line 10 of file normalize_pol_vecs.c.
{
    // pol_vecs (nsets, natom,3);
    // atomic_masses (natom)
    // does  e^v_ix = Mi^power * e^v_ix
    //
    for (ND_int imode = 0; imode < nsets; ++imode)
    {
        for (ND_int ia = 0; ia < natoms; ++ia)
        {
            ELPH_float mass_tmp = pow(atomic_masses[ia], power);
            for (ND_int i = 0; i < 3; ++i)
            {
                pol_vecs[imode * 3 * natoms + ia * 3 + i] *= mass_tmp;
            }
        }
    }
}
Referenced by interpolation_driver(), and pol_vecs_to_dyn().
pol_vecs_to_dyn()
void pol_vecs_to_dyn (const ELPH_float * omega, const ND_int natom, const ELPH_float * atomic_masses, ELPH_cmplx * pol_vecs)
Definition at line 13 of file pol_vecs_to_dyn.c.
{
    ND_int nmodes = 3 * natom;
    ELPH_cmplx* tmp_buf = malloc(2 * sizeof(*tmp_buf) * nmodes * nmodes);
    CHECK_ALLOC(tmp_buf);
    // mass normalize
    mass_normalize_pol_vecs(atomic_masses, nmodes, natom, 0.5, pol_vecs);
    //
    memcpy(tmp_buf, pol_vecs, sizeof(*tmp_buf) * nmodes * nmodes);
    memcpy(tmp_buf + nmodes * nmodes, pol_vecs,
           sizeof(*tmp_buf) * nmodes * nmodes);
    //
    for (ND_int i = 0; i < nmodes; ++i)
    {
        ELPH_float factor = omega[i] > 0 ? 1.0 : -1.0;
        factor = factor * omega[i] * omega[i];
        for (ND_int j = 0; j < nmodes; ++j)
        {
            tmp_buf[i * nmodes + j] = factor * conj(tmp_buf[i * nmodes + j]);
        }
    }
    matmul_cmplx('T', 'N', tmp_buf + nmodes * nmodes, tmp_buf, pol_vecs, 1.0,
                 0.0, nmodes, nmodes, nmodes, nmodes, nmodes, nmodes);
    free(tmp_buf);
}
References CHECK_ALLOC, mass_normalize_pol_vecs(), and matmul_cmplx().
Referenced by interpolation_driver().