LetzElPhC: src/fft/fft.h File Reference
fft.h File Reference
#include "elphC.h"
#include <complex.h>
#include <fftw3.h>
#include <mpi.h>
#include <stdbool.h>
Data Structures
struct ELPH_fft_plan
Macros
#define fftw_fun(FUN_NAME)
#define fftw3_fun_HIDDEN(FUN_NAME)
Functions
typedef fftw_fun (plan) fftw_generic_plan
ND_int alignment_len (void)
void wfc_plan (struct ELPH_fft_plan *plan, const ND_int ngvecs_loc, const ND_int nzloc, const ND_int nGxyloc, const int *gvecs, const ND_int *fft_dims, unsigned fft_flags, MPI_Comm comm)
void wfc_destroy_plan (struct ELPH_fft_plan *plan)
void fft3D (struct ELPH_fft_plan *plan, const ND_int nsets, ELPH_cmplx *wfcr, ELPH_cmplx *wfcG, const bool conjugate)
void invfft3D (struct ELPH_fft_plan *plan, const ND_int nsets, ELPH_cmplx *wfcG, ELPH_cmplx *wfcr, const bool conjugate)
void fwd_transpose (struct ELPH_fft_plan *plan)
void bwd_transpose (struct ELPH_fft_plan *plan)
void fft_convolution3D (struct ELPH_fft_plan *plan, const ND_int nspinor, ND_int nmag, const ELPH_cmplx *Vpotr, const ELPH_cmplx *psir, ELPH_cmplx *wfcG, const bool conjugate)
Macro Definition Documentation
fftw3_fun_HIDDEN
#define fftw3_fun_HIDDEN (FUN_NAME)
Value:
fftwf_##FUN_NAME
Definition at line 17 of file fft.h.
fftw_fun
#define fftw_fun (FUN_NAME)
Value:
fftw3_fun_HIDDEN(FUN_NAME)
Definition at line 16 of file fft.h.
Referenced by alignment_len(), elph_driver(), fft3D(), fft_convolution3D(), fft_q2R(), invfft3D(), wfc_destroy_plan(), and wfc_plan().
Function Documentation
alignment_len()
ND_int alignment_len (void)
Definition at line 12 of file align.c.
{
    /* get the aligment len in units of sizeof(ELPH_cmplx) bytes*/
    static ND_int align_len = -1;
    if (align_len > 0)
    {
        return align_len;
    }
    //
    align_len = ELPH_FFTW_SIMD_LEN + 10;
    ND_int temp_len = sizeof(ELPH_cmplx) * ELPH_FFTW_SIMD_LEN;
    ELPH_cmplx* temp = fftw_fun(malloc)(temp_len);
    CHECK_ALLOC(temp);
    // first get the alignment value of temp;
    int buf_alignment = fftw_fun(alignment_of)((void*)temp);
    for (int i = 1; i < ELPH_FFTW_SIMD_LEN; ++i)
    {
        ELPH_cmplx* ptr = temp + i;
        int ptr_align = fftw_fun(alignment_of)((void*)ptr);
        if (ptr_align == buf_alignment)
        {
            align_len = i;
            break;
        }
    }
    fftw_fun(free)(temp);
    if (align_len >= ELPH_FFTW_SIMD_LEN)
    {
        error_msg("Error determining simd len");
    }
    return align_len;
}
References CHECK_ALLOC, ELPH_FFTW_SIMD_LEN, error_msg, and fftw_fun.
Referenced by wfc_plan().
bwd_transpose()
void bwd_transpose (struct ELPH_fft_plan * plan)
Definition at line 53 of file transpose.c.
{
    /* This performs a transpose from
    (nGxy_loc,Nz)  -> (nGxy,Nz_loc)
    The input and output are stored in plan->nz_buf
    plan->fft_buf is used as scratch space
    */
    /*
    Perform Alltoallv plan->nz_buf -> plan->fft_buf
    */
    int mpi_error;
    int ncpus;
    mpi_error = MPI_Comm_size(plan->comm, &ncpus);
    MPI_error_msg(mpi_error);
    int* gxy_counts = plan->comm_bufs;
    int* xy_disp = gxy_counts + ncpus;
    int* z_counts = gxy_counts + 2 * ncpus;
    int* z_disp = gxy_counts + 3 * ncpus;
    /*
    we need to redistribute and store to plan->fft_data */
    for (ND_int ig = 0; ig < plan->nGxyloc; ++ig)
    {
        ELPH_cmplx* src_ptr = plan->nz_buf + ig * plan->fft_dims[2];
        for (ND_int i = 0; i < ncpus; ++i)
        {
            ND_int zcount_tmp = z_counts[i] / plan->nGxyloc;
            ND_int z_disp_tmp = z_disp[i] / plan->nGxyloc;
            ELPH_cmplx* dest_ptr = plan->fft_data + z_disp[i] + ig * zcount_tmp;
            memcpy(dest_ptr, src_ptr + z_disp_tmp,
                   sizeof(ELPH_cmplx) * zcount_tmp);
        }
    }
    // Now plan->fft_data has the data. scatter back to plan->nz_buf
    mpi_error = MPI_Alltoallv(plan->fft_data, z_counts, z_disp, ELPH_MPI_cmplx,
                              plan->nz_buf, gxy_counts, xy_disp, ELPH_MPI_cmplx,
                              plan->comm);
    MPI_error_msg(mpi_error);
}
References ELPH_fft_plan::comm, ELPH_fft_plan::comm_bufs, ELPH_MPI_cmplx, ELPH_fft_plan::fft_data, ELPH_fft_plan::fft_dims, MPI_error_msg, ELPH_fft_plan::nGxyloc, and ELPH_fft_plan::nz_buf.
Referenced by invfft3D().
fft3D()
void fft3D (struct ELPH_fft_plan * plan, const ND_int nsets, ELPH_cmplx * wfcr, ELPH_cmplx * wfcG, const bool conjugate)
Definition at line 13 of file fwdfft.c.
{
    /*
    Note: if conjugate is true, then the output of FFT is conjugated
    a) FFT along xy and  (Nx,Ny,Nz_loc)-> (Gx, Gy, Nz_loc)
    b) scatter Gx,Gy to different cpus to perform fft along x and y.
        *Note that we use scatter instead of alltoallv so that some FFTs
        can be computed while being communicating
    c) Perform FFT along Z
    d) box to sphere
    */
    ND_int Nx = plan->fft_dims[0];
    ND_int Ny = plan->fft_dims[1];
    ND_int Nz = plan->fft_dims[2];
    ELPH_float norm = Nx * Ny * Nz;
    norm = 1.0 / norm;
    ND_int Ny_stride = plan->nzloc * Ny;
    ND_int fft_buf_size = Nx * Ny * plan->nzloc;
    for (ND_int iset = 0; iset < nsets; ++iset)
    {
        ELPH_cmplx* wfcr_tmp = wfcr + iset * fft_buf_size;
        ELPH_cmplx* wfcG_tmp = wfcG + iset * plan->ngvecs_loc;
        ND_int ia = fftw_fun(alignment_of)((void*)wfcr_tmp);
        ia /= sizeof(ELPH_cmplx);
        // a) (i) FFT along X
        fftw_fun(execute_dft)(plan->fplan_x[ia], wfcr_tmp, wfcr_tmp);
        // a) (ii) FFT along Y
        for (ND_int ix = 0; ix < plan->fft_dims[0]; ++ix)
        {
            if (!(plan->gx_inGvecs[ix]))
            {
                continue;
            }
            ELPH_cmplx* wfcr_tmp_y =
                wfcr_tmp + ix * Ny_stride;  //(Gx,Ny,Nz_log)
            ND_int iax = fftw_fun(alignment_of)((void*)wfcr_tmp_y);
            iax /= sizeof(ELPH_cmplx);
            fftw_fun(execute_dft)(plan->fplan_y[iax], wfcr_tmp_y, wfcr_tmp_y);
        }
        // b) (i) pack the data for transpose
        for (ND_int ixy = 0; ixy < plan->nGxy; ++ixy)
        {
            ND_int Gx = plan->Gxy_total[2 * ixy];
            ND_int Gy = plan->Gxy_total[2 * ixy + 1];
            // [Gx,Gy,0] =  Gx*Ny*Nzloc + Gy*Nzloc
            ELPH_cmplx* xy_buf = wfcr_tmp + plan->nzloc * (Gy + Gx * Ny);
            // (Nxy,Zloc)
            memcpy(plan->nz_buf + ixy * plan->nzloc, xy_buf,
                   sizeof(ELPH_cmplx) * plan->nzloc);
        }
        // b) (ii)  transpose the data
        fwd_transpose(plan);  // nz_buf has (NGxy_loc,Nz)
        // c) perform fft along z
        fftw_fun(execute)(plan->fplan_z);
        // d) box to sphere
        ND_int igvec = 0;
        for (ND_int ixy = 0; ixy < plan->nGxyloc; ++ixy)
        {
            ELPH_cmplx* zfft_ptr = plan->nz_buf + ixy * Nz;
            for (ND_int ig = 0; ig < plan->ngxy_z[ixy]; ++ig)
            {
                ND_int Gz = plan->gvecs[3 * igvec + 2];
                if (Gz < 0)
                {
                    Gz += Nz;
                }
                wfcG_tmp[igvec] = zfft_ptr[Gz] * norm;
                if (conjugate)
                {
                    wfcG_tmp[igvec] = conj(wfcG_tmp[igvec]);
                }
                ++igvec;
            }
        }
        if (igvec != plan->ngvecs_loc)
        {
            error_msg("Gvec mismatch in fwd execute. ");
        }
    }
}
References error_msg, ELPH_fft_plan::fft_dims, fftw_fun, ELPH_fft_plan::fplan_x, ELPH_fft_plan::fplan_y, ELPH_fft_plan::fplan_z, fwd_transpose(), ELPH_fft_plan::gvecs, ELPH_fft_plan::gx_inGvecs, ELPH_fft_plan::Gxy_total, ELPH_fft_plan::ngvecs_loc, ELPH_fft_plan::nGxy, ELPH_fft_plan::ngxy_z, ELPH_fft_plan::nGxyloc, ELPH_fft_plan::nz_buf, and ELPH_fft_plan::nzloc.
fft_convolution3D()
void fft_convolution3D (struct ELPH_fft_plan * plan, const ND_int nspinor, ND_int nmag, const ELPH_cmplx * Vpotr, const ELPH_cmplx * psir, ELPH_cmplx * wfcG, const bool conjugate)
Definition at line 13 of file convolution.c.
{
    /*
    Note: if conjugate is true, then the output of convolution is conjugated.
    a) FFt along X for V(r)*psi(r) followed by fft along z
    if nmag = 1 or 2, "i,si=>si"
    if nmag = 4, "rsxyz,sxyz->rxyz"
    b) scatter Gx,Gy to different cpus to perform fft along x and y.
        *Note that we use scatter instead of alltoallv so that some FFTs
        can be computed while being communicating
    c) Perform FFT along Z
    d) box to sphere
    */
    // basic checks
    if (nspinor == 1)
    {
        nmag = 1;
    }
    if (nmag != 1 && nmag != 4)
    {
        error_msg("Error wrong nmag value.");
    }
    if (nmag == 4 && nspinor != 2)
    {
        error_msg("Error wrong nmag and nspinor combination.");
    }
    if (nspinor > 2)
    {
        error_msg("nspinor must be <= 2.");
    }
    /*
    In case of nmag  = 2 (i.e lsda), we have two V(r) for each spin component.
    so this can be treated as nmag = 1 case
    */
    // first some basic stuff
    ND_int Nx = plan->fft_dims[0];
    ND_int Ny = plan->fft_dims[1];
    ND_int Nz = plan->fft_dims[2];
    ELPH_float norm = Nx * Ny * Nz;
    norm = 1.0 / norm;
    ND_int Ny_stride = plan->nzloc * Ny;
    ND_int fft_buf_size = Nx * Ny * plan->nzloc;
    for (ND_int ispinor = 0; ispinor < nspinor; ++ispinor)
    {
        ELPH_cmplx* wfcG_tmp = wfcG + ispinor * plan->ngvecs_loc;
        const ELPH_cmplx* dV_r = Vpotr;
        // we store V(r)*psi(r) in plan->fft_data and perform FFT
        /* now we do blocking to reuse cache. we divide into Ny blocks and
            perform convolution and FFT */
        if (nmag == 1)
        {
            const ELPH_cmplx* psi_spinor = psir + ispinor * fft_buf_size;
            for (ND_int iy = 0; iy < Ny; ++iy)
            {
                ND_int iyshift = iy * plan->nzloc;
                for (ND_int ix = 0; ix < Nx; ++ix)
                {
                    ND_int ixshift = ix * Ny * plan->nzloc + iyshift;
                    ELPH_cmplx* dvpsi_xyz = plan->fft_data + ixshift;
                    const ELPH_cmplx* psi_xyz = psi_spinor + ixshift;
                    const ELPH_cmplx* dV_xyz = dV_r + ixshift;
                    for (ND_int iz = 0; iz < plan->nzloc; ++iz)
                    {
                        dvpsi_xyz[iz] = psi_xyz[iz] * dV_xyz[iz];
                    }
                }
                // perform the fft along X
                ELPH_cmplx* dvpsi_ptr = plan->fft_data + iyshift;
                ND_int iax = fftw_fun(alignment_of)((void*)(dvpsi_ptr));
                iax /= sizeof(ELPH_cmplx);
                fftw_fun(execute_dft)(plan->cplan_x[iax], dvpsi_ptr, dvpsi_ptr);
            }
        }
        else
        {
            if (ispinor == 1)
            {
                dV_r = Vpotr + 2 * fft_buf_size;
            }  // [1,2],[3,4]
            for (ND_int iy = 0; iy < Ny; ++iy)
            {
                ND_int iyshift = iy * plan->nzloc;
                for (ND_int ix = 0; ix < Nx; ++ix)
                {
                    ND_int ixshift = ix * Ny * plan->nzloc + iyshift;
                    ELPH_cmplx* dvpsi_out = plan->fft_data + ixshift;
                    const ELPH_cmplx* psi0 = psir + ixshift;
                    const ELPH_cmplx* psi1 = psir + ixshift + fft_buf_size;
                    const ELPH_cmplx* dV0 = dV_r + ixshift;
                    const ELPH_cmplx* dV1 = dV_r + ixshift + fft_buf_size;
                    for (ND_int iz = 0; iz < plan->nzloc; ++iz)
                    {
                        dvpsi_out[iz] = psi0[iz] * dV0[iz] + psi1[iz] * dV1[iz];
                    }
                }
                // perform the fft along X
                ELPH_cmplx* dvpsi_ptr = plan->fft_data + iyshift;
                ND_int iax = fftw_fun(alignment_of)((void*)(dvpsi_ptr));
                iax /= sizeof(ELPH_cmplx);
                fftw_fun(execute_dft)(plan->cplan_x[iax], dvpsi_ptr, dvpsi_ptr);
            }
        }
        // a) (ii) FFT along Y
        for (ND_int ix = 0; ix < plan->fft_dims[0]; ++ix)
        {
            if (!(plan->gx_inGvecs[ix]))
            {
                continue;
            }
            ELPH_cmplx* wfcr_tmp_y =
                plan->fft_data + ix * Ny_stride;  //(Gx,Ny,Nz_log)
            ND_int iax = fftw_fun(alignment_of)((void*)wfcr_tmp_y);
            iax /= sizeof(ELPH_cmplx);
            fftw_fun(execute_dft)(plan->fplan_y[iax], wfcr_tmp_y, wfcr_tmp_y);
        }
        // b) (i) pack the data for transpose
        for (ND_int ixy = 0; ixy < plan->nGxy; ++ixy)
        {
            ND_int Gx = plan->Gxy_total[2 * ixy];
            ND_int Gy = plan->Gxy_total[2 * ixy + 1];
            // [Gx,Gy,0] =  Gx*Ny*Nzloc + Gy*Nzloc
            ELPH_cmplx* xy_buf = plan->fft_data + plan->nzloc * (Gy + Gx * Ny);
            // (Nxy,Zloc)
            memcpy(plan->nz_buf + ixy * plan->nzloc, xy_buf,
                   sizeof(ELPH_cmplx) * plan->nzloc);
        }
        // b) (ii)  transpose the data
        fwd_transpose(plan);  // nz_buf has (NGxy_loc,Nz)
        // c) perform fft along z
        fftw_fun(execute)(plan->fplan_z);
        // d) box to sphere
        ND_int igvec = 0;
        for (ND_int ixy = 0; ixy < plan->nGxyloc; ++ixy)
        {
            ELPH_cmplx* zfft_ptr = plan->nz_buf + ixy * Nz;
            for (ND_int ig = 0; ig < plan->ngxy_z[ixy]; ++ig)
            {
                ND_int Gz = plan->gvecs[3 * igvec + 2];
                if (Gz < 0)
                {
                    Gz += Nz;
                }
                wfcG_tmp[igvec] = zfft_ptr[Gz] * norm;
                if (conjugate)
                {
                    wfcG_tmp[igvec] = conj(wfcG_tmp[igvec]);
                }
                ++igvec;
            }
        }
        if (igvec != plan->ngvecs_loc)
        {
            error_msg("Gvec mismatch in fwd execute. ");
        }
    }
}
References ELPH_fft_plan::cplan_x, error_msg, ELPH_fft_plan::fft_data, ELPH_fft_plan::fft_dims, fftw_fun, ELPH_fft_plan::fplan_y, ELPH_fft_plan::fplan_z, fwd_transpose(), ELPH_fft_plan::gvecs, ELPH_fft_plan::gx_inGvecs, ELPH_fft_plan::Gxy_total, ELPH_fft_plan::ngvecs_loc, ELPH_fft_plan::nGxy, ELPH_fft_plan::ngxy_z, ELPH_fft_plan::nGxyloc, ELPH_fft_plan::nz_buf, and ELPH_fft_plan::nzloc.
Referenced by elphLocal().
fftw_fun()
typedef fftw_fun (plan)
fwd_transpose()
void fwd_transpose (struct ELPH_fft_plan * plan)
Definition at line 12 of file transpose.c.
{
    /* This performs a transpose from
    (nGxy,Nz_loc) -> (nGxy_loc,Nz)
    The input and output are stored in plan->nz_buf
    plan->fft_buf is used as scratch space
    */
    /*
    Perform Alltoallv plan->nz_buf -> plan->fft_buf
    */
    int mpi_error;
    int ncpus;
    mpi_error = MPI_Comm_size(plan->comm, &ncpus);
    MPI_error_msg(mpi_error);
    int* gxy_counts = plan->comm_bufs;
    int* xy_disp = gxy_counts + ncpus;
    int* z_counts = gxy_counts + 2 * ncpus;
    int* z_disp = gxy_counts + 3 * ncpus;
    mpi_error = MPI_Alltoallv(plan->nz_buf, gxy_counts, xy_disp, ELPH_MPI_cmplx,
                              plan->fft_data, z_counts, z_disp, ELPH_MPI_cmplx,
                              plan->comm);
    MPI_error_msg(mpi_error);
    /* Now plan->fft_data has the data.
    we need to redistribute and store to plan->nz_buf */
    for (ND_int ig = 0; ig < plan->nGxyloc; ++ig)
    {
        ELPH_cmplx* dest_ptr = plan->nz_buf + ig * plan->fft_dims[2];
        for (ND_int i = 0; i < ncpus; ++i)
        {
            ND_int zcount_tmp = z_counts[i] / plan->nGxyloc;
            ND_int z_disp_tmp = z_disp[i] / plan->nGxyloc;
            ELPH_cmplx* src_ptr = plan->fft_data + z_disp[i] + ig * zcount_tmp;
            memcpy(dest_ptr + z_disp_tmp, src_ptr,
                   sizeof(ELPH_cmplx) * zcount_tmp);
        }
    }
}
References ELPH_fft_plan::comm, ELPH_fft_plan::comm_bufs, ELPH_MPI_cmplx, ELPH_fft_plan::fft_data, ELPH_fft_plan::fft_dims, MPI_error_msg, ELPH_fft_plan::nGxyloc, and ELPH_fft_plan::nz_buf.
Referenced by fft3D(), and fft_convolution3D().
invfft3D()
void invfft3D (struct ELPH_fft_plan * plan, const ND_int nsets, ELPH_cmplx * wfcG, ELPH_cmplx * wfcr, const bool conjugate)
Definition at line 13 of file bwdfft.c.
{
    /*
    Note: if conjugate is true, then the input is conjugated and then FFT is
    performed! please note that the input wfcG is not alterned even when
    conjugate is set to true.
    a) sphere to box
    b) inv FFT along Z
    c) Gather Gx, Gy and scatter Nz
    d) inv fft along Gx and Gy
    */
    // first some basic stuff
    ND_int Nx = plan->fft_dims[0];
    ND_int Ny = plan->fft_dims[1];
    ND_int Nz = plan->fft_dims[2];
    ND_int fft_buf_size = Nx * Ny * plan->nzloc;
    ND_int Ny_stride = plan->nzloc * Ny;
    for (ND_int iset = 0; iset < nsets; ++iset)
    {
        ELPH_cmplx* wfcG_tmp = wfcG + iset * plan->ngvecs_loc;
        ELPH_cmplx* wfcr_tmp = wfcr + iset * fft_buf_size;
        ND_int igvec = 0;
        for (ND_int ixy = 0; ixy < plan->nGxyloc; ++ixy)
        {
            ELPH_cmplx* zfft_ptr = plan->nz_buf + ixy * Nz;
            // a) sphere to box
            for (ND_int iz = 0; iz < Nz; ++iz)
            {
                zfft_ptr[iz] = 0;
            }
            for (ND_int ig = 0; ig < plan->ngxy_z[ixy]; ++ig)
            {
                ND_int Gz = plan->gvecs[3 * igvec + 2];
                if (Gz < 0)
                {
                    Gz += Nz;
                }
                zfft_ptr[Gz] = wfcG_tmp[igvec];
                if (conjugate)
                {
                    zfft_ptr[Gz] = conj(zfft_ptr[Gz]);
                }
                ++igvec;
            }
        }
        if (igvec != plan->ngvecs_loc)
        {
            error_msg("Gvec mismatch in bwd execute.");
        }
        // b) perform invfft along z
        fftw_fun(execute)(plan->bplan_z);
        // c) (i) transpose the data
        bwd_transpose(plan);  // nz_buf has (NGxy,Nz_loc)
        // zero out the xy buffer and fill the fft_data buffer
        for (ND_int ixyz = 0; ixyz < fft_buf_size; ++ixyz)
        {
            wfcr_tmp[ixyz] = 0;
        }
        for (ND_int ixy = 0; ixy < plan->nGxy; ++ixy)
        {
            ND_int Gx = plan->Gxy_total[2 * ixy];
            ND_int Gy = plan->Gxy_total[2 * ixy + 1];
            // [Gx,Gy,0] =  Gx*Ny*Nzloc + Gy*Nzloc
            ELPH_cmplx* xy_buf = wfcr_tmp + plan->nzloc * (Gy + Gx * Ny);
            // (Nxy,Zloc)
            memcpy(xy_buf, plan->nz_buf + ixy * plan->nzloc,
                   sizeof(ELPH_cmplx) * plan->nzloc);
        }
        // c) (ii) FFT along Y
        for (ND_int ix = 0; ix < plan->fft_dims[0]; ++ix)
        {
            if (!(plan->gx_inGvecs[ix]))
            {
                continue;
            }
            ELPH_cmplx* wfcr_tmp_y =
                wfcr_tmp + ix * Ny_stride;  //(Gx,Ny,Nz_log)
            ND_int iax = fftw_fun(alignment_of)((void*)wfcr_tmp_y);
            iax /= sizeof(ELPH_cmplx);
            fftw_fun(execute_dft)(plan->bplan_y[iax], wfcr_tmp_y, wfcr_tmp_y);
        }
        ND_int ia = fftw_fun(alignment_of)((void*)wfcr_tmp);
        ia /= sizeof(ELPH_cmplx);
        // d) FFT along X
        fftw_fun(execute_dft)(plan->bplan_x[ia], wfcr_tmp, wfcr_tmp);
    }
}
References ELPH_fft_plan::bplan_x, ELPH_fft_plan::bplan_y, ELPH_fft_plan::bplan_z, bwd_transpose(), error_msg, ELPH_fft_plan::fft_dims, fftw_fun, ELPH_fft_plan::gvecs, ELPH_fft_plan::gx_inGvecs, ELPH_fft_plan::Gxy_total, ELPH_fft_plan::ngvecs_loc, ELPH_fft_plan::nGxy, ELPH_fft_plan::ngxy_z, ELPH_fft_plan::nGxyloc, ELPH_fft_plan::nz_buf, and ELPH_fft_plan::nzloc.
Referenced by dV_add_longrange(), dVlocq(), and elphLocal().
wfc_destroy_plan()
void wfc_destroy_plan (struct ELPH_fft_plan * plan)
Definition at line 315 of file planner.c.
{
    if (NULL == plan)
    {
        return;
    }
    // destroy x,y,z buffer
    fftw_fun(free)(plan->fft_data);
    fftw_fun(free)(plan->nz_buf);
    // destroy plans
    for (ND_int i = 0; i < plan->align_len; ++i)
    {
        fftw_fun(destroy_plan)(plan->fplan_x[i]);
        fftw_fun(destroy_plan)(plan->bplan_x[i]);
        fftw_fun(destroy_plan)(plan->fplan_y[i]);
        fftw_fun(destroy_plan)(plan->bplan_y[i]);
        fftw_fun(destroy_plan)(plan->cplan_x[i]);
    }
    fftw_fun(destroy_plan)(plan->fplan_z);
    fftw_fun(destroy_plan)(plan->bplan_z);
    // free remaining buffers
    free(plan->gx_inGvecs);
    free(plan->fplan_x);
    free(plan->comm_bufs);
    free(plan->Gxy_total);
    free(plan->ngxy_z);
}
References ELPH_fft_plan::align_len, ELPH_fft_plan::bplan_x, ELPH_fft_plan::bplan_y, ELPH_fft_plan::bplan_z, ELPH_fft_plan::comm_bufs, ELPH_fft_plan::cplan_x, ELPH_fft_plan::fft_data, fftw_fun, ELPH_fft_plan::fplan_x, ELPH_fft_plan::fplan_y, ELPH_fft_plan::fplan_z, ELPH_fft_plan::gx_inGvecs, ELPH_fft_plan::Gxy_total, ELPH_fft_plan::ngxy_z, and ELPH_fft_plan::nz_buf.
Referenced by dV_add_longrange(), dVlocq(), and elphLocal().
wfc_plan()
void wfc_plan (struct ELPH_fft_plan * plan, const ND_int ngvecs_loc, const ND_int nzloc, const ND_int nGxyloc, const int * gvecs, const ND_int * fft_dims, unsigned fft_flags, MPI_Comm comm)
Definition at line 16 of file planner.c.
{
    int ncpus, mpi_error;
    mpi_error = MPI_Comm_size(comm, &ncpus);
    MPI_error_msg(mpi_error);
    plan->comm_bufs = malloc(sizeof(int) * 4 * ncpus);
    CHECK_ALLOC(plan->comm_bufs);
    /*
    gxy_counts, xy_disp, z_counts, z_disp
    */
    plan->nzloc = get_mpi_local_size_idx(fft_dims[2], NULL, comm);
    if (plan->nzloc != nzloc)
    {
        error_msg("Wrong z local dimensions to planner.");
    }
    ND_int size_fft_data = fft_dims[0] * fft_dims[1] * plan->nzloc;
    if (size_fft_data < (fft_dims[2] * nGxyloc))
    {
        size_fft_data = fft_dims[2] * nGxyloc;
    }
    plan->align_len = alignment_len();
    size_fft_data += plan->align_len;  // we add alignment_len to make
                                       // alignment_len plans for x and y
    // alloc memory for fft_data and nz_buf;
    plan->fft_data = fftw_fun(malloc)(size_fft_data * sizeof(ELPH_cmplx));
    CHECK_ALLOC(plan->fft_data);
    plan->nz_buf = fftw_fun(malloc)(size_fft_data * sizeof(ELPH_cmplx));
    CHECK_ALLOC(plan->nz_buf);
    memset(plan->fft_data, 0,
           size_fft_data * sizeof(ELPH_cmplx));  // 0 the buffer
    memset(plan->nz_buf, 0,
           size_fft_data * sizeof(ELPH_cmplx));  // 0 the buffer
    plan->comm = comm;
    plan->gvecs = gvecs;
    plan->nGxyloc = nGxyloc;
    plan->ngvecs_loc = ngvecs_loc;
    // fft_dims Nx,Ny,Nz
    memcpy(plan->fft_dims, fft_dims, sizeof(ND_int) * 3);
    mpi_error = MPI_Allreduce(&nGxyloc, &(plan->nGxy), 1, ELPH_MPI_ND_INT,
                              MPI_SUM, comm);
    MPI_error_msg(mpi_error);
    if (nGxyloc != get_mpi_local_size_idx(plan->nGxy, NULL, comm))
    {
        error_msg("Wrong xy local dimensions to planner.");
    }
    int* Gxy_loc = malloc(sizeof(int) * 2 * nGxyloc);  // local gxy (nGxyloc,2)
    CHECK_ALLOC(Gxy_loc);
    plan->Gxy_total = malloc(sizeof(int) * 2 * plan->nGxy);
    CHECK_ALLOC(plan->Gxy_total);
    plan->gx_inGvecs = malloc(sizeof(bool) * fft_dims[0]);
    CHECK_ALLOC(plan->gx_inGvecs);
    // initiate to false
    for (ND_int igx = 0; igx < fft_dims[0]; ++igx)
    {
        plan->gx_inGvecs[igx] = false;
    }
    int* gxy_counts = plan->comm_bufs;
    int* xy_disp = gxy_counts + ncpus;
    int* z_counts = gxy_counts + 2 * ncpus;
    int* z_disp = gxy_counts + 3 * ncpus;
    int xycount = 0;
    // initialize with gvecs which are out of the box
    int Gx_prev = fft_dims[0] + 10;
    int Gy_prev = fft_dims[1] + 10;
    plan->ngxy_z = malloc(sizeof(int) * nGxyloc);
    CHECK_ALLOC(plan->ngxy_z);
    // zero the buffer
    for (ND_int i = 0; i < nGxyloc; ++i)
    {
        plan->ngxy_z[i] = 0;
    }
    for (ND_int ig = 0; ig < plan->ngvecs_loc; ++ig)
    {
        if (gvecs[3 * ig + 1] != Gy_prev || gvecs[3 * ig] != Gx_prev)
        {
            Gx_prev = gvecs[3 * ig];
            Gy_prev = gvecs[3 * ig + 1];
            Gxy_loc[2 * xycount] = Gx_prev;
            Gxy_loc[2 * xycount + 1] = Gy_prev;
            if (Gx_prev < 0)
            {
                Gxy_loc[2 * xycount] += fft_dims[0];
            }
            if (Gy_prev < 0)
            {
                Gxy_loc[2 * xycount + 1] += fft_dims[1];
            }
            // sanity checks
            if (Gxy_loc[2 * xycount] >= fft_dims[0] ||
                Gxy_loc[2 * xycount + 1] >= fft_dims[1])
            {
                error_msg("gvec > Nfft dim");
            }
            if (Gxy_loc[2 * xycount] < 0 || Gxy_loc[2 * xycount + 1] < 0)
            {
                error_msg("Bad gvectors");
            }
            plan->gx_inGvecs[Gxy_loc[2 * xycount]] = true;
            ++xycount;
        }
        plan->ngxy_z[xycount - 1] += 1;
    }
    if (xycount != nGxyloc)
    {
        error_msg("Wrong number of xy components in each cpu");
    }
    // get global plan->gx_inGvecs
    mpi_error = MPI_Allreduce(MPI_IN_PLACE, plan->gx_inGvecs, fft_dims[0],
                              MPI_C_BOOL, MPI_LOR, comm);
    MPI_error_msg(mpi_error);
    mpi_error =
        MPI_Allgather(&xycount, 1, MPI_INT, gxy_counts, 1, MPI_INT, comm);
    MPI_error_msg(mpi_error);
    int nzloc_temp = nzloc;
    mpi_error =
        MPI_Allgather(&nzloc_temp, 1, MPI_INT, z_counts, 1, MPI_INT, comm);
    MPI_error_msg(mpi_error);
    int dispdisp_temp = 0;
    for (int i = 0; i < ncpus; ++i)
    {
        gxy_counts[i] *= 2;
        xy_disp[i] = dispdisp_temp;
        dispdisp_temp += gxy_counts[i];
    }
    mpi_error = MPI_Allgatherv(Gxy_loc, 2 * xycount, MPI_INT, plan->Gxy_total,
                               gxy_counts, xy_disp, MPI_INT, comm);
    MPI_error_msg(mpi_error);
    free(Gxy_loc);
    /* fill the comm buffer */
    dispdisp_temp = 0;
    for (int i = 0; i < ncpus; ++i)
    {
        gxy_counts[i] = nzloc * (gxy_counts[i] / 2);
        xy_disp[i] = nzloc * (xy_disp[i] / 2);
        z_counts[i] *= xycount;
        z_disp[i] = dispdisp_temp;
        dispdisp_temp += z_counts[i];
    }
    /* Now time to create plans */
    // i) create plan along entire X direction
    // ii) create two plans along y for -Gx_min < Gx < Gx_max
    // iii) create plan for along z only for set of (Gx,Gy) pairs
    // create plan buffers
    // fftw_fun(plan) expands to fftwf_plan or fftw_plan
    plan->fplan_x = malloc(sizeof(fftw_generic_plan) * 5 *
                           plan->align_len);  // (naligment plans) for x
    CHECK_ALLOC(plan->fplan_x);
    plan->fplan_y = plan->fplan_x + plan->align_len;  // (naligment plans) for y
    /* backward plans G->r */
    plan->bplan_x =
        plan->fplan_x + 2 * plan->align_len;  // (naligment plans) for x
    plan->bplan_y =
        plan->fplan_x + 3 * plan->align_len;  // (naligment plans) for y
    /* convolution plan x */
    plan->cplan_x =
        plan->fplan_x + 4 * plan->align_len;  // (naligment plans) for x
    // i) create forward plan and bwd plan along X
    for (ND_int i = 0; i < plan->align_len; ++i)
    {
        ELPH_cmplx* tmp_fft_plan_ptr = plan->fft_data + i;
        ND_int ia = fftw_fun(alignment_of)((void*)tmp_fft_plan_ptr);
        ia /= sizeof(ELPH_cmplx);
        int nff_dimx = fft_dims[0];
        // (Nx, k, Nz_loc)
        plan->fplan_x[ia] = fftw_fun(plan_many_dft)(
            1, &nff_dimx, fft_dims[1] * nzloc, tmp_fft_plan_ptr, NULL,
            fft_dims[1] * nzloc, 1, tmp_fft_plan_ptr, NULL, fft_dims[1] * nzloc,
            1, FFTW_FORWARD, fft_flags);
        if (plan->fplan_x[ia] == NULL)
        {
            error_msg("X forward plan failed");
        }
        // backward plan G->r
        plan->bplan_x[ia] = fftw_fun(plan_many_dft)(
            1, &nff_dimx, fft_dims[1] * nzloc, tmp_fft_plan_ptr, NULL,
            fft_dims[1] * nzloc, 1, tmp_fft_plan_ptr, NULL, fft_dims[1] * nzloc,
            1, FFTW_BACKWARD, fft_flags);
        if (plan->bplan_x[ia] == NULL)
        {
            error_msg("X backward plan failed");
        }
    }
    // ii) create Y ffts plans
    for (ND_int i = 0; i < plan->align_len; ++i)
    {
        ELPH_cmplx* tmp_fft_plan_ptr = plan->fft_data + i;
        ND_int ia = fftw_fun(alignment_of)((void*)tmp_fft_plan_ptr);
        ia /= sizeof(ELPH_cmplx);
        //
        int nff_dimy = fft_dims[1];
        // (k, Nz_loc)
        plan->fplan_y[ia] = fftw_fun(plan_many_dft)(
            1, &nff_dimy, nzloc, tmp_fft_plan_ptr, NULL, nzloc, 1,
            tmp_fft_plan_ptr, NULL, nzloc, 1, FFTW_FORWARD, fft_flags);
        if (plan->fplan_y[ia] == NULL)
        {
            error_msg("Y forward plan failed");
        }
        // backward plan G->r
        plan->bplan_y[ia] = fftw_fun(plan_many_dft)(
            1, &nff_dimy, nzloc, tmp_fft_plan_ptr, NULL, nzloc, 1,
            tmp_fft_plan_ptr, NULL, nzloc, 1, FFTW_BACKWARD, fft_flags);
        if (plan->bplan_y[ia] == NULL)
        {
            error_msg("Y backward plan failed");
        }
    }
    // iii) create a single z plan.
    // forward plan->
    plan->fplan_z = fftw_fun(plan_many_dft)(
        1, (int[1]){fft_dims[2]}, nGxyloc, plan->nz_buf, NULL, 1, fft_dims[2],
        plan->nz_buf, NULL, 1, fft_dims[2], FFTW_FORWARD, fft_flags);
    if (plan->fplan_z == NULL)
    {
        error_msg("Z forward plan failed");
    }
    // backward plan
    plan->bplan_z = fftw_fun(plan_many_dft)(
        1, (int[1]){fft_dims[2]}, nGxyloc, plan->nz_buf, NULL, 1, fft_dims[2],
        plan->nz_buf, NULL, 1, fft_dims[2], FFTW_BACKWARD, fft_flags);
    if (plan->bplan_z == NULL)
    {
        error_msg("Z backward plan failed");
    }
    /*
    Finally create convolution plan for FFT along x
    In convolutions we use these plans instead of fplan_x
    */
    for (ND_int i = 0; i < plan->align_len; ++i)
    {
        ELPH_cmplx* tmp_pln_ptr = plan->fft_data + i;
        ND_int ia = fftw_fun(alignment_of)((void*)tmp_pln_ptr);
        ia /= sizeof(ELPH_cmplx);
        // (Nx, k, Nz_loc)
        plan->cplan_x[ia] = fftw_fun(plan_many_dft)(
            1, (int[1]){fft_dims[0]}, nzloc, tmp_pln_ptr, NULL,
            fft_dims[1] * nzloc, 1, tmp_pln_ptr, NULL, fft_dims[1] * nzloc, 1,
            FFTW_FORWARD, fft_flags);
        if (plan->cplan_x[ia] == NULL)
        {
            error_msg("convolution forward X plan failed");
        }
    }
}
References ELPH_fft_plan::align_len, alignment_len(), ELPH_fft_plan::bplan_x, ELPH_fft_plan::bplan_y, ELPH_fft_plan::bplan_z, CHECK_ALLOC, ELPH_fft_plan::comm, ELPH_fft_plan::comm_bufs, ELPH_fft_plan::cplan_x, ELPH_MPI_ND_INT, error_msg, ELPH_fft_plan::fft_data, ELPH_fft_plan::fft_dims, fftw_fun, ELPH_fft_plan::fplan_x, ELPH_fft_plan::fplan_y, ELPH_fft_plan::fplan_z, get_mpi_local_size_idx(), ELPH_fft_plan::gvecs, ELPH_fft_plan::gx_inGvecs, ELPH_fft_plan::Gxy_total, MPI_error_msg, ELPH_fft_plan::ngvecs_loc, ELPH_fft_plan::nGxy, ELPH_fft_plan::ngxy_z, ELPH_fft_plan::nGxyloc, ELPH_fft_plan::nz_buf, and ELPH_fft_plan::nzloc.
Referenced by dV_add_longrange(), dVlocq(), and elphLocal().