LetzElPhC: src/common/string_func.c File Reference
string_func.c File Reference
#include "string_func.h"
#include <ctype.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include "error.h"
Functions
char * strncpy_custom (char *dest, const char *src, size_t count)
void lowercase_str (char *str)
ND_int parser_doubles_from_string (const char *str, ELPH_float *out)
bool string_start_with (char *str, char *compare_str, bool trim)
bool string_end_with (char *str, char *compare_str, bool trim)
char * str_reverse_in_place (char *str)
void str_replace_chars (char *str_in, const char *delimters, const char *replace_chars)
Function Documentation
lowercase_str()
void lowercase_str (char * str)
Definition at line 28 of file string_func.c.
{
    // lower case all the chars in a string
    for (char* p = str; *p; ++p)
    {
        *p = tolower((unsigned char)(*p));
    }
}
Referenced by create_ph_save_dir_pp_qe(), and handler().
parser_doubles_from_string()
ND_int parser_doubles_from_string (const char * str, ELPH_float * out)
Definition at line 37 of file string_func.c.
{
    /*
    Extract all float values from given string
    if out == NULL, it return number of float it parsed
    */
    const char* p = str;
    char* q;
    double temp_val;
    ND_int count = 0;
    while (*p)
    {
        if (isdigit((unsigned char)(*p)) ||
            ((*p == '-' || *p == '+') && isdigit((unsigned char)(*(p + 1)))))
        {
            temp_val = strtod(p, &q);
            if (p == q)
            {
                break;
            }
            else
            {
                p = q;
            }
            if (out != NULL)
            {
                out[count] = temp_val;
            }
            ++count;
        }
        else
        {
            ++p;
        }
    }
    return count;
}
Referenced by parse_upf1(), and parse_upf2().
str_replace_chars()
void str_replace_chars (char * str_in, const char * delimters, const char * replace_chars)
Definition at line 169 of file string_func.c.
{
    ND_int ndelimters = strlen(delimters);
    // if  ndelimters != strlen(replace_chars) buffer overflow
    ND_int str_in_len = strlen(str_in);
    for (ND_int i = 0; i < str_in_len; ++i)
    {
        for (ND_int j = 0; j < ndelimters; ++j)
        {
            if (str_in[i] == delimters[j])
            {
                str_in[i] = replace_chars[j];
                break;
            }
        }
    }
}
Referenced by create_ph_save_dir_pp_qe().
str_reverse_in_place()
char * str_reverse_in_place (char * str)
Definition at line 144 of file string_func.c.
{
    /*
    Do a inplace reversing of string
    */
    ND_int len = strlen(str);
    if (len == 0)
    {
        return str;
    }
    char* p1 = str;
    char* p2 = str + len - 1;
    while (p1 < p2)
    {
        char tmp = *p1;
        *p1++ = *p2;
        *p2-- = tmp;
    }
    return str;
}
Referenced by string_end_with().
string_end_with()
bool string_end_with (char * str, char * compare_str, bool trim)
Definition at line 106 of file string_func.c.
{
    /*
    Check if given string ends with a substring
    */
    char* temp_str =
        malloc(sizeof(char) * (strlen(str) + strlen(compare_str) + 2));
    CHECK_ALLOC(temp_str);
    char* a = temp_str;
    char* b = temp_str + strlen(str) + 1;
    strcpy(a, str);
    strcpy(b, compare_str);
    str_reverse_in_place(a);
    str_reverse_in_place(b);
    if (trim)
    {
        while (isspace((unsigned char)(*a)))
        {
            ++a;
        }
        while (isspace((unsigned char)(*b)))
        {
            ++b;
        }
    }
    bool ret_value = !strncmp(a, b, strlen(b));
    if (b[0] != a[0])
    {
        ret_value = false;
    }
    free(temp_str);
    return ret_value;
}
References CHECK_ALLOC, and str_reverse_in_place().
string_start_with()
bool string_start_with (char * str, char * compare_str, bool trim)
Definition at line 79 of file string_func.c.
{
    /*
    Check if given string starts with a substring
    */
    char* a;
    char* b;
    a = str;
    b = compare_str;
    if (trim)
    {
        while (isspace((unsigned char)(*a)))
        {
            ++a;
        }
        while (isspace((unsigned char)(*b)))
        {
            ++b;
        }
    }
    if (b[0] != a[0])
    {
        return false;
    }
    return !strncmp(a, b, strlen(b));
}
strncpy_custom()
char * strncpy_custom (char * dest, const char * src, size_t count)
Definition at line 13 of file string_func.c.
{
    // this does strncpy(dest,src,n-1) and sets nth element as \0
    if (1 == count)
    {
        dest[0] = '\0';
    }
    else if (count > 1)
    {
        strncpy(dest, src, count - 1);
        dest[count - 1] = '\0';
    }
    return dest;
}
Referenced by create_ph_save_dir_pp_qe(), ELPH_cli_parser(), handler(), init_usr_input(), and set_kernel().