LetzElPhC: src/elph/set_kernel.c File Reference
set_kernel.c File Reference
#include <stdbool.h>
#include <stddef.h>
#include <string.h>
#include "common/dtypes.h"
#include "common/error.h"
#include "common/string_func.h"
#include "elph.h"
Functions
void init_kernel (struct kernel_info *kernel)
void set_kernel (const char *kernel_str, struct kernel_info *kernel)
Function Documentation
init_kernel()
void init_kernel (struct kernel_info * kernel)
Definition at line 10 of file set_kernel.c.
{
    strcpy(kernel->name_str, "dfpt");
    kernel->bare_loc = true;
    kernel->non_loc = true;
    kernel->screening = ELPH_DFPT_SCREENING;
}
References kernel_info::bare_loc, ELPH_DFPT_SCREENING, kernel_info::name_str, kernel_info::non_loc, and kernel_info::screening.
Referenced by elph_driver().
set_kernel()
void set_kernel (const char * kernel_str, struct kernel_info * kernel)
Definition at line 18 of file set_kernel.c.
{
    size_t name_str_size = sizeof(kernel->name_str) - 1;
    kernel->name_str[name_str_size] = '\0';
    strncpy_custom(kernel->name_str, kernel_str, name_str_size);
    if (!strcmp(kernel_str, "dfpt"))
    {
        kernel->bare_loc = true;
        kernel->non_loc = true;
        kernel->screening = ELPH_DFPT_SCREENING;
    }
    else if (!strcmp(kernel_str, "dfpt_local"))
    {
        kernel->bare_loc = true;
        kernel->non_loc = false;
        kernel->screening = ELPH_DFPT_SCREENING;
    }
    else if (!strcmp(kernel_str, "bare"))
    {
        kernel->bare_loc = true;
        kernel->non_loc = true;
        kernel->screening = ELPH_NO_SCREENING;
    }
    else if (!strcmp(kernel_str, "bare_local"))
    {
        kernel->bare_loc = true;
        kernel->non_loc = false;
        kernel->screening = ELPH_NO_SCREENING;
    }
    else
    {
        error_msg("invalid value for kernel in the input file");
    }
}
References kernel_info::bare_loc, ELPH_DFPT_SCREENING, ELPH_NO_SCREENING, error_msg, kernel_info::name_str, kernel_info::non_loc, kernel_info::screening, and strncpy_custom().
Referenced by elph_driver().