LetzElPhC: src/dvloc/dvloc.h File Reference
dvloc.h File Reference
#include <stdbool.h>
#include "common/dtypes.h"
#include "elphC.h"
Functions
ELPH_float Vloc_Gspace (ELPH_float *work_arr, const char cutoff, const ELPH_float Gnorm, const ND_int ngrid, const ELPH_float *Vloc_atomic, const ELPH_float *r_grid, const ELPH_float *rab_grid, const ELPH_float Zval, const ELPH_float eta, const ELPH_float volume)
void add_dvscf_qe (ELPH_cmplx *dVscf, const ELPH_cmplx *dVloc, const struct Lattice *lattice)
void elphLocal (const ELPH_float *qpt, struct WFC *wfcs, struct Lattice *lattice, int ikq, int ik, int kqsym, int ksym, ELPH_cmplx *dVlocr, const struct ELPH_MPI_Comms *Comm, ELPH_cmplx *elph_kq)
void dVlocq (const ELPH_float *qpt, struct Lattice *lattice, struct Pseudo *pseudo, const ELPH_cmplx *eigVec, ELPH_cmplx *Vlocr, MPI_Comm commK)
void dVlong_range_kernel (const ELPH_float *qpt, const ELPH_float *gvecs, const ND_int npw_loc, const ELPH_float *Zvals, const ELPH_float *epslion, const ELPH_float *Zeu, const ELPH_float *Qpole, const ND_int natom, const ELPH_float *atom_pos, const char diminsion, const ELPH_float volume, const ELPH_float zlat, const ELPH_float EcutRy, ELPH_cmplx *elph_lr_out)
void dV_add_longrange (const ELPH_float *qpt, struct Lattice *lattice, struct Phonon *phonon, const ELPH_float *Zvals, const ELPH_cmplx *eigVec, ELPH_cmplx *dVscf, const ND_int sign, const bool only_induced_part, const ELPH_float EcutRy, const bool *nmags_add, MPI_Comm commK)
void dVscf_change_basis (ELPH_cmplx *dvscf, const ELPH_cmplx *rot_vecs, const ND_int nsets, const ND_int nmodes, const ND_int nmag, const ND_int Nx, const ND_int Ny, const ND_int Nz, const char blas_char)
void multiply_eikr (ELPH_cmplx *pot_grid, const ELPH_float *qpt_crys, const struct Lattice *lattice, const ND_int nsets, const ND_int sign)
void create_vlocg_table (const struct Lattice *lattice, struct Pseudo *pseudo, const struct ELPH_MPI_Comms *Comm)
void free_vlocg_table (struct Vloc_table *vloc_table)
Function Documentation
add_dvscf_qe()
void add_dvscf_qe (ELPH_cmplx * dVscf, const ELPH_cmplx * dVloc, const struct Lattice * lattice)
Definition at line 12 of file add_dvscf.c.
{
    /*
    nffts = Nx*Ny*Nz_loc
    This function adds dVloc is added to dVscf.
    dVscf_{2x2} = d{V}*I + d{Bx}*sigma_x + d{By}*sigma_y + dBz}*sigma_z
                    =   | d{V} + d{Bz}         d{Bx} - I*d{By} |
                        | d{Bx}+ I*d{By}       d{V} - d{Bz}    |
    where Bx,By,Bz = d{Exc}/dm and V = V_Ha + d{Exc}/dn i.e V = V_Ha + V_Xc
    In QE. dvscf is stored as follows :
    nmag = 1 : dV is stored (non magnetic calc with both collinear and non
    collinear) nmag = 2 : d{V} + d{Bz}  and d{V} - d{Bz} are stored (nspin = 2)
    nmag = 4 : d{V}, d{Bx},d{By},d{Bz} are stored (magnetic, non collinear)
    dVscf -> (nmodes, nmag, nffts)
    dVloc -> (nmodes, nffts)
    */
    const ND_int nmag = lattice->nmag;
    const ND_int nmodes = lattice->nmodes;
    const ND_int nffts =
        lattice->fft_dims[0] * lattice->fft_dims[1] * lattice->nfftz_loc;
    ND_int mag_iter = 1;
    if (nmag == 2)
    {
        mag_iter = 2;
    }
    for (ND_int iv = 0; iv < nmodes; ++iv)
    {
        ELPH_cmplx* dVscf_mode = dVscf + iv * nffts * nmag;
        const ELPH_cmplx* dVbare = dVloc + iv * nffts;
        /* add local bare part of pseudo potential (i,e dVloc) to V_Ha + V_xc */
        for (ND_int im = 0; im < mag_iter; ++im)
        {
            ELPH_cmplx* temp_ptr = dVscf_mode + im * nffts;
            ELPH_OMP_PAR_FOR_SIMD
            for (ND_int i = 0; i < nffts; ++i)
            {
                temp_ptr[i] += dVbare[i];
            }
        }
        if (nmag == 4)
        {
            /* dvscf_{2x2} = vloc*I + Bx*sigma_x + By*sigma_y + Bz*sigma_z
            | V + Bz         Bx - I*By |
            | Bx+ I*By       V - Bz    |
            where Bx,By,Bz = d{Exc}/dm and Vxc = d{Exc}/dn
            */
            /*
            This is an inplace operation to avoid creating a large buffer
            */
            ELPH_cmplx* Vxc_loc = dVscf_mode + 0 * nffts;
            ELPH_cmplx* Bx_loc = dVscf_mode + 1 * nffts;
            ELPH_cmplx* By_loc = dVscf_mode + 2 * nffts;
            ELPH_cmplx* Bz_loc = dVscf_mode + 3 * nffts;
            ELPH_OMP_PAR_FOR_SIMD
            for (ND_int i = 0; i < nffts; ++i)
            {
                ELPH_cmplx Vxc_t, Bx_t, By_t, Bz_t;
                Vxc_t = Vxc_loc[i];
                Bx_t = Bx_loc[i];
                By_t = By_loc[i];
                Bz_t = Bz_loc[i];
                Vxc_loc[i] = Vxc_t + Bz_t;
                Bx_loc[i] = Bx_t - I * By_t;
                By_loc[i] = Bx_t + I * By_t;
                Bz_loc[i] = Vxc_t - Bz_t;
            }
        }
    }
}
References ELPH_OMP_PAR_FOR_SIMD, Lattice::fft_dims, Lattice::nfftz_loc, Lattice::nmag, and Lattice::nmodes.
Referenced by elph_driver().
create_vlocg_table()
void create_vlocg_table (const struct Lattice * lattice, struct Pseudo * pseudo, const struct ELPH_MPI_Comms * Comm)
Definition at line 16 of file vlocg_table.c.
{
    ELPH_start_clock("Vloc table");
    int mpi_error;
    // pseudo->vloc_table->qmax_abs
    const struct local_pseudo* loc_pseudo = pseudo->loc_pseudo;
    const ND_int ntype = pseudo->ntype;
    const ND_int ngrid_max = pseudo->ngrid_max;
    const ELPH_float volume = lattice->volume;
    ELPH_float gmax, gmin;
    ND_int npts;
    // create a small scope
    {
        const ELPH_float* blat = lattice->blat_vec;  // 2*pi is included
        ELPH_float bi[3], bmin, bmax, Nmax;
        bi[0] = sqrt((blat[0] * blat[0]) + (blat[3] * blat[3]) +
                     (blat[6] * blat[6]));
        bi[1] = sqrt((blat[1] * blat[1]) + (blat[4] * blat[4]) +
                     (blat[7] * blat[7]));
        bi[2] = sqrt((blat[2] * blat[2]) + (blat[5] * blat[5]) +
                     (blat[8] * blat[8]));
        bmin = bi[0];
        bmax = bi[0];
        Nmax = lattice->fft_dims[0];
        for (int i = 0; i < 3; ++i)
        {
            if (bi[i] < bmin)
            {
                bmin = bi[i];
            }
            if (bi[i] > bmax)
            {
                bmax = bi[i];
            }
            if (lattice->fft_dims[i] > Nmax)
            {
                Nmax = lattice->fft_dims[i];
            }
        }
        /*
        We try to do this only once for any q, so we should get the max possible
        value of |G+q| |G+q| <= |G| + |q|. If all three values of q (in crystal
        coordinates) are restricted to [qmin,qmax] then |q| <= 3*b_max*|qmax|
        G_max = |N1/2*b1 + N2/2*b2 + N3/2*b3| < N_max/2 * 3 * b_max
        |G|<= 1.5*N_max*b_max
        => |G+q| <= b_max*(1.5*N_max+3*|qmax|)
        So we choose Interpolation range to be [0,(1.5*N_max+3*|qmax|)*b_max]
        // coarse spacing = b_min, npts ~ (1.5*N_max + 3*|qmax|)*b_max/b_min.
        */
        if (bmin > 0.01)
        {
            bmin = 0.01;  // set some bare minimum
        }
        gmax = (1.7 * (Nmax + 4.0) + 3 * fabs(pseudo->vloc_table->qmax_abs)) *
               bmax;
        // we choose 1.7 instead of 1.5
        npts = ceil(gmax / bmin);
        gmin = 0.0;
    }  // end of scope
    ELPH_float* xins = malloc(sizeof(ELPH_float) * npts);
    CHECK_ALLOC(xins);
    ELPH_float* yins = malloc(sizeof(ELPH_float) * npts * ntype);
    CHECK_ALLOC(yins);
    pseudo->vloc_table->vploc_co = malloc(sizeof(ELPH_float) * npts * ntype);
    CHECK_ALLOC(pseudo->vloc_table->vploc_co);
    pseudo->vloc_table->npts_co = npts;
    pseudo->vloc_table->g_co = xins;
    pseudo->vloc_table->vlocg = yins;
    ELPH_float diff = (gmax - gmin) / (npts - 1.0);
    for (ND_int i = 0; i < npts; ++i)
    {
        xins[i] = gmin + i * diff;
    }
    pseudo->vloc_table->dg = diff;
    ND_int n_shift;
    int npts_loc = get_mpi_local_size_idx(npts, &n_shift, Comm->commW);
    ELPH_float* work_array =
        malloc(sizeof(ELPH_float) * (ngrid_max + npts_loc + 1));
    CHECK_ALLOC(work_array);
    ELPH_float* vlocg_cpu = work_array + ngrid_max;
    int* counts_recv = malloc(sizeof(int) * 2 * Comm->commW_size);
    CHECK_ALLOC(counts_recv);
    int* displacements = counts_recv + Comm->commW_size;
    mpi_error = MPI_Allgather(&npts_loc, 1, MPI_INT, counts_recv, 1, MPI_INT,
                              Comm->commW);
    MPI_error_msg(mpi_error);
    int n_shift_temp = n_shift;
    mpi_error = MPI_Allgather(&n_shift_temp, 1, MPI_INT, displacements, 1,
                              MPI_INT, Comm->commW);
    MPI_error_msg(mpi_error);
    for (ND_int itype = 0; itype < ntype; ++itype)
    {
        ELPH_float* vlocg_atom = yins + itype * npts;
        ELPH_float* dyy = pseudo->vloc_table->vploc_co + itype * npts;
        const struct local_pseudo* loc_pseudo_type = loc_pseudo + itype;
        // loop not thread safe
        for (ND_int i = 0; i < npts_loc; ++i)
        {
            vlocg_cpu[i] = Vloc_Gspace(
                work_array, lattice->dimension, xins[i + n_shift],
                loc_pseudo_type->ngrid, loc_pseudo_type->Vloc_atomic,
                loc_pseudo_type->r_grid, loc_pseudo_type->rab_grid,
                loc_pseudo_type->Zval, 1.0, volume);
        }
        mpi_error = MPI_Allgatherv(vlocg_cpu, npts_loc, ELPH_MPI_float,
                                   vlocg_atom, counts_recv, displacements,
                                   ELPH_MPI_float, Comm->commW);
        MPI_error_msg(mpi_error);
        prepare_spline(npts, xins, vlocg_atom, dyy);
    }
    free(counts_recv);
    free(work_array);
    ELPH_stop_clock("Vloc table");
}
References Lattice::blat_vec, CHECK_ALLOC, ELPH_MPI_Comms::commW, ELPH_MPI_Comms::commW_size, Vloc_table::dg, Lattice::dimension, ELPH_MPI_float, ELPH_start_clock(), ELPH_stop_clock(), Lattice::fft_dims, Vloc_table::g_co, get_mpi_local_size_idx(), Pseudo::loc_pseudo, MPI_error_msg, local_pseudo::ngrid, Pseudo::ngrid_max, Vloc_table::npts_co, Pseudo::ntype, prepare_spline(), Vloc_table::qmax_abs, local_pseudo::r_grid, local_pseudo::rab_grid, local_pseudo::Vloc_atomic, Vloc_Gspace(), Pseudo::vloc_table, Vloc_table::vlocg, Lattice::volume, Vloc_table::vploc_co, and local_pseudo::Zval.
Referenced by read_and_alloc_save_data().
dV_add_longrange()
void dV_add_longrange (const ELPH_float * qpt, struct Lattice * lattice, struct Phonon * phonon, const ELPH_float * Zvals, const ELPH_cmplx * eigVec, ELPH_cmplx * dVscf, const ND_int sign, const bool only_induced_part, const ELPH_float EcutRy, const bool * nmags_add, MPI_Comm commK)
Add or subtracts the long range part of the deformation potential in real space
Input qpt : q-point in crystal coordinates if sign < 0: long range part is subtracted to the dvscf else : long range part is added to the advscf dVscf : (nmodes, nmag, nfft_loc) Assumes dVscf is already initialized, else UB. only_induced_part : If only_induced_part is true, then only dipoles and quadrupoles are considered else Valance charge(Z_val/r), dipoles and quadrupoles are consider. nmags_add : is list of bools for which the potential is add or subtraced if nmags_add[imag] == true, the potential is added/sub to dvscf[:,imag,:]
Parameters
[in] qpt q-point in crystal coordinates (range: [-1, 1]).
[in] lattice Pointer to Lattice structure containing:
alat_vec/blat_vec (lattice/reciprocal vectors),
atomic_pos (Cartesian positions),
fft_dims (FFT grid dimensions),
dimension (cutoff type: '3', '2', or '1' for 3D/2D/1D). species).
[in] eigVec Phonon eigenvectors (shape: [nmodes, 3*natom]), used to project onto modes.
[out] Vlocr Output array (shape: [nmodes, nffts_loc]) storing the real-space dVloc/dtau for each mode.
[in] commK MPI communicator for parallel FFT grid distribution.
Attention
The q-point must be in fractional coordinates (range [-1, 1]).
Memory for Vlocr must be pre-allocated by the caller.
Uses spline interpolation for Vloc(G) and includes a long-range Coulomb correction.
For 2D systems (‘cutoff == '2’`), an analytic cutoff is applied to remove z-periodicity.
Warning
Terminates with error_msg if:
No G-vectors are assigned to a process (G_vecs_xy < 1).
|q+G| exceeds the interpolation table bounds.
Definition at line 18 of file dVpot_add_long_range.c.
{
    if (lattice->dimension == '2' && fabs(qpt[2]) > ELPH_EPS)
    {
        error_msg(
            "In 2D, only qz == 0 points are accepted when interpolating.");
    }
    ELPH_start_clock("dV_longrange");
    //
    const ELPH_float* latvec = lattice->alat_vec;
    const ELPH_float* atom_pos = lattice->atomic_pos;
    const char cutoff = lattice->dimension;
    const ND_int natom = lattice->natom;
    const ND_int nmodes = lattice->nmodes;
    const ELPH_float volume = lattice->volume;
    const ELPH_float* blat = lattice->blat_vec;
    const ND_int nffts_loc =
        lattice->fft_dims[0] * lattice->fft_dims[1] * lattice->nfftz_loc;
    // compute the small fft box for the Cutoff for which we compute
    // dV_longrage(G)
    //
    ND_int Gbox[3];
    get_fft_box(EcutRy, blat, Gbox, commK);
    // make sure we donot exceed fft_dims
    for (int i = 0; i < 3; ++i)
    {
        Gbox[i] = MIN(Gbox[i], lattice->fft_dims[i]);
    }
    ND_int G_vecs_xy, Gxy_shift;
    G_vecs_xy = get_mpi_local_size_idx(Gbox[0] * Gbox[1], &Gxy_shift, commK);
    if (G_vecs_xy < 1)
    {
        error_msg(
            "Some process do not contain G vectors. reduce PW "
            "parallelization.");
    }
    const ND_int size_G_vecs = G_vecs_xy * Gbox[2];
    const ND_int size_VG = nmodes * size_G_vecs;
    // this must be calloc
    ELPH_cmplx* VlocG = calloc(size_VG, sizeof(ELPH_cmplx));
    CHECK_ALLOC(VlocG);
    int* gvecs = malloc(3 * size_G_vecs * sizeof(*gvecs));
    CHECK_ALLOC(gvecs);
    ELPH_float* Gvecs_z = malloc(3 * Gbox[2] * sizeof(*Gvecs_z));
    CHECK_ALLOC(gvecs);
    ELPH_cmplx* VlocGz_cart = calloc(Gbox[2] * nmodes, sizeof(ELPH_cmplx));
    CHECK_ALLOC(VlocGz_cart);
    ELPH_float qcart[3];
    MatVec3f(blat, qpt, false, qcart);
    for (int ii = 0; ii < 3; ++ii)
    {
        qcart[ii] /= (2.0 * ELPH_PI);
    }
    //
    const ELPH_float* Zvals_tmp = Zvals;
    if (only_induced_part)
    {
        Zvals_tmp = NULL;
    }
    const ELPH_float* epslion = phonon->epsilon;
    const ELPH_float* Zeu = phonon->Zborn;
    const ELPH_float* Qpole = phonon->Qpole;
    // Note. No openmp par for, not thread safe for this outer most loop.
    for (ND_int ig = 0; ig < G_vecs_xy; ++ig)
    {
        const ND_int G_glob_idx = Gxy_shift + ig;
        ND_int ix = G_glob_idx / Gbox[1];
        ND_int jy = G_glob_idx % Gbox[1];
        ix = get_miller_idx(ix, Gbox[0]);
        jy = get_miller_idx(jy, Gbox[1]);
        for (ND_int kz = 0; kz < Gbox[2]; ++kz)
        {
            ND_int Gkz = get_miller_idx(kz, Gbox[2]);
            int* g_temp_set = gvecs + Gbox[2] * 3 * ig + kz * 3;
            //
            g_temp_set[0] = ix;
            g_temp_set[1] = jy;
            g_temp_set[2] = Gkz;
            ELPH_float qGtemp[3] = {ix, jy, Gkz};  //|G|
            //
            MatVec3f(blat, qGtemp, false, Gvecs_z + 3 * kz);
            // 2*pi is included here //
            for (int ii = 0; ii < 3; ++ii)
            {
                Gvecs_z[kz * 3 + ii] /= (2.0 * ELPH_PI);
            }
        }
        dVlong_range_kernel(qcart, Gvecs_z, Gbox[2], Zvals_tmp, epslion, Zeu,
                            Qpole, natom, atom_pos, cutoff, volume, latvec[8],
                            EcutRy, VlocGz_cart);
        // VlocG -> (nffs,atom,3),
        //  get it in mode basis @ (nu,atom,3) @(nffs,atom,3)^T
        matmul_cmplx('N', 'T', eigVec, VlocGz_cart, VlocG + Gbox[2] * ig, 1.0,
                     0.0, nmodes, nmodes, size_G_vecs, nmodes, Gbox[2], nmodes);
    }
    free(Gvecs_z);
    free(VlocGz_cart);
    struct ELPH_fft_plan fft_plan;
    wfc_plan(&fft_plan, size_G_vecs, lattice->nfftz_loc, G_vecs_xy, gvecs,
             lattice->fft_dims, FFTW_MEASURE, commK);
    ELPH_cmplx* Vlocr = calloc(nffts_loc, sizeof(*Vlocr));
    CHECK_ALLOC(Vlocr);
    ELPH_float add_sub_factor = 1.0;
    if (sign < 0)
    {
        add_sub_factor = -1.0;
    }
    for (ND_int imode = 0; imode < nmodes; ++imode)
    {
        invfft3D(&fft_plan, 1, VlocG + imode * size_G_vecs, Vlocr, false);
        for (ND_int imag = 0; imag < lattice->nmag; ++imag)
        {
            if (nmags_add[imag])
            {
                ELPH_cmplx* dvscf_tmp =
                    dVscf + (imode * lattice->nmag + imag) * nffts_loc;
                for (ND_int ift = 0; ift < nffts_loc; ++ift)
                {
                    dvscf_tmp[ift] =
                        dvscf_tmp[ift] + add_sub_factor * Vlocr[ift];
                }
            }
        }
    }
    wfc_destroy_plan(&fft_plan);
    free(gvecs);
    free(VlocG);
    ELPH_stop_clock("dV_longrange");
}
References Lattice::alat_vec, Lattice::atomic_pos, Lattice::blat_vec, CHECK_ALLOC, Lattice::dimension, dVlong_range_kernel(), ELPH_EPS, ELPH_PI, ELPH_start_clock(), ELPH_stop_clock(), Phonon::epsilon, error_msg, Lattice::fft_dims, get_fft_box(), get_miller_idx(), get_mpi_local_size_idx(), ELPH_fft_plan::gvecs, invfft3D(), matmul_cmplx(), MatVec3f(), MIN, Lattice::natom, Lattice::nfftz_loc, Lattice::nmag, Lattice::nmodes, Phonon::Qpole, Lattice::volume, wfc_destroy_plan(), wfc_plan(), and Phonon::Zborn.
Referenced by interpolation_driver().
dVlocq()
void dVlocq (const ELPH_float * qpt, struct Lattice * lattice, struct Pseudo * pseudo, const ELPH_cmplx * eigVec, ELPH_cmplx * Vlocr, MPI_Comm commK)
Computes the change in local bare potential in real space due to atomic displacements.
This function calculates the derivative of the local pseudopotential (dVloc/dtau) in real space for a given q-point, transforming from reciprocal space (G-vectors) using an inverse FFT. The result is projected onto phonon modes using the provided eigenvectors.
Mathematical Formulation:
The local potential derivative in reciprocal space is: [ \frac{dV_{loc}(q+G)}{d\tau} = -i (q+G) \cdot V_{loc}(|q+G|) \cdot e^{-i(q+G)\cdot\tau} ]
After interpolation and mode projection, an inverse FFT is applied to obtain the real-space result.
Parameters
[in] qpt q-point in crystal coordinates (range: [-1, 1]).
[in] lattice Pointer to Lattice structure containing:
alat_vec/blat_vec (lattice/reciprocal vectors),
atomic_pos (Cartesian positions),
atom_type (atomic species indices),
fft_dims (FFT grid dimensions),
dimension (cutoff type: '3', '2', or '1' for 3D/2D/1D).
[in] pseudo Pointer to Pseudo structure with pseudopotential tables:
vloc_table (interpolation data for Vloc(G)),
loc_pseudo[itype].Zval (valence charge per species).
[in] eigVec Phonon eigenvectors (shape: [nmodes, 3*natom]), used to project onto modes.
[out] Vlocr Output array (shape: [nmodes, nffts_loc]) storing the real-space dVloc/dtau for each mode.
[in] commK MPI communicator for parallel FFT grid distribution.
Attention
The q-point must be in fractional coordinates (range [-1, 1]).
Memory for Vlocr must be pre-allocated by the caller.
Uses spline interpolation for Vloc(G) and includes a long-range Coulomb correction.
For 2D systems (‘cutoff == '2’`), an analytic cutoff is applied to remove z-periodicity.
Warning
Terminates with error_msg if:
No G-vectors are assigned to a process (G_vecs_xy < 1).
|q+G| exceeds the interpolation table bounds.
Definition at line 16 of file dVbare_loc.c.
{
    ELPH_start_clock("dV_bare");
    const ELPH_float* latvec = lattice->alat_vec;
    const ND_int ntype = pseudo->ntype;
    const ELPH_float* atom_pos = lattice->atomic_pos;
    const int* atom_type = lattice->atom_type;
    const char cutoff = lattice->dimension;
    const ND_int natom = lattice->natom;
    const ND_int nmodes = lattice->nmodes;
    const ND_int FFTx = lattice->fft_dims[0];
    const ND_int FFTy = lattice->fft_dims[1];
    const ND_int FFTz = lattice->fft_dims[2];
    const ELPH_float volume = lattice->volume;
    const ELPH_float* blat = lattice->blat_vec;
    const ELPH_float eta = 1.0;
    /* This is spread of nuclear charge */
    const ND_int nffts_loc = FFTx * FFTy * lattice->nfftz_loc;
    for (ND_int i = 0; i < (nffts_loc * nmodes); ++i)
    {
        Vlocr[i] = 0;
    }
    ND_int G_vecs_xy, Gxy_shift;
    G_vecs_xy = get_mpi_local_size_idx(FFTx * FFTy, &Gxy_shift, commK);
    if (G_vecs_xy < 1)
    {
        error_msg("Some process do not contain G vectors");
    }
    const ND_int size_G_vecs = G_vecs_xy * lattice->fft_dims[2];
    const ND_int size_VG = nmodes * size_G_vecs;
    // this must be calloc
    ELPH_cmplx* VlocG = calloc(size_VG, sizeof(ELPH_cmplx));
    CHECK_ALLOC(VlocG);
    int* gvecs = malloc(3 * size_G_vecs * sizeof(int));
    CHECK_ALLOC(gvecs);
    const ND_int npts_co = pseudo->vloc_table->npts_co;
    const ELPH_float* g_co = pseudo->vloc_table->g_co;
    const ELPH_float* vlocg = pseudo->vloc_table->vlocg;
    const ELPH_float* vploc_co = pseudo->vloc_table->vploc_co;
    const ELPH_float dg =
        pseudo->vloc_table->dg;  // spacing between two g points in g_co
    ELPH_float* VlocGtype = malloc(sizeof(ELPH_float) * (ntype));
    CHECK_ALLOC(VlocGtype);
    ELPH_cmplx* VlocGz_cart = malloc(FFTz * nmodes * sizeof(ELPH_cmplx));
    CHECK_ALLOC(VlocGz_cart);
    // Note. No openmp par for, not thread safe for this outer most loop.
    for (ND_int ig = 0; ig < G_vecs_xy; ++ig)
    {
        const ND_int fft_glob_idx = Gxy_shift + ig;
        const ND_int ix = fft_glob_idx / FFTy;
        const ND_int jy = fft_glob_idx % FFTy;
        for (ND_int kz = 0; kz < FFTz; ++kz)
        {
            int* g_temp_set = gvecs + FFTz * 3 * ig + kz * 3;
            g_temp_set[0] = ix;
            g_temp_set[1] = jy;
            g_temp_set[2] = kz;
            ELPH_float qGtemp[3] = {
                get_miller_idx(ix, FFTx) + qpt[0],
                get_miller_idx(jy, FFTy) + qpt[1],
                get_miller_idx(kz, FFTz) + qpt[2]};  // | q + G|
            ELPH_float qGtempCart[3];  // in cartisian coordinate
            MatVec3f(blat, qGtemp, false,
                     qGtempCart);  // 2*pi is included here //
            ELPH_float qGnorm = sqrt(qGtempCart[0] * qGtempCart[0] +
                                     qGtempCart[1] * qGtempCart[1] +
                                     qGtempCart[2] * qGtempCart[2]);
            if (qGnorm > g_co[npts_co - 1])
            {
                error_msg("Vlocg Interpolation failed due to out of bounds");
            }
            ND_int gidx = floor(qGnorm / dg);
            ELPH_cmplx* tmp_ptr = VlocGz_cart + kz * nmodes;
            ELPH_float cutoff_fac = 1;
            /* using analytic cutoff which works only when z periodicity is
             * broken */
            if (cutoff == '2')
            {
                ELPH_float Gp_norm = sqrt(qGtempCart[0] * qGtempCart[0] +
                                          qGtempCart[1] * qGtempCart[1]);
                ELPH_float qGp = latvec[8] * Gp_norm;
                ELPH_float cos_sin_fac = cos(qGtempCart[2] * latvec[8] * 0.5);
                if (Gp_norm > ELPH_EPS)
                {
                    cos_sin_fac =
                        cos_sin_fac - sin(qGtempCart[2] * latvec[8] * 0.5) *
                                          qGtempCart[2] / Gp_norm;
                }
                cutoff_fac = 1 - exp(-qGp * 0.5) * cos_sin_fac;
            }
            for (ND_int itype = 0; itype < ntype; ++itype)
            {
                VlocGtype[itype] = spline_interpolate(
                    qGnorm, gidx, g_co, vlocg + itype * npts_co,
                    vploc_co + itype * npts_co);
                // add long range part back
                if (qGnorm >= ELPH_EPS)
                {
                    VlocGtype[itype] -= (4 * ELPH_PI * ELPH_e2) *
                                        ((pseudo->loc_pseudo)[itype].Zval) *
                                        exp(-qGnorm * qGnorm * 0.25 / eta) *
                                        cutoff_fac / (qGnorm * qGnorm * volume);
                }
                // printf("%f \n",VlocGtype[itype]);
            }
            ELPH_OMP_PAR_SIMD
            for (ND_int ia = 0; ia < natom; ++ia)
            {
                const ND_int itype = atom_type[ia];
                const ELPH_float* pos_temp = atom_pos + 3 * ia;
                ELPH_float qdottau = qGtempCart[0] * pos_temp[0] +
                                     qGtempCart[1] * pos_temp[1] +
                                     qGtempCart[2] * pos_temp[2];
                ELPH_cmplx factor = -I * cexp(-I * qdottau);
                factor *= VlocGtype[itype];
                tmp_ptr[ia * 3] = factor * qGtempCart[0];
                tmp_ptr[ia * 3 + 1] = factor * qGtempCart[1];
                tmp_ptr[ia * 3 + 2] = factor * qGtempCart[2];
            }
        }
        // VlocG -> (nffs,atom,3),
        //  get it in mode basis @ (nu,atom,3) @(nffs,atom,3)^T
        matmul_cmplx('N', 'T', eigVec, VlocGz_cart, VlocG + FFTz * ig, 1.0, 0.0,
                     nmodes, nmodes, size_G_vecs, nmodes, FFTz, nmodes);
    }
    free(VlocGtype);
    free(VlocGz_cart);
    struct ELPH_fft_plan fft_plan;
    wfc_plan(&fft_plan, size_G_vecs, lattice->nfftz_loc, G_vecs_xy, gvecs,
             lattice->fft_dims, FFTW_MEASURE, commK);
    invfft3D(&fft_plan, nmodes, VlocG, Vlocr, false);
    wfc_destroy_plan(&fft_plan);
    free(gvecs);
    free(VlocG);
    ELPH_stop_clock("dV_bare");
}
References Lattice::alat_vec, Lattice::atom_type, Lattice::atomic_pos, Lattice::blat_vec, CHECK_ALLOC, Vloc_table::dg, Lattice::dimension, ELPH_e2, ELPH_EPS, ELPH_OMP_PAR_SIMD, ELPH_PI, ELPH_start_clock(), ELPH_stop_clock(), error_msg, Lattice::fft_dims, Vloc_table::g_co, get_miller_idx(), get_mpi_local_size_idx(), ELPH_fft_plan::gvecs, invfft3D(), Pseudo::loc_pseudo, matmul_cmplx(), MatVec3f(), Lattice::natom, Lattice::nfftz_loc, Lattice::nmodes, Vloc_table::npts_co, Pseudo::ntype, spline_interpolate(), Pseudo::vloc_table, Vloc_table::vlocg, Lattice::volume, Vloc_table::vploc_co, wfc_destroy_plan(), and wfc_plan().
Referenced by elph_driver().
dVlong_range_kernel()
void dVlong_range_kernel (const ELPH_float * qpt, const ELPH_float * gvecs, const ND_int npw_loc, const ELPH_float * Zvals, const ELPH_float * epslion, const ELPH_float * Zeu, const ELPH_float * Qpole, const ND_int natom, const ELPH_float * atom_pos, const char diminsion, const ELPH_float volume, const ELPH_float zlat, const ELPH_float EcutRy, ELPH_cmplx * elph_lr_out)
Definition at line 33 of file dVlong_range_kernel.c.
{
    // gvecs in cartisian coordinates  ( no 2*pi)
    // qpt in cart units             ( no 2*pi)
    // npw_loc, number of gvecs in this cpu
    // atomic pos in cart units
    // elph_lr_out (npw_loc, natom,3)
    // zlat in the dimension along the out ot plane direction.
    // only used in the 2D case
    // first zero out the elph_lr_out buffer
    // note that in ca
    // //
    // NOTE: Donot forget to allreduce the result over plane waves.
    // EcutRy : Energy cut off in Ry. The deformation potential pws for
    // |q+G|^2 > EcutRy is set to zero.
    // //
    //
    // (3D) C. Verdi, F. Giustino PhysRevLett.115.176401
    // (2D) T Deng et. al Phys. Rev. B 103, 075410 (2021)
    // (2D) T Sohier et. al  Phys. Rev. B 96, 075448 (2017)
    // Quadrupoles : G Brunin et al Phys. Rev. Lett. 125, 136601
    //
    for (ND_int i = 0; i < (3 * natom * npw_loc); ++i)
    {
        elph_lr_out[i] = 0.0;
    }
    if (!epslion && !Zvals)
    {
        return;
    }
    const ELPH_cmplx factor =
        4.0 * ELPH_PI * I * ELPH_e2 / volume;  // prefactor
    for (ND_int ig = 0; ig < npw_loc; ++ig)
    {
        const ELPH_float* gtmp = gvecs + 3 * ig;
        ELPH_float qplusG[3];
        for (int i = 0; i < 3; ++i)
        {
            qplusG[i] = 2 * ELPH_PI * (qpt[i] + gtmp[i]);
        }
        const ELPH_float qplusG_norm2 = dot3_macro(qplusG, qplusG);
        if (qplusG_norm2 > EcutRy)
        {
            continue;
        }
        for (ND_int ia = 0; ia < natom; ++ia)
        {
            const ELPH_float* Zval = Zvals ? (Zvals + ia) : NULL;
            const ELPH_float* Z_k = Zeu ? (Zeu + 9 * ia) : NULL;
            const ELPH_float* Q_k = Qpole ? (Qpole + 27 * ia) : NULL;
            const ELPH_float* tau_k = atom_pos + 3 * ia;
            ELPH_cmplx* out_tmp_buf = elph_lr_out + ia * 3 + ig * natom * 3;
            if (diminsion == '3')
            {
                long_range_3D_kernel(qplusG, Zval, Z_k, Q_k, epslion, tau_k,
                                     out_tmp_buf);
            }
            else if (diminsion == '2')
            {
                long_range_2D_kernel(qplusG, Zval, Z_k, Q_k, epslion, tau_k,
                                     zlat, 2 * ELPH_PI * qpt[2], out_tmp_buf);
            }
            // multiply with prefactor
            for (ND_int i = 0; i < 3; ++i)
            {
                out_tmp_buf[i] *= factor;
            }
        }
    }
    return;
}
References dot3_macro, ELPH_e2, ELPH_PI, long_range_2D_kernel(), and long_range_3D_kernel().
Referenced by dV_add_longrange().
dVscf_change_basis()
void dVscf_change_basis (ELPH_cmplx * dvscf, const ELPH_cmplx * rot_vecs, const ND_int nsets, const ND_int nmodes, const ND_int nmag, const ND_int Nx, const ND_int Ny, const ND_int Nz, const char blas_char)
Definition at line 12 of file dvscf_basis_rotation.c.
{
    // dVscf, (nsets, nmodes, nmag, Nx, Ny, Nz_loc)
    // rot_vecs (modes, modes)
    // if blas_char == 'N" rot_vecs@dVscf
    // == 'C', rot_vecs^dagger @dvscf
    // === 'T' rot_vecs^T@dvscf
    ND_int tmp_buf_len = Ny * Nz * nmodes;
    ELPH_cmplx* tmp_buf = calloc(tmp_buf_len, sizeof(*tmp_buf));
    CHECK_ALLOC(tmp_buf);
    ND_int dvscf_stride = nmag * Nx * Ny * Nz;
    for (ND_int iset = 0; iset < nsets; ++iset)
    {
        for (ND_int img = 0; img < nmag; ++img)
        {
            for (ND_int ix = 0; ix < Nx; ++ix)
            {
                ELPH_cmplx* dvscf_tmp = dvscf + iset * nmodes * dvscf_stride +
                                        img * Nx * Ny * Nz + ix * Ny * Nz;
                matmul_cmplx(blas_char, 'N', rot_vecs, dvscf_tmp, tmp_buf, 1.0,
                             0.0, nmodes, dvscf_stride, Ny * Nz, nmodes,
                             Ny * Nz, nmodes);
                for (ND_int imode = 0; imode < nmodes; ++imode)
                {
                    memcpy(dvscf_tmp + imode * dvscf_stride,
                           tmp_buf + imode * Ny * Nz,
                           Ny * Nz * sizeof(*tmp_buf));
                }
            }
        }
    }
    free(tmp_buf);
}
References CHECK_ALLOC, and matmul_cmplx().
Referenced by interpolation_driver().
elphLocal()
void elphLocal (const ELPH_float * qpt, struct WFC * wfcs, struct Lattice * lattice, int ikq, int ik, int kqsym, int ksym, ELPH_cmplx * dVlocr, const struct ELPH_MPI_Comms * Comm, ELPH_cmplx * elph_kq)
Definition at line 17 of file compute_Vbare_loc.c.
{
    /* Computes <S2*k2 | dV_{q}local | S1*k1>
    Note that the inputs kvectors must full the following condition S2*k2 =
    S1*k1 + q + ulmveckq Input : . k+q and k wave functions, (nspin, bands,
    nspinor, ng) . kqvec, kvec are kvectors in (cart units ) for wfc_kq and
    wfc_k . Gkq, Gk  are Gvectors for wfc_kq and wfc_k, .
    ulmveckq is shift that is applyed to k+q vector i.e Skq*kq - S*k - q .
    symkq and symk are symmetric operations to be applied on k+q and k wave
    functions .
    taukq and tauk are fractional translation .
    Gkq and Gk are Gvectors for k+q and k wfs respectively .
    dVlocr -> change in local KS potential i.e dVlocal + dVscf (nmodes, nmag,
    Nx,Ny,Nz-loc) in for one mode . qpt -> qpoint in crystal units output : (nu,
    nspin, mk, nk+q) // electron-phonon mat in mode basis (only the master
    process writes)
    */
    ELPH_start_clock("elph local");
    const ND_int nspin = lattice->nspin;
    const ND_int nbnds = lattice->nbnds;
    const ND_int nspinor = lattice->nspinor;
    const ND_int nmodes = lattice->nmodes;
    const ND_int nmag = lattice->nmag;
    /* nmag = 1 for non magnetic and = 2/4 for spin
    polarized/magnetic systems */
    const ND_int nfft_loc =
        lattice->fft_dims[0] * lattice->fft_dims[1] * lattice->nfftz_loc;
    const ELPH_float* lat_vec = lattice->alat_vec;
    const ELPH_float* blat = lattice->blat_vec;
    // note this has 2*pi//
    // get the wfcs.  (nspin,nbnds,nspinor,npw)
    const ELPH_cmplx* wfc_kq = (wfcs + ikq)->wfc;
    const ELPH_float* Gkq = (wfcs + ikq)->gvec;
    ND_int npwkq = (wfcs + ikq)->npw_loc;
    // no const for the npwkq as sort_pw will change them
    const ELPH_cmplx* wfc_k = (wfcs + ik)->wfc;
    const ELPH_float* Gk = (wfcs + ik)->gvec;
    ND_int npwk = (wfcs + ik)->npw_loc;
    // no const for the npwk as sort_pw will change them
    const ND_int npwkq_total = (wfcs + ikq)->npw_total;
    const ND_int npwk_total = (wfcs + ik)->npw_total;
    /*initialization and setup */
    ELPH_float* gSkq_buf = calloc(3 * npwkq, sizeof(ELPH_float));
    CHECK_ALLOC(gSkq_buf);
    ELPH_float* gSk_buf = calloc(3 * npwk, sizeof(ELPH_float));
    CHECK_ALLOC(gSk_buf);
    /*initialization and setup */
    const ELPH_float* kqvec = lattice->kpt_iredBZ + 3 * ikq;
    const ELPH_float* kvec = lattice->kpt_iredBZ + 3 * ik;
    const ELPH_float* symkq = lattice->syms[kqsym].Rmat;
    const ELPH_float* symk = lattice->syms[ksym].Rmat;
    const ELPH_float* taukq = lattice->syms[kqsym].tau;
    const ELPH_float* tauk = lattice->syms[ksym].tau;
    const bool timerevkq = lattice->syms[kqsym].time_rev;
    const bool timerevk = lattice->syms[ksym].time_rev;
    ELPH_float ulmveckq[3];
    // ulmveckq is G shift that is applyed to k+q wfc
    // i.e ulmveckq = (Skq*kq - S*k - q)
    ELPH_float tempSkq[3] = {0, 0, 0};  //
    ELPH_float tempSk[3] = {0, 0, 0};   //
    ELPH_float taukq_crys[3], tauk_crys[3];
    // fractional translation in crystal coordinates
    ELPH_float kvecSkq[3], kvecSk[3];
    // Sk + q and Sk in crystal coordinates
    MatVec3f(symkq, kqvec, false, tempSkq);
    MatVec3f(symk, kvec, false, tempSk);
    MatVec3f(lat_vec, tempSk, true, kvecSk);
    // compute k + q
    for (int xi = 0; xi < 3; ++xi)
    {
        kvecSkq[xi] = kvecSk[xi] + qpt[xi];
    }
    // Now subtract k from Skq in cart units
    // i.e now tempSkq contains q + G
    for (int xi = 0; xi < 3; ++xi)
    {
        tempSkq[xi] -= tempSk[xi];
    }
    // convert qpt to cartisian coord
    // and store it in tempSk
    MatVec3f(blat, qpt, false, tempSk);
    // store qpt( in cart units ) in tempSk
    for (int xi = 0; xi < 3; ++xi)
    {
        tempSk[xi] = tempSk[xi] / (2 * ELPH_PI);
    }
    // convert tau to crystal coordinates
    MatVec3f(blat, taukq, true, taukq_crys);
    for (int xi = 0; xi < 3; ++xi)
    {
        taukq_crys[xi] = taukq_crys[xi] / (2 * ELPH_PI);
    }
    MatVec3f(blat, tauk, true, tauk_crys);
    for (int xi = 0; xi < 3; ++xi)
    {
        tauk_crys[xi] = tauk_crys[xi] / (2 * ELPH_PI);
    }
    // Finally get the ulmvec by subtracting q from q+G
    for (int xi = 0; xi < 3; ++xi)
    {
        ulmveckq[xi] = (tempSkq[xi] - tempSk[xi]);
    }
    // now rotate and shitf (only for k+q vector) G vectors
    rotateGvecs(Gkq, symkq, npwkq, lat_vec, false, true, ulmveckq, gSkq_buf);
    rotateGvecs(Gk, symk, npwk, lat_vec, false, true, NULL, gSk_buf);
    // rotate the wave function in spin space
    ELPH_cmplx su2kq[4] = {1, 0, 0, 1};
    ELPH_cmplx su2k[4] = {1, 0, 0, 1};
    /* Get SU(2) matrices for spinors*/
    SU2mat(symkq, nspinor, false, timerevkq, su2kq);
    SU2mat(symk, nspinor, false, timerevk, su2k);
    // in case of time rev, we have to complex conj the wavefunction,
    // which is done at sandwiching.
    /* scatter the wfc and gvecs */
    int* gvecSGkq;       // gvecs after rearragement // k+q
    int* gvecSGk;        // k
    ELPH_cmplx* wfcSkq;  // wfc after rearragement // k+q
    ELPH_cmplx* wfcSk;   // k
    ND_int nGxySkq, nGxySk;
    // Note : npwkq and npwk are overwritten by number of gvecs in gvecSGkq and
    // gvecSGk respectively. Sort_pw internally allocates buffer that must be
    // freed out side of the function
    Sort_pw(npwkq_total, npwkq, lattice->fft_dims, gSkq_buf, wfc_kq,
            nspin * nspinor * nbnds, &npwkq, &nGxySkq, &gvecSGkq, &wfcSkq,
            Comm->commK);
    Sort_pw(npwk_total, npwk, lattice->fft_dims, gSk_buf, wfc_k,
            nspin * nspinor * nbnds, &npwk, &nGxySk, &gvecSGk, &wfcSk,
            Comm->commK);
    // Note that we need to free gvecSGkq, gvecSGk, wfcSkq, wfcSk in this
    // function when no longer need
    free(gSkq_buf);
    free(gSk_buf);
    ND_int max_npw = ((npwkq > npwk) ? npwkq : npwk);
    /* Gvecs are stored in ints but we need it in float type, so we
    allocate a gvec array to store gvecs in floats (needed for translation
    routine) */
    ELPH_float* gvecs_float_tmp = malloc(sizeof(ELPH_float) * 3 * max_npw);
    CHECK_ALLOC(gvecs_float_tmp);
    for (ND_int ipw = 0; ipw < (3 * npwkq); ++ipw)
    {
        gvecs_float_tmp[ipw] = gvecSGkq[ipw];
    }
    /* Apply spinors and fractional translation to k+q wfc */
    for (ND_int iset = 0; iset < (nspin * nbnds); ++iset)
    {
        ELPH_cmplx* wfcSkq_tmp = wfcSkq + iset * nspinor * npwkq;
        // apply su2 rotation
        su2rotate(nspinor, npwkq, 1, su2kq, wfcSkq_tmp);
        // apply fractional translation
        apply_trans_wfc(taukq_crys, kvecSkq, nspinor, npwkq, gvecs_float_tmp,
                        wfcSkq_tmp, false);
    }
    ELPH_cmplx* wfcSk_r =
        malloc(sizeof(ELPH_cmplx) * nspin * nbnds * nspinor * nfft_loc);
    CHECK_ALLOC(wfcSk_r);
    struct ELPH_fft_plan fft_plan;
    // create plan for Sk
    wfc_plan(&fft_plan, npwk, lattice->nfftz_loc, nGxySk, gvecSGk,
             lattice->fft_dims, FFTW_MEASURE, Comm->commK);
    for (ND_int ipw = 0; ipw < (3 * npwk); ++ipw)
    {
        gvecs_float_tmp[ipw] = gvecSGk[ipw];
    }
    /* FFT Sk wave function to get it in real space */
    for (ND_int iset = 0; iset < (nspin * nbnds); ++iset)
    {
        // rotate spinor wfc
        ELPH_cmplx* wfcSk_tmp = wfcSk + iset * nspinor * npwk;
        su2rotate(nspinor, npwk, 1, su2k, wfcSk_tmp);
        // apply fractional translation
        apply_trans_wfc(tauk_crys, kvecSk, nspinor, npwk, gvecs_float_tmp,
                        wfcSk_tmp, false);
        ELPH_cmplx* wfcSkr_tmp = wfcSk_r + iset * nspinor * nfft_loc;
        // conjugate (only incase of timerevk is true) and then perform inverse
        // FFT.
        invfft3D(&fft_plan, nspinor, wfcSk_tmp, wfcSkr_tmp, timerevk);
        // Note that incase of time reversal symmetry,
        // inverse fft of the conjugate of input is performed.
        // Inputs are never altered in invfft3D function !
    }
    // free some buffers
    wfc_destroy_plan(&fft_plan);
    free(gvecSGk);
    free(wfcSk);
    free(gvecs_float_tmp);
    // create plan for dvSpi
    wfc_plan(&fft_plan, npwkq, lattice->nfftz_loc, nGxySkq, gvecSGkq,
             lattice->fft_dims, FFTW_MEASURE, Comm->commK);
    ELPH_cmplx* dVpsiG =
        malloc(sizeof(ELPH_cmplx) * nspin * nbnds * nspinor * npwkq);
    CHECK_ALLOC(dVpsiG);
    if (Comm->commK_rank == 0)
    {
        ND_int elph_buffer_len = nmodes * nbnds * nbnds * nspin;
        ELPH_OMP_PAR_FOR_SIMD
        for (ND_int i = 0; i < elph_buffer_len; ++i)
        {
            elph_kq[i] = 0.0;
        }
    }
    /* nmag is the spinor dimension of the change in potential */
    if (nmag == 2 && nspin != 2)
    {
        error_msg("Incompatible dvscf ");
    }
    if (nmag == 2 && nspinor != 1)
    {
        error_msg("Incompatible dvscf ");
    }
    //-------
    // create a temporary buffer to store local el-ph mat elements
    ELPH_cmplx* elph_kq_mn = calloc(nbnds * nbnds, sizeof(ELPH_cmplx));
    CHECK_ALLOC(elph_kq_mn);
    /* Now Get Sk in real space*/
    /* Compute dVpsi in G space and compute the sandwich */
    for (ND_int iv = 0; iv < nmodes; ++iv)
    {
        /*
        Compute dv*psi
        */
        ELPH_cmplx* dv_nu = dVlocr + nmag * nfft_loc * iv;
        // (nmodes, nmag, nfft_loc)
        for (ND_int is = 0; is < nspin; ++is)
        {
            ELPH_cmplx* psi_r_spin = wfcSk_r + is * nbnds * nspinor * nfft_loc;
            ELPH_cmplx* dV_r = dv_nu + nfft_loc * is;
            // only in nspin = 2 case, nmag represent nspin dimension
            for (ND_int ibnd = 0; ibnd < nbnds; ++ibnd)
            {
                /* compute the convolution FFT(dV(r)*psi(r))*/
                ELPH_cmplx* dV_psiG_ptr = dVpsiG +
                                          is * nbnds * nspinor * npwkq +
                                          ibnd * nspinor * npwkq;
                fft_convolution3D(&fft_plan, nspinor, nmag, dV_r,
                                  psi_r_spin + ibnd * nspinor * nfft_loc,
                                  dV_psiG_ptr, false);
            }
            // Compute the sandwich
            char blas_char = 'C';
            if (timerevkq)
            {
                blas_char = 'T';
                // we perform the time reversal conjugation for K+q wfc (if any)
                // here now
            }
            /* msg, nsg -> mn */
            // FIX ME donot forget time reversal here. // wfc_kq
            // elph_kq_mn+ (iv*nspin+is)*nbnds*nbnds
            matmul_cmplx('N', blas_char, dVpsiG + is * nbnds * nspinor * npwkq,
                         wfcSkq + is * (nbnds * nspinor * npwkq), elph_kq_mn,
                         1.0, 0.0, nspinor * npwkq, nspinor * npwkq, nbnds,
                         nbnds, nbnds, nspinor * npwkq);
            // reduce the electron phonon matrix elements
            ELPH_cmplx* elph_sum_buf;
            ELPH_cmplx temp_sum = 0;  // dummy
            if (Comm->commK_rank == 0)
            {
                elph_sum_buf = elph_kq + (iv * nspin + is) * nbnds * nbnds;
            }
            else
            {
                elph_sum_buf = &temp_sum;
            }
            int mpi_error = MPI_Reduce(elph_kq_mn, elph_sum_buf, nbnds * nbnds,
                                       ELPH_MPI_cmplx, MPI_SUM, 0, Comm->commK);
            MPI_error_msg(mpi_error);
        }
    }
    // Free stuff
    free(elph_kq_mn);
    wfc_destroy_plan(&fft_plan);
    free(dVpsiG);
    free(wfcSk_r);
    free(gvecSGkq);
    free(wfcSkq);
    ELPH_stop_clock("elph local");
    // Free stuff
}
References Lattice::alat_vec, apply_trans_wfc(), Lattice::blat_vec, CHECK_ALLOC, ELPH_MPI_Comms::commK, ELPH_MPI_Comms::commK_rank, ELPH_MPI_cmplx, ELPH_OMP_PAR_FOR_SIMD, ELPH_PI, ELPH_start_clock(), ELPH_stop_clock(), error_msg, fft_convolution3D(), Lattice::fft_dims, invfft3D(), Lattice::kpt_iredBZ, matmul_cmplx(), MatVec3f(), MPI_error_msg, Lattice::nbnds, Lattice::nfftz_loc, Lattice::nmag, Lattice::nmodes, Lattice::nspin, Lattice::nspinor, symmetry::Rmat, rotateGvecs(), Sort_pw(), SU2mat(), su2rotate(), Lattice::syms, symmetry::tau, symmetry::time_rev, wfc_destroy_plan(), and wfc_plan().
Referenced by compute_and_write_elphq().
free_vlocg_table()
void free_vlocg_table (struct Vloc_table * vloc_table)
Definition at line 156 of file vlocg_table.c.
{
    // free the allocate Vloc_table
    free(vloc_table->g_co);
    free(vloc_table->vlocg);
    free(vloc_table->vploc_co);
    vloc_table->g_co = NULL;
    vloc_table->vlocg = NULL;
    vloc_table->vploc_co = NULL;
}
References Vloc_table::g_co, Vloc_table::vlocg, and Vloc_table::vploc_co.
Referenced by free_save_data().
multiply_eikr()
void multiply_eikr (ELPH_cmplx * pot_grid, const ELPH_float * qpt_crys, const struct Lattice * lattice, const ND_int nsets, const ND_int sign)
Definition at line 14 of file multiply_eikr.c.
{
    // sign < 0. e^{-ikr} is multiplied
    // else e^{ikr} is multiplied
    // qpt in crystal coordinates
    //
    const ND_int nffts =
        lattice->fft_dims[0] * lattice->fft_dims[1] * lattice->nfftz_loc;
    ELPH_cmplx factor = 2 * I * ELPH_PI;
    if (sign < 0)
    {
        factor = -factor;
    }
    ELPH_cmplx* eikr = malloc(sizeof(*eikr) * nffts);
    CHECK_ALLOC(eikr);
    ND_int FFTyz = lattice->fft_dims[1] * lattice->nfftz_loc;
    // (Nx, Ny, Nz_loc)  (Ny*Nz_loc, Nz_loc, 1)
    ELPH_OMP_PAR_FOR_SIMD
    for (ND_int ig = 0; ig < nffts; ++ig)
    {
        ND_int ix = ig / FFTyz;
        ND_int iy = (ig % FFTyz) / lattice->nfftz_loc;
        ND_int iz =
            lattice->nfftz_loc_shift + (ig % FFTyz) % lattice->nfftz_loc;
        ELPH_float ri = ((ELPH_float)ix) / lattice->fft_dims[0];
        ELPH_float rj = ((ELPH_float)iy) / lattice->fft_dims[1];
        ELPH_float rk = ((ELPH_float)iz) / lattice->fft_dims[2];
        ELPH_float qdotr =
            qpt_crys[0] * ri + qpt_crys[1] * rj + qpt_crys[2] * rk;
        eikr[ig] = cexp(factor * qdotr);
    }
    for (ND_int iset = 0; iset < nsets; ++iset)
    {
        ELPH_cmplx* pot_grid_iset = pot_grid + iset * nffts;
        ELPH_OMP_PAR_FOR_SIMD
        for (ND_int ig = 0; ig < nffts; ++ig)
        {
            pot_grid_iset[ig] *= eikr[ig];
        }
    }
    free(eikr);
}
References CHECK_ALLOC, ELPH_OMP_PAR_FOR_SIMD, ELPH_PI, Lattice::fft_dims, Lattice::nfftz_loc, and Lattice::nfftz_loc_shift.
Referenced by interpolation_driver().
Vloc_Gspace()
ELPH_float Vloc_Gspace (ELPH_float * work_arr, const char cutoff, const ELPH_float Gnorm, const ND_int ngrid, const ELPH_float * Vloc_atomic, const ELPH_float * r_grid, const ELPH_float * rab_grid, const ELPH_float Zval, const ELPH_float eta, const ELPH_float volume)
Definition at line 10 of file VlocG_atom.c.
{
    /* work_arr is the work array. dims = (ngrid)
    We do not call malloc/free inside this function as this function is called
    with a very high frequency and can lead to fragmentation of memory. Gnorm ==
    0 only whene q = 0 and G = 0
    */
    ELPH_float VlocGq;
    /* PseudoPot is spilt into long range and short range */
    /*
    Lt x-> 0 erf(r)/r = 2/sqrt(pi)
    */
    ELPH_float sqrt_eta = sqrt(eta);
    /* Compute the integrate i.e V_{SR}(r)*/
    for (ND_int imesh = 0; imesh < ngrid; ++imesh)
    {
        ELPH_float fac, radius;
        radius = r_grid[imesh];
        if (Gnorm < ELPH_EPS)
        {
            fac = radius;
        }
        else
        {
            fac = sin(radius * Gnorm) / Gnorm;
        }
        if (cutoff == '3' && Gnorm < ELPH_EPS)
        {
            fac *= (radius * Vloc_atomic[imesh] + ELPH_e2 * Zval);
        }
        else
        {
            fac *= (radius * Vloc_atomic[imesh] +
                    ELPH_e2 * Zval * erf(radius * sqrt_eta));
        }
        work_arr[imesh] = fac;
    }
    VlocGq = simpson(work_arr, rab_grid, ngrid);
    return 4 * ELPH_PI * VlocGq / volume;
}
References ELPH_e2, ELPH_EPS, ELPH_PI, and simpson().
Referenced by create_vlocg_table().