LetzElPhC: src/common/numerical_func.c File Reference
numerical_func.c File Reference
#include "numerical_func.h"
#include <complex.h>
#include <math.h>
#include <stdbool.h>
#include <stdlib.h>
#include "constants.h"
#include "elphC.h"
#include "error.h"
#include "omp_pragma_def.h"
Functions
static ELPH_float factorial (ND_int n)
ELPH_float legendre (int l_val, int m_val, ELPH_float x_in)
ELPH_float Ylm (int l_val, int m_val, ELPH_float *vec)
ELPH_float simpson (const ELPH_float *func_vals, const ELPH_float *dx, ND_int npts)
ELPH_float cos_angle_bw_Vec (const ELPH_float *vec1, const ELPH_float *vec2)
void MatVec3f (const ELPH_float *Mat, const ELPH_float *vec, const bool trans, ELPH_float *restrict out)
ELPH_cmplx Cmplxdot (const ELPH_cmplx *vec1, const ELPH_cmplx *vec2, const ND_int n)
void normalize_Cmplx_vec (ELPH_cmplx *vec, const ND_int n)
ELPH_float det3x3 (const ELPH_float *mat)
void reciprocal_vecs (const ELPH_float *lat_vec, ELPH_float *restrict blat)
void aXpY (const ND_int n, const ELPH_cmplx a, const ELPH_cmplx *X, ELPH_cmplx *Y)
void transpose3x3f (const ELPH_float *inmat, ELPH_float *restrict outmat)
void transpose3x3f_inplace (ELPH_float *mat)
ND_int find_maxint (ND_int *in_arr, ND_int nelements)
ELPH_float find_maxfloat (ELPH_float *in_arr, ND_int nelements)
void Gemm3x3f (const ELPH_float *A, const char transA, const ELPH_float *B, const char transB, ELPH_float *restrict C)
void matmul_Cmpl2x2 (ELPH_cmplx *mat1, ELPH_cmplx *mat2, ELPH_cmplx *restrict out)
ND_int get_miller_idx (ND_int idx_in, ND_int FFT_dimension)
int get_fft_idx (ELPH_float idx_in, int FFT_dimension)
ND_int find_kidx_in_list (ND_int nkpts, const ELPH_float *kpts_list, const ELPH_float *kpt)
void get_KplusQ_idxs (const ND_int Nbz, const ELPH_float *kpoints, const ELPH_float *Q_pt, int *KplusQidxs)
void swap_ints (int *a, int *b)
void swap_floats (ELPH_float *a, ELPH_float *b)
Function Documentation
aXpY()
void aXpY (const ND_int n, const ELPH_cmplx a, const ELPH_cmplx * X, ELPH_cmplx * Y)
Definition at line 303 of file numerical_func.c.
{
    /* computes y= aX + y */
    // ELPH_OMP_PAR_FOR_SIMD
    for (ND_int i = 0; i < n; ++i)
    {
        Y[i] += a * X[i];
    }
}
Cmplxdot()
ELPH_cmplx Cmplxdot (const ELPH_cmplx * vec1, const ELPH_cmplx * vec2, const ND_int n)
Definition at line 242 of file numerical_func.c.
{
    ELPH_cmplx sum = 0.0;
    for (ND_int i = 0; i < n; ++i)
    {
        sum += conj(vec1[i]) * vec2[i];
    }
    return sum;
}
Referenced by normalize_Cmplx_vec().
cos_angle_bw_Vec()
ELPH_float cos_angle_bw_Vec (const ELPH_float * vec1, const ELPH_float * vec2)
Definition at line 194 of file numerical_func.c.
{
    /*
    This function returns Cos(w) where w is angle between vec1 and vec2
    */
    ELPH_float norm1 =
        vec1[0] * vec1[0] + vec1[1] * vec1[1] + vec1[2] * vec1[2];
    ELPH_float norm2 =
        vec2[0] * vec2[0] + vec2[1] * vec2[1] + vec2[2] * vec2[2];
    ELPH_float norm = sqrt(norm1 * norm2);
    if (norm < ELPH_EPS)
    {
        return 0;
    }
    ELPH_float dot_12 =
        vec1[0] * vec2[0] + vec1[1] * vec2[1] + vec1[2] * vec2[2];
    return dot_12 / norm;
}
References ELPH_EPS.
det3x3()
ELPH_float det3x3 (const ELPH_float * mat)
Definition at line 270 of file numerical_func.c.
{
    ELPH_float det = 0;
    det += mat[0] * (mat[4] * mat[8] - mat[5] * mat[7]);
    det -= mat[1] * (mat[3] * mat[8] - mat[5] * mat[6]);
    det += mat[2] * (mat[7] * mat[3] - mat[4] * mat[6]);
    return det;
}
Referenced by read_and_alloc_save_data(), reciprocal_vecs(), and SU2mat().
factorial()
ELPH_float factorial (ND_int n) static
Static functions
Definition at line 216 of file numerical_func.c.
{
    if (n < 0)
    {
        return 0.0;  // error
    }
    return tgamma(n + 1);
}
Referenced by legendre(), and Ylm().
find_kidx_in_list()
ND_int find_kidx_in_list (ND_int nkpts, const ELPH_float * kpts_list, const ELPH_float * kpt)
Definition at line 470 of file numerical_func.c.
{
    /*
    kpt and kpts_list must be in crystal coordinates
    return -1 if not found
    */
    ND_int kidx = -1;
    for (ND_int ik = 0; ik < nkpts; ++ik)
    {
        const ELPH_float* ik_vec_tmp = kpts_list + 3 * ik;
        ELPH_float sum = 0;
        for (int i = 0; i < 3; ++i)
        {
            ELPH_float diff_tmp = ik_vec_tmp[i] - kpt[i];
            diff_tmp = diff_tmp - rint(diff_tmp);
            sum += diff_tmp * diff_tmp;
        }
        sum = sqrt(sum);
        if (sum < ELPH_EPS)
        {
            kidx = ik;
            break;
        }
    }
    return kidx;
}
References ELPH_EPS.
Referenced by bz_expand(), compute_and_write_elphq(), electronic_reps(), generate_iBZ_kpts(), get_KplusQ_idxs(), and rotate_eig_vecs().
find_maxfloat()
ELPH_float find_maxfloat (ELPH_float * in_arr, ND_int nelements)
Definition at line 352 of file numerical_func.c.
{
    ELPH_float max = in_arr[0];
    for (ND_int imax = 0; imax < nelements; ++imax)
    {
        if (in_arr[imax] > max)
        {
            max = in_arr[imax];
        }
    }
    // printf("Max : %llu \n ", max);
    return max;
}
Referenced by read_and_alloc_save_data().
find_maxint()
ND_int find_maxint (ND_int * in_arr, ND_int nelements)
Definition at line 338 of file numerical_func.c.
{
    ND_int max = in_arr[0];
    for (ND_int imax = 0; imax < nelements; ++imax)
    {
        if (in_arr[imax] > max)
        {
            max = in_arr[imax];
        }
    }
    // printf("Max : %llu \n ", max);
    return max;
}
Referenced by read_and_alloc_save_data().
Gemm3x3f()
void Gemm3x3f (const ELPH_float * A, const char transA, const ELPH_float * B, const char transB, ELPH_float *restrict C)
Definition at line 366 of file numerical_func.c.
{
    if (transA == 'N' && transB == 'N')
    {
        C[0] = A[0] * B[0] + A[1] * B[3] + A[2] * B[6];
        C[1] = A[0] * B[1] + A[1] * B[4] + A[2] * B[7];
        C[2] = A[0] * B[2] + A[1] * B[5] + A[2] * B[8];
        C[3] = A[3] * B[0] + A[4] * B[3] + A[5] * B[6];
        C[4] = A[3] * B[1] + A[4] * B[4] + A[5] * B[7];
        C[5] = A[3] * B[2] + A[4] * B[5] + A[5] * B[8];
        C[6] = A[6] * B[0] + A[7] * B[3] + A[8] * B[6];
        C[7] = A[6] * B[1] + A[7] * B[4] + A[8] * B[7];
        C[8] = A[6] * B[2] + A[7] * B[5] + A[8] * B[8];
    }
    else if (transA == 'T' && transB == 'N')
    {
        C[0] = A[0] * B[0] + A[3] * B[3] + A[6] * B[6];
        C[1] = A[0] * B[1] + A[3] * B[4] + A[6] * B[7];
        C[2] = A[0] * B[2] + A[3] * B[5] + A[6] * B[8];
        C[3] = A[1] * B[0] + A[4] * B[3] + A[7] * B[6];
        C[4] = A[1] * B[1] + A[4] * B[4] + A[7] * B[7];
        C[5] = A[1] * B[2] + A[4] * B[5] + A[7] * B[8];
        C[6] = A[2] * B[0] + A[5] * B[3] + A[8] * B[6];
        C[7] = A[2] * B[1] + A[5] * B[4] + A[8] * B[7];
        C[8] = A[2] * B[2] + A[5] * B[5] + A[8] * B[8];
    }
    else if (transA == 'N' && transB == 'T')
    {
        C[0] = A[0] * B[0] + A[1] * B[1] + A[2] * B[2];
        C[1] = A[0] * B[3] + A[1] * B[4] + A[2] * B[5];
        C[2] = A[0] * B[6] + A[1] * B[7] + A[2] * B[8];
        C[3] = A[3] * B[0] + A[4] * B[1] + A[5] * B[2];
        C[4] = A[3] * B[3] + A[4] * B[4] + A[5] * B[5];
        C[5] = A[3] * B[6] + A[4] * B[7] + A[5] * B[8];
        C[6] = A[6] * B[0] + A[7] * B[1] + A[8] * B[2];
        C[7] = A[6] * B[3] + A[7] * B[4] + A[8] * B[5];
        C[8] = A[6] * B[6] + A[7] * B[7] + A[8] * B[8];
    }
    else if (transA == 'T' && transB == 'T')
    {
        C[0] = A[0] * B[0] + A[3] * B[1] + A[6] * B[2];
        C[1] = A[0] * B[3] + A[3] * B[4] + A[6] * B[5];
        C[2] = A[0] * B[6] + A[3] * B[7] + A[6] * B[8];
        C[3] = A[1] * B[0] + A[4] * B[1] + A[7] * B[2];
        C[4] = A[1] * B[3] + A[4] * B[4] + A[7] * B[5];
        C[5] = A[1] * B[6] + A[4] * B[7] + A[7] * B[8];
        C[6] = A[2] * B[0] + A[5] * B[1] + A[8] * B[2];
        C[7] = A[2] * B[3] + A[5] * B[4] + A[8] * B[5];
        C[8] = A[2] * B[6] + A[5] * B[7] + A[8] * B[8];
    }
    else
    {
        error_msg("Wrong Trans type");
    }
    return;
}
References error_msg.
Referenced by electronic_reps(), rotate_dvscf(), and rotateGvecs().
get_fft_idx()
int get_fft_idx (ELPH_float idx_in, int FFT_dimension)
Definition at line 451 of file numerical_func.c.
{
    /*
    We need this functions because FFT libraries assume that the
    indices run from [0,N) but where as miller indices are from
    [-N/2,N/1)
    */
    // returns FFT Indices to [0, N-1]
    int temp_idx = rint(idx_in);
    if (temp_idx >= 0)
    {
        return temp_idx;
    }
    else
    {
        return FFT_dimension + temp_idx;
    }
}
get_KplusQ_idxs()
void get_KplusQ_idxs (const ND_int Nbz, const ELPH_float * kpoints, const ELPH_float * Q_pt, int * KplusQidxs)
Definition at line 499 of file numerical_func.c.
{
    /* returns index of the k+q point in the kpoints*/
    // kpoitsn and  kpoints must be in crystal coordinates
    for (ND_int i = 0; i < Nbz; ++i)
    {
        const ELPH_float* ktemp = kpoints + 3 * i;
        ELPH_float KplusQ[3];
        KplusQ[0] = ktemp[0] + Q_pt[0];
        KplusQ[1] = ktemp[1] + Q_pt[1];
        KplusQ[2] = ktemp[2] + Q_pt[2];
        KplusQidxs[i] = find_kidx_in_list(Nbz, kpoints, KplusQ);
        if (KplusQidxs[i] < 0)
        {
            error_msg(
                "K+Q point cannot be found in kgrid. "
                "The k-grid and q-grid are not commensurate! \n");
        }
    }
}
References error_msg, and find_kidx_in_list().
Referenced by compute_and_write_elphq().
get_miller_idx()
ND_int get_miller_idx (ND_int idx_in, ND_int FFT_dimension)
Definition at line 435 of file numerical_func.c.
{
    // returns FFT Indices to [-N/2, N/2) if FFT_dimension is even
    // [-(n-1)/2,(n-1)/2 )] of FFT_dimension is odd
    ND_int mid_pnt = (FFT_dimension - 1) / 2 + 1;
    if (idx_in < mid_pnt)
    {
        return idx_in;
    }
    else
    {
        return (idx_in - mid_pnt) - FFT_dimension / 2;
    }
}
Referenced by add_ph_dyn_long_range_internal(), build_wigner_seitz_vectors(), dV_add_longrange(), dVlocq(), fft_R2q_dvscf(), and fft_R2q_dyn().
legendre()
ELPH_float legendre (int l_val, int m_val, ELPH_float x_in)
Definition at line 28 of file numerical_func.c.
{
    /* This does not contain Condon–Shortley phase
    Eq: 9-12 in
    "Miguel A. Blanco, M. Flórez, M. Bermejo
    Evaluation of the rotation matrices in the basis of real spherical harmonics
    J. Mol. Struct. THEOCHEM 419, 19-27 (1997)"
    */
    /* Order of below if-else conditions is important */
    if (l_val == 0 && m_val == 0)
    {
        return 1.0;
    }
    else if (l_val < 0)
    {
        return legendre(-l_val - 1, m_val, x_in);
    }
    else if (abs(m_val) > l_val)
    {
        return 0.0;
    }
    else if (m_val < 0)
    {
        return legendre(l_val, -m_val, x_in) * pow(-1, -m_val) *
               factorial(l_val + m_val) / factorial(l_val - m_val);
    }
    else
    {
        ELPH_float legendre_val = 1.0;
        ELPH_float sqrt_xin = sqrt(1 - (x_in * x_in));
        /* P^l_l = (2l-1)*sqrt(1-x^2)*P^{l-1}_{l-1}(x)  */
        for (int im = 1; im <= m_val; ++im)
        {
            legendre_val *= (2 * im - 1) * sqrt_xin;
        }
        if (l_val == m_val)
        {
            return legendre_val;
        }
        ELPH_float legendre_val_mm = legendre_val;
        /* P^l_l+1 = (2l+1)*x*P^l_l*/
        legendre_val *= (2 * m_val + 1) * x_in;
        if (l_val == (m_val + 1))
        {
            return legendre_val;
        }
        /* For all other l,m combination */
        for (int im = m_val + 2; im <= l_val; ++im)
        {
            ELPH_float legendre_temp = legendre_val;
            legendre_val = (2 * im - 1) * x_in * legendre_val -
                           (im + m_val - 1) * legendre_val_mm;
            legendre_val = legendre_val / (im - m_val);
            legendre_val_mm = legendre_temp;
        }
        return legendre_val;
    }
}
References factorial(), and legendre().
Referenced by legendre(), and Ylm().
matmul_Cmpl2x2()
void matmul_Cmpl2x2 (ELPH_cmplx * mat1, ELPH_cmplx * mat2, ELPH_cmplx *restrict out)
Definition at line 424 of file numerical_func.c.
{
    out[0] = mat1[0] * mat2[0] + mat1[1] * mat2[2];
    out[1] = mat1[0] * mat2[1] + mat1[1] * mat2[3];
    out[2] = mat1[2] * mat2[0] + mat1[3] * mat2[2];
    out[3] = mat1[2] * mat2[1] + mat1[3] * mat2[3];
}
Referenced by SU2mat().
MatVec3f()
void MatVec3f (const ELPH_float * Mat, const ELPH_float * vec, const bool trans, ELPH_float *restrict out)
Definition at line 225 of file numerical_func.c.
{
    if (trans)
    {
        out[0] = Mat[0] * vec[0] + Mat[3] * vec[1] + Mat[6] * vec[2];
        out[1] = Mat[1] * vec[0] + Mat[4] * vec[1] + Mat[7] * vec[2];
        out[2] = Mat[2] * vec[0] + Mat[5] * vec[1] + Mat[8] * vec[2];
    }
    else
    {
        out[0] = Mat[0] * vec[0] + Mat[1] * vec[1] + Mat[2] * vec[2];
        out[1] = Mat[3] * vec[0] + Mat[4] * vec[1] + Mat[5] * vec[2];
        out[2] = Mat[6] * vec[0] + Mat[7] * vec[1] + Mat[8] * vec[2];
    }
}
Referenced by add_elphNonLocal(), add_ph_dyn_long_range_internal(), bz_expand(), compute_and_write_elphq(), dV_add_longrange(), dVlocq(), electronic_reps(), elphLocal(), generate_iBZ_kpts(), interpolation_driver(), long_range_2D_kernel(), long_range_3D_kernel(), rotate_dvscf(), rotate_eig_vecs(), and rotateGvecs().
normalize_Cmplx_vec()
void normalize_Cmplx_vec (ELPH_cmplx * vec, const ND_int n)
Definition at line 255 of file numerical_func.c.
{
    ELPH_float norm = sqrt(cabs(Cmplxdot(vec, vec, n)));
    if (norm < ELPH_EPS)
    {
        return;
    }
    for (ND_int i = 0; i < n; ++i)
    {
        vec[i] = vec[i] / norm;
    }
}
References Cmplxdot(), and ELPH_EPS.
reciprocal_vecs()
void reciprocal_vecs (const ELPH_float * lat_vec, ELPH_float *restrict blat)
Definition at line 279 of file numerical_func.c.
{
    /*
    a[:,i]  are latvecs
    b[:,i]  are blat
    result is multiplied with 2*pi
    */
    ELPH_float det = det3x3(lat_vec);
    if (det < ELPH_EPS)
    {
        error_msg("Inverting singular matrix");
    }
    det = 2 * ELPH_PI / det;
    blat[0] = (lat_vec[4] * lat_vec[8] - lat_vec[7] * lat_vec[5]) * det;
    blat[1] = (lat_vec[5] * lat_vec[6] - lat_vec[3] * lat_vec[8]) * det;
    blat[2] = (lat_vec[3] * lat_vec[7] - lat_vec[6] * lat_vec[4]) * det;
    blat[3] = (lat_vec[2] * lat_vec[7] - lat_vec[1] * lat_vec[8]) * det;
    blat[4] = (lat_vec[0] * lat_vec[8] - lat_vec[2] * lat_vec[6]) * det;
    blat[5] = (lat_vec[1] * lat_vec[6] - lat_vec[0] * lat_vec[7]) * det;
    blat[6] = (lat_vec[1] * lat_vec[5] - lat_vec[2] * lat_vec[4]) * det;
    blat[7] = (lat_vec[2] * lat_vec[3] - lat_vec[0] * lat_vec[5]) * det;
    blat[8] = (lat_vec[0] * lat_vec[4] - lat_vec[1] * lat_vec[3]) * det;
}
References det3x3(), ELPH_EPS, ELPH_PI, and error_msg.
Referenced by build_wigner_seitz_vectors(), and read_and_alloc_save_data().
simpson()
ELPH_float simpson (const ELPH_float * func_vals, const ELPH_float * dx, ND_int npts)
Definition at line 154 of file numerical_func.c.
{
    /*
    Compute the integral using simpson 1/3 rules i.e /int f(x) dx
    */
    if (npts < 3)
    {
        return 0;  // Need atleast 3 points . Return an error instead
    }
    ELPH_float sum = func_vals[0] * dx[0];
    /* Odd terms*/
    for (ND_int i = 1; i < npts - 1; i += 2)
    {
        sum += 4.0 * func_vals[i] * dx[i];
    }
    /* even terms*/
    for (ND_int i = 2; i < npts - 1; i += 2)
    {
        sum += 2.0 * func_vals[i] * dx[i];
    }
    if (npts % 2 != 0)
    {
        sum += func_vals[npts - 1] * dx[npts - 1];
    }
    else
    {
        sum -= func_vals[npts - 3] * dx[npts - 3] * 0.25;
        sum += func_vals[npts - 2] * dx[npts - 2];
        sum += func_vals[npts - 1] * dx[npts - 1] * 1.25;
    }
    return sum / 3.0;
}
Referenced by Vloc_Gspace().
swap_floats()
void swap_floats (ELPH_float * a, ELPH_float * b)
Definition at line 533 of file numerical_func.c.
{
    const ELPH_float c = *b;
    *b = *a;
    *a = c;
}
Referenced by transpose3x3f_inplace().
swap_ints()
void swap_ints (int * a, int * b)
Definition at line 526 of file numerical_func.c.
{
    const int c = *b;
    *b = *a;
    *a = c;
}
Referenced by compute_and_write_elphq().
transpose3x3f()
void transpose3x3f (const ELPH_float * inmat, ELPH_float *restrict outmat)
Definition at line 314 of file numerical_func.c.
{
    /* Transpose 3x3 matrix */
    outmat[0] = inmat[0];
    outmat[1] = inmat[3];
    outmat[2] = inmat[6];
    outmat[3] = inmat[1];
    outmat[4] = inmat[4];
    outmat[5] = inmat[7];
    outmat[6] = inmat[2];
    outmat[7] = inmat[5];
    outmat[8] = inmat[8];
}
Referenced by read_and_alloc_save_data().
transpose3x3f_inplace()
void transpose3x3f_inplace (ELPH_float * mat)
Definition at line 330 of file numerical_func.c.
{
    /* inplace Transpose 3x3 matrix */
    swap_floats(mat + 1, mat + 3);
    swap_floats(mat + 2, mat + 6);
    swap_floats(mat + 5, mat + 7);
}
References swap_floats().
Ylm()
ELPH_float Ylm (int l_val, int m_val, ELPH_float * vec)
Definition at line 96 of file numerical_func.c.
{
    /*
    Miguel A. Blanco, M. Flórez, M. Bermejo
    Evaluation of the rotation matrices in the basis of real spherical harmonics
    J. Mol. Struct. THEOCHEM 419, 19-27 (1997)
    */
    if (l_val < 0)
    {
        return 0.0;  // error
    }
    ELPH_float cost, phi;
    ELPH_float norm = sqrt(vec[0] * vec[0] + vec[1] * vec[1] + vec[2] * vec[2]);
    if (norm < ELPH_EPS)
    {
        if (l_val != 0)
        {
            return 0;
        }
        else
        {
            return 1.0 / sqrt(4 * ELPH_PI);
        }
    }
    cost = vec[2] / norm;  // z/r
    phi = atan2(vec[1], vec[0]);
    ELPH_float sh = 0.0;
    /* phi part*/
    if (m_val > 0)
    {
        sh = sqrt(2) * cos(m_val * phi);
    }
    else if (m_val < 0)
    {
        m_val = -m_val;
        sh = sqrt(2) * sin(m_val * phi);
    }
    else
    {
        sh = 1;  // 1 for m =0
    }
    /* Multiply with legendre polynomial */
    sh *= legendre(l_val, m_val, cost);
    /* Multiply with normalization factor*/
    sh *= sqrt(factorial(l_val - m_val) * (2 * l_val + 1) /
               (4 * ELPH_PI * factorial(l_val + m_val)));
    return sh;
}
References ELPH_EPS, ELPH_PI, factorial(), and legendre().
Referenced by add_elphNonLocal().