LetzElPhC: src/io/input_parser.c File Reference
input_parser.c File Reference
#include <mpi.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "common/dtypes.h"
#include "common/error.h"
#include "common/string_func.h"
#include "io.h"
#include "io/inih/ini.h"
Macros
#define READ_STR_LEN 600
Functions
static void Bcast_input_data (struct usr_input *input, int root, MPI_Comm comm)
static int handler (void *user, const char *section, const char *name, const char *value)
void init_usr_input (struct usr_input **input)
void free_usr_input (struct usr_input *input)
void read_input_file (const char *input_file, struct usr_input **input_data, MPI_Comm MPI_world_comm)
Macro Definition Documentation
READ_STR_LEN
#define READ_STR_LEN 600
Definition at line 13 of file input_parser.c.
Referenced by Bcast_input_data(), handler(), and init_usr_input().
Function Documentation
Bcast_input_data()
void Bcast_input_data (struct usr_input * input, int root, MPI_Comm comm) static
Definition at line 52 of file input_parser.c.
{
    int mpi_error;
    // all char * will be bcasted in one single call
    mpi_error =
        MPI_Bcast(input->save_dir, READ_STR_LEN * 3, MPI_CHAR, root, comm);
    MPI_error_msg(mpi_error);
    // ph_save_dir and kernel_str are also broadcasted when entire save_dir is
    // Bcasted
    mpi_error = MPI_Bcast(&input->nkpool, 1, MPI_INT, root, comm);
    MPI_error_msg(mpi_error);
    mpi_error = MPI_Bcast(&input->nqpool, 1, MPI_INT, root, comm);
    MPI_error_msg(mpi_error);
    mpi_error = MPI_Bcast(&input->start_bnd, 1, MPI_INT, root, comm);
    MPI_error_msg(mpi_error);
    mpi_error = MPI_Bcast(&input->end_bnd, 1, MPI_INT, root, comm);
    MPI_error_msg(mpi_error);
    mpi_error = MPI_Bcast(&input->kminusq, 1, MPI_C_BOOL, root, comm);
    MPI_error_msg(mpi_error);
}
References usr_input::end_bnd, usr_input::kminusq, MPI_error_msg, usr_input::nkpool, usr_input::nqpool, READ_STR_LEN, usr_input::save_dir, and usr_input::start_bnd.
Referenced by read_input_file().
free_usr_input()
void free_usr_input (struct usr_input * input)
Definition at line 46 of file input_parser.c.
{
    free(input->save_dir);
    free(input);
}
References usr_input::save_dir.
Referenced by elph_driver().
handler()
int handler (void * user, const char * section, const char * name, const char * value) static
Definition at line 78 of file input_parser.c.
{
    struct usr_input* inp = user;
    // check if value is just an empty string
    size_t nospace_len = 0;
    size_t val_len = strlen(value);
    for (size_t i = 0; i < val_len; ++i)
    {
        if (value[i] != ' ')
        {
            ++nospace_len;
        }
    }
    if (nospace_len == 0)
    {
        printf("Invalid input for %s ", name);
        error_msg("Invalid input");
    }
    if (strcmp(name, "nkpool") == 0)
    {
        inp->nkpool = atoi(value);
    }
    else if (strcmp(name, "nqpool") == 0)
    {
        inp->nqpool = atoi(value);
    }
    else if (strcmp(name, "start_bnd") == 0)
    {
        inp->start_bnd = atoi(value);
    }
    else if (strcmp(name, "end_bnd") == 0)
    {
        inp->end_bnd = atoi(value);
    }
    else if (strcmp(name, "save_dir") == 0)
    {
        strncpy_custom(inp->save_dir, value, READ_STR_LEN);
    }
    else if (strcmp(name, "ph_save_dir") == 0)
    {
        strncpy_custom(inp->ph_save_dir, value, READ_STR_LEN);
    }
    else if (strcmp(name, "kernel") == 0)
    {
        strncpy_custom(inp->kernel_str, value, READ_STR_LEN);
        lowercase_str(inp->kernel_str);
    }
    else if (strcmp(name, "convention") == 0)
    {
        if (strstr(value, "yambo"))
        {
            inp->kminusq = true;
        }
        else if (strstr(value, "standard"))
        {
            inp->kminusq = false;
        }
        else
        {
            error_msg(
                "Invalid value for convention in the input file."
                " Only yambo or standard are accepted.");
        }
    }
    else
    {
        error_msg("Invalid variable in input file.");
    }
    return 1;
}
References usr_input::end_bnd, error_msg, usr_input::kernel_str, usr_input::kminusq, lowercase_str(), usr_input::nkpool, usr_input::nqpool, usr_input::ph_save_dir, READ_STR_LEN, usr_input::save_dir, usr_input::start_bnd, and strncpy_custom().
Referenced by read_input_file().
init_usr_input()
void init_usr_input (struct usr_input ** input)
Definition at line 20 of file input_parser.c.
{
    // this function also sets defaults for the user input file
    *input = malloc(sizeof(struct usr_input));
    CHECK_ALLOC(*input);
    struct usr_input* inp = *input;
    inp->save_dir = calloc(READ_STR_LEN * 3, 1);
    CHECK_ALLOC(inp->save_dir);
    inp->ph_save_dir = inp->save_dir + READ_STR_LEN;
    inp->kernel_str = inp->save_dir + 2 * READ_STR_LEN;
    // defaults
    inp->nkpool = 1;
    inp->nqpool = 1;
    inp->start_bnd = 0;
    inp->end_bnd = 0;
    strncpy_custom(inp->save_dir, "SAVE", READ_STR_LEN);
    strncpy_custom(inp->ph_save_dir, "ph_save", READ_STR_LEN);
    strncpy_custom(inp->kernel_str, "dfpt", READ_STR_LEN);
    inp->kminusq = false;  // default is standard
}
References CHECK_ALLOC, usr_input::end_bnd, usr_input::kernel_str, usr_input::kminusq, usr_input::nkpool, usr_input::nqpool, usr_input::ph_save_dir, READ_STR_LEN, usr_input::save_dir, usr_input::start_bnd, and strncpy_custom().
Referenced by read_input_file().
read_input_file()
void read_input_file (const char * input_file, struct usr_input ** input_data, MPI_Comm MPI_world_comm)
Definition at line 154 of file input_parser.c.
{
    // input_data must be free outside
    init_usr_input(input_data);
    int mpi_world_rank, mpi_error;
    mpi_error = MPI_Comm_rank(MPI_world_comm, &mpi_world_rank);
    MPI_error_msg(mpi_error);
    if (mpi_world_rank == 0)
    {
        if (ini_parse(input_file, handler, *input_data) < 0)
        {
            error_msg("Cannot open input file.");
        }
    }
    // broad cast;
    Bcast_input_data(*input_data, 0, MPI_world_comm);
}
References Bcast_input_data(), error_msg, handler(), init_usr_input(), and MPI_error_msg.
Referenced by elph_driver().