LetzElPhC: src/common/ELPH_timers.h File Reference
ELPH_timers.h File Reference
Functions
void init_ELPH_clocks (void)
void ELPH_start_clock (const char *str)
void ELPH_stop_clock (const char *str)
void cleanup_ELPH_clocks (void)
void print_ELPH_clock_summary (void)
Function Documentation
cleanup_ELPH_clocks()
void cleanup_ELPH_clocks (void)
Definition at line 88 of file ELPH_timers.c.
{
    // cleanup all the clock info.
    // nothing should be called after this.
    map_deinit(&timer_map);
}
Referenced by elph_driver(), and interpolation_driver().
ELPH_start_clock()
void ELPH_start_clock (const char * str)
Definition at line 34 of file ELPH_timers.c.
{
    if (!str)
    {
        return;
    }
    double tic = MPI_Wtime();
    // check if this tag already exists
    struct ELPH_timer *etime = map_get(&timer_map, str);
    size_t count_tmp = 0;
    if (etime)
    {
        tic -= etime->Wtime;
        count_tmp = etime->count;
    }
    tic = -tic;
    struct ELPH_timer time_set;
    time_set.count = count_tmp;
    time_set.Wtime = tic;
    map_set(&timer_map, str, time_set);
}
References ELPH_timer::count, and ELPH_timer::Wtime.
Referenced by add_elphNonLocal(), add_ph_dyn_long_range_internal(), build_wigner_seitz_vectors(), create_vlocg_table(), dV_add_longrange(), dVlocq(), electronic_reps(), elph_q_rotate(), elphLocal(), fft_q2R(), fft_R2q_dvscf(), fft_R2q_dyn(), map_t(), read_and_alloc_save_data(), and rotate_eig_vecs().
ELPH_stop_clock()
void ELPH_stop_clock (const char * str)
Definition at line 59 of file ELPH_timers.c.
{
    if (!str)
    {
        return;
    }
    double tok = MPI_Wtime();
    // check if this tag already exists
    struct ELPH_timer *etime = map_get(&timer_map, str);
    size_t count_tmp = 0;
    if (etime)
    {
        tok += etime->Wtime;
        count_tmp = etime->count + 1;
    }
    else
    {
        // clock does not exist
        return;
    }
    struct ELPH_timer time_set;
    time_set.count = count_tmp;
    time_set.Wtime = tok;
    map_set(&timer_map, str, time_set);
}
References ELPH_timer::count, and ELPH_timer::Wtime.
Referenced by add_elphNonLocal(), add_ph_dyn_long_range_internal(), build_wigner_seitz_vectors(), create_vlocg_table(), dV_add_longrange(), dVlocq(), electronic_reps(), elph_q_rotate(), elphLocal(), fft_q2R(), fft_R2q_dvscf(), fft_R2q_dyn(), print_ELPH_clock_summary(), read_and_alloc_save_data(), and rotate_eig_vecs().
init_ELPH_clocks()
void init_ELPH_clocks (void)
Referenced by elph_driver(), and interpolation_driver().
print_ELPH_clock_summary()
void print_ELPH_clock_summary (void)
Definition at line 95 of file ELPH_timers.c.
{
    // first end the total time
    ELPH_stop_clock("Total time");
    const char *key;
    map_iter_t iter = map_iter(&timer_map);
    fputs("\n", stdout);
    fputs("===================== Wall times =====================\n", stdout);
    fprintf(stdout, "%-20s  :    Wtime (s)     (  counts  )\n",
            "Function name");
    fputs("------------------------------------------------------\n", stdout);
    while ((key = map_next(&timer_map, &iter)))
    {
        if (0 == strcmp(key, "Total time"))
        {
            continue;
        }
        struct ELPH_timer *etime = map_get(&timer_map, key);
        fprintf(stdout, "%-20s  : %12.4f     ( %8zu )\n", key, etime->Wtime,
                etime->count);
    }
    fputs("------------------------------------------------------\n", stdout);
    // print total time
    key = "Total time";
    fprintf(stdout, "%-20s  : %12.4f s.\n", key,
            map_get(&timer_map, key)->Wtime);
    fputs("\n", stdout);
}
References ELPH_timer::count, ELPH_stop_clock(), and ELPH_timer::Wtime.
Referenced by elph_driver(), and interpolation_driver().