LetzElPhC: src/elph/elph.h File Reference
elph.h File Reference
#include <mpi.h>
#include <stdbool.h>
#include "common/dtypes.h"
#include "elphC.h"
Functions
void elph_driver (const char *ELPH_input_file, enum ELPH_dft_code dft_code, MPI_Comm comm_world)
void compute_and_write_elphq (struct WFC *wfcs, struct Lattice *lattice, struct Pseudo *pseudo, struct Phonon *phonon, const ND_int iqpt, ELPH_cmplx *eigVec, ELPH_cmplx *dVscfq, const int ncid_elph, const int varid_elph, const int ncid_dmat, const int varid_dmat, const bool non_loc, const bool kminusq, const struct ELPH_MPI_Comms *Comm)
void compute_and_write_dmats (const char *file_name, const struct WFC *wfcs, const struct Lattice *lattice, const ND_int nph_sym, const struct symmetry *sym_data, const struct ELPH_MPI_Comms *Comm)
void init_kernel (struct kernel_info *kernel)
void set_kernel (const char *kernel_str, struct kernel_info *kernel)
Function Documentation
compute_and_write_dmats()
void compute_and_write_dmats (const char * file_name, const struct WFC * wfcs, const struct Lattice * lattice, const ND_int nph_sym, const struct symmetry * sym_data, const struct ELPH_MPI_Comms * Comm)
Definition at line 20 of file compute_dmats.c.
{
    ND_int nk_totalBZ = lattice->nkpts_BZ;
    ELPH_cmplx* Dkmn_rep_ptr = NULL;
    int ncid, varid, nc_err;
    size_t startp[6] = {0, 0, 0, 0, 0, 0};
    size_t countp[6] = {1, 1, lattice->nspin, lattice->nbnds, lattice->nbnds,
                        2};
    ND_int nk_chunk_size = NC4_DEFAULT_CHUCK_KB * 1024;  // now this is in bytes
    // scale with complex number size to get the number of elements
    nk_chunk_size /=
        (sizeof(ELPH_cmplx) * lattice->nspin * lattice->nbnds * lattice->nbnds);
    // chuck the varaible elph_mat with atmost default size
    if (nk_chunk_size == 0)
    {
        nk_chunk_size = 1;
    }
    else if (nk_chunk_size > nk_totalBZ)
    {
        nk_chunk_size = nk_totalBZ;
    }
    if (Comm->commK_rank == 0)
    {
        // we overwrite any existing file
        if ((nc_err = nc_create_par(file_name, NC_NETCDF4 | NC_CLOBBER,
                                    Comm->commR, MPI_INFO_NULL, &ncid)))
        {
            fprintf(stderr, "Error creating Dmat file");
            ERR(nc_err);
        }
        // set no fill mode (to avoid writting twice)
        if ((nc_err = ncsetfill(ncid, NC_NOFILL)))
        {
            fprintf(stderr, "Error setting nc_fill to dmat file.");
            ERR(nc_err);
        }
        def_ncVar(ncid, &varid, 6, ELPH_NC4_IO_FLOAT,
                  (ND_int[]){nph_sym, nk_totalBZ, lattice->nspin,
                             lattice->nbnds, lattice->nbnds, 2},
                  "Dmats",
                  (char*[]){"nsym_ph", "nkpts", "nspin", "Rk_band", "k_band",
                            "re_im"},
                  (size_t[]){1, nk_chunk_size, lattice->nspin, lattice->nbnds,
                             lattice->nbnds, 2});
        // Make the access INDEPENDENT as not all can call the put_var function
        // simultaneously
        if ((nc_err = nc_var_par_access(ncid, varid, NC_INDEPENDENT)))
        {
            ERR(nc_err);
        }
        Dkmn_rep_ptr = calloc(lattice->nspin * lattice->nbnds * lattice->nbnds,
                              sizeof(ELPH_cmplx));
        CHECK_ALLOC(Dkmn_rep_ptr);
    }
    // for computation of Dmats, we use all the nodes
    // ("nsym", "nk", "nspin", "nbndb", "nbnda")
    ND_int dmat_shift;
    ND_int ndmats =
        distribute_to_grps(nph_sym * nk_totalBZ, Comm->nqpools * Comm->nkpools,
                           Comm->commW_rank / Comm->commK_size, &dmat_shift);
    // start the progress bar for dmats
    struct progress_bar pbar[1];
    start_progressbar(pbar, Comm->commW_rank, ndmats);
    for (ND_int idmat = 0; idmat < ndmats; ++idmat)
    {
        ND_int isym = (idmat + dmat_shift) / nk_totalBZ;
        ND_int ikBZ = (idmat + dmat_shift) % nk_totalBZ;
        startp[0] = isym;
        startp[1] = ikBZ;
        // compute the dmats
        electronic_reps(wfcs, lattice, sym_data[isym].Rmat, sym_data[isym].tau,
                        sym_data[isym].time_rev, ikBZ, Dkmn_rep_ptr, Comm);
        if (Comm->commK_rank == 0)
        {
            // write data to file
            if ((nc_err =
                     nc_put_vara(ncid, varid, startp, countp, Dkmn_rep_ptr)))
            {
                ERR(nc_err);
            }
        }
        // update the progress bar
        print_progressbar(pbar);
    }
    if (Comm->commK_rank == 0)
    {
        free(Dkmn_rep_ptr);
        if ((nc_err = nc_close(ncid)))
        {
            ERR(nc_err);
        }
    }
}
References CHECK_ALLOC, ELPH_MPI_Comms::commK_rank, ELPH_MPI_Comms::commK_size, ELPH_MPI_Comms::commR, ELPH_MPI_Comms::commW_rank, def_ncVar(), distribute_to_grps(), electronic_reps(), ELPH_NC4_IO_FLOAT, ERR, Lattice::nbnds, NC4_DEFAULT_CHUCK_KB, ELPH_MPI_Comms::nkpools, Lattice::nkpts_BZ, ELPH_MPI_Comms::nqpools, Lattice::nspin, print_progressbar(), and start_progressbar().
Referenced by elph_driver().
compute_and_write_elphq()
void compute_and_write_elphq (struct WFC * wfcs, struct Lattice * lattice, struct Pseudo * pseudo, struct Phonon * phonon, const ND_int iqpt, ELPH_cmplx * eigVec, ELPH_cmplx * dVscfq, const int ncid_elph, const int varid_elph, const int ncid_dmat, const int varid_dmat, const bool non_loc, const bool kminusq, const struct ELPH_MPI_Comms * Comm)
Definition at line 20 of file compute_elph_matq.c.
{
    /*
    dVscf -> (nmodes,nmag,Nx,Ny,Nz)
    ((k, nmodes, nspin, nbands, nbands))
    */
    /* distribute k points */
    int mpi_error;
    const ND_int nk_totalBZ = lattice->nkpts_BZ;
    const ELPH_float* qpt = phonon->qpts_iBZ + iqpt * 3;
    ND_int qpos = 0;  // positon of this iBZ qpoint in full q point list
    for (ND_int i = 0; i < iqpt; ++i)
    {
        qpos += phonon->nqstar[i];
    }
    // sanity check
    if (phonon->qmap[2 * qpos] != iqpt || phonon->qmap[2 * qpos + 1] != 0)
    {
        error_msg("Qpoint in iBZ cannot be traced in phonon qmap");
    }
    ND_int kshift;
    ND_int nk_this_pool =
        distribute_to_grps(nk_totalBZ, Comm->nkpools,
                           Comm->commQ_rank / Comm->commK_size, &kshift);
    if (nk_this_pool < 1)
    {
        error_msg(
            "There are no kpoints in some cpus, Make sure nkpool < # of "
            "kpoints in full BZ.");
    }
    /* get the k point indices and symmetries */
    int* kmap = lattice->kmap;
    int* KplusQidxs = malloc(nk_totalBZ * sizeof(int));
    CHECK_ALLOC(KplusQidxs);
    ELPH_float qpt_tmp[3];
    memcpy(qpt_tmp, qpt, sizeof(ELPH_float) * 3);
    // incase if we want yambo convention
    if (kminusq)
    {
        for (int xi = 0; xi < 3; ++xi)
        {
            qpt_tmp[xi] = -qpt_tmp[xi];
        }
    }
    get_KplusQ_idxs(nk_totalBZ, lattice->kpt_fullBZ_crys, qpt_tmp, KplusQidxs);
    ND_int nbnds = lattice->nbnds;
    ND_int nmodes = lattice->nmodes;
    ELPH_cmplx* elph_kq_mn = NULL;
    if (Comm->commK_rank == 0)
    {
        elph_kq_mn =
            calloc(nbnds * nbnds * lattice->nspin * nmodes, sizeof(ELPH_cmplx));
        CHECK_ALLOC(elph_kq_mn);
    }
    /* Now Compute elph-matrix elements for each kpoint */
    size_t startp[7] = {0, 0, 0, 0, 0, 0, 0};
    size_t countp[7] = {1, 1, nmodes, lattice->nspin, nbnds, nbnds, 2};
    ELPH_cmplx* gSq_buff = NULL;
    ELPH_cmplx* D_mat_l = NULL;
    ELPH_cmplx* D_mat_r = NULL;
    if (Comm->commK_rank == 0)
    {
        gSq_buff =
            calloc(nbnds * nbnds * lattice->nspin * nmodes, sizeof(ELPH_cmplx));
        CHECK_ALLOC(gSq_buff);
        D_mat_l = calloc(nbnds * nbnds * lattice->nspin, sizeof(ELPH_cmplx));
        CHECK_ALLOC(D_mat_l);
        D_mat_r = calloc(nbnds * nbnds * lattice->nspin, sizeof(ELPH_cmplx));
        CHECK_ALLOC(D_mat_r);
    }
    // start the progress bar
    struct progress_bar pbar[1];
    start_progressbar(pbar, Comm->commW_rank, nk_this_pool);
    // compute electron-phonon matrix elements for each kpoint
    for (ND_int ii = 0; ii < nk_this_pool; ++ii)
    {
        /* compute the global k index */
        ND_int i = kshift + ii;
        int idx_k = i;
        int idx_kq = KplusQidxs[i];
        if (kminusq)
        {
            swap_ints(&idx_k, &idx_kq);
        }
        int ik = kmap[2 * idx_k];
        int ksym = kmap[2 * idx_k + 1];
        int ikq = kmap[2 * idx_kq];
        int kqsym = kmap[2 * idx_kq + 1];
        elphLocal(qpt, wfcs, lattice, ikq, ik, kqsym, ksym, dVscfq, Comm,
                  elph_kq_mn);
        /* add the non local part elements */
        // WARNING : non local must be added after elphLocal else U.B
        if (non_loc)
        {
            add_elphNonLocal(wfcs, lattice, pseudo, ikq, ik, kqsym, ksym,
                             eigVec, elph_kq_mn, Comm);
        }
        startp[0] = qpos;
        startp[1] = i;
        int nc_err;
        if (Comm->commK_rank == 0)
        {
            if ((nc_err = nc_put_vara(ncid_elph, varid_elph, startp, countp,
                                      elph_kq_mn)))
            {
                ERR(nc_err);
            }
        }
        // expand the el-ph matrix elements in full BZ
        const ELPH_float* kpt_BZ = lattice->kpt_fullBZ + 3 * i;
        // only master node does this
        if (Comm->commK_rank == 0)
        {
            for (ND_int istar = 1; istar < phonon->nqstar[iqpt]; ++istar)
            {
                ND_int qpos_star = qpos + istar;
                // get the symmetry
                int istar_symm = phonon->qmap[2 * qpos_star + 1];
                size_t D_mat_sp[6] = {istar_symm, idx_kq, 0, 0, 0, 0};
                size_t D_mat_cp[6] = {
                    1, 1, lattice->nspin, lattice->nbnds, lattice->nbnds, 2};
                // read D_mats //const int ncid_dmat, const int varid_dmat,
                if ((nc_err = nc_get_vara(ncid_dmat, varid_dmat, D_mat_sp,
                                          D_mat_cp, D_mat_l)))
                {  // k + q
                    ERR(nc_err);
                }
                D_mat_sp[1] = idx_k;
                if ((nc_err = nc_get_vara(ncid_dmat, varid_dmat, D_mat_sp,
                                          D_mat_cp, D_mat_r)))
                {  // k
                    ERR(nc_err);
                }
                // gSq_buff
                elph_q_rotate(D_mat_l, elph_kq_mn, D_mat_r, lattice,
                              phonon->ph_syms[istar_symm].time_rev, gSq_buff);
                ELPH_float Sk_crys[3];
                ELPH_float Sk_cart[3];
                MatVec3f(phonon->ph_syms[istar_symm].Rmat, kpt_BZ, false,
                         Sk_cart);
                // convert to crsytal units
                MatVec3f(lattice->alat_vec, Sk_cart, true, Sk_crys);
                // now get the indices of S*k
                ND_int idx_Sk = find_kidx_in_list(
                    lattice->nkpts_BZ, lattice->kpt_fullBZ_crys, Sk_crys);
                if (idx_Sk < 0)
                {
                    error_msg(
                        "Unable to to find S*k index "
                        "This is due to incommenserate k and q grids.");
                }
                startp[0] = qpos_star;
                startp[1] = idx_Sk;
                // Write it for Sq and Sk point
                if ((nc_err = nc_put_vara(ncid_elph, varid_elph, startp, countp,
                                          gSq_buff)))
                {
                    ERR(nc_err);
                }
            }
        }
        mpi_error = MPI_Barrier(Comm->commK);
        MPI_error_msg(mpi_error);
        // update the progress bar
        print_progressbar(pbar);
    }
    // free wfc buffers
    if (Comm->commK_rank == 0)
    {
        free(elph_kq_mn);
        free(gSq_buff);
        free(D_mat_l);
        free(D_mat_r);
    }
    free(KplusQidxs);
}
References add_elphNonLocal(), Lattice::alat_vec, CHECK_ALLOC, ELPH_MPI_Comms::commK, ELPH_MPI_Comms::commK_rank, ELPH_MPI_Comms::commK_size, ELPH_MPI_Comms::commQ_rank, ELPH_MPI_Comms::commW_rank, distribute_to_grps(), elph_q_rotate(), elphLocal(), ERR, error_msg, find_kidx_in_list(), get_KplusQ_idxs(), Lattice::kmap, Lattice::kpt_fullBZ, Lattice::kpt_fullBZ_crys, MatVec3f(), MPI_error_msg, Lattice::nbnds, ELPH_MPI_Comms::nkpools, Lattice::nkpts_BZ, Lattice::nmodes, Phonon::nqstar, Lattice::nspin, Phonon::ph_syms, print_progressbar(), Phonon::qmap, Phonon::qpts_iBZ, symmetry::Rmat, start_progressbar(), swap_ints(), and symmetry::time_rev.
Referenced by elph_driver().
elph_driver()
void elph_driver (const char * ELPH_input_file, enum ELPH_dft_code dft_code, MPI_Comm comm_world)
Definition at line 27 of file elph_driver.c.
{
    struct usr_input* input_data;
    // start the clocks
    init_ELPH_clocks();
    //
    // read the input file
    read_input_file(ELPH_input_file, &input_data, comm_world);
    // Note input parameters are broadcasted internally
    // All the parameters in input_data must be available for all cpus in
    // comm_world
    struct kernel_info* kernel = malloc(sizeof(struct kernel_info));
    // initate the kernel with default
    init_kernel(kernel);
    // set the kernel
    set_kernel(input_data->kernel_str, kernel);
    struct ELPH_MPI_Comms* mpi_comms = malloc(sizeof(struct ELPH_MPI_Comms));
    CHECK_ALLOC(mpi_comms);
    create_parallel_comms(input_data->nqpool, input_data->nkpool, comm_world,
                          mpi_comms);
    // print logo and stated message
    print_ELPH_logo(mpi_comms->commW_rank, stdout);
    print_info_msg(mpi_comms->commW_rank,
                   "********** Program started **********");
    print_input_info(input_data->save_dir, input_data->ph_save_dir,
                     input_data->kernel_str, input_data->kminusq, dft_code,
                     mpi_comms);
    struct Lattice* lattice = malloc(sizeof(struct Lattice));
    CHECK_ALLOC(lattice);
    init_lattice_type(lattice);
    struct Pseudo* pseudo = malloc(sizeof(struct Pseudo));
    CHECK_ALLOC(pseudo);
    init_Pseudo_type(pseudo);
    struct Phonon* phonon = malloc(sizeof(struct Phonon));
    CHECK_ALLOC(phonon);
    init_phonon_type(phonon);
    struct WFC* wfcs;
    // read the SAVE data and phonon related data.
    read_and_alloc_save_data(input_data->save_dir, mpi_comms,
                             input_data->start_bnd, input_data->end_bnd, &wfcs,
                             input_data->ph_save_dir, lattice, pseudo, phonon,
                             dft_code);
    // print info about lattice and phonons
    print_lattice_info(mpi_comms, lattice);
    print_phonon_info(mpi_comms, phonon);
    //======= Now start the real computation =========
    // a) COmpute the D_mats and store them in the netcdf file
    // ============= Dmats =====================
    print_info_msg(mpi_comms->commW_rank, "");
    print_info_msg(mpi_comms->commW_rank,
                   "=== Computing Dmats for phonon symmetries ===");
    compute_and_write_dmats("ndb.Dmats", wfcs, lattice, phonon->nph_sym,
                            phonon->ph_syms, mpi_comms);
    // b) Compute elph
    // ============= ELPH iBZ computation =============
    ND_int nmodes = lattice->nmodes;
    ND_int nfft_loc =
        lattice->fft_dims[0] * lattice->fft_dims[1] * lattice->nfftz_loc;
    ELPH_cmplx* eigVec = malloc(sizeof(ELPH_cmplx) * nmodes * nmodes);
    //(nmodes,nmodes) // buffer to store eigen vectors
    CHECK_ALLOC(eigVec);
    ELPH_cmplx* dVscf =
        malloc(sizeof(ELPH_cmplx) * nmodes * lattice->nmag * nfft_loc);
    // (nmodes,nmag,Nx,Ny,Nz) // bufffer to store dVscf
    CHECK_ALLOC(dVscf);
    ELPH_float* omega_ph = malloc(sizeof(ELPH_float) * nmodes);
    // buffer for storing phonon freq
    CHECK_ALLOC(omega_ph);
    int ncid_elph, ncid_dmat, nc_err;
    int varid_eig, varid_elph, varid_omega, varid_dmat;
    // Define netcdf variables
    if (mpi_comms->commK_rank == 0)
    {
        // open Dmat file
        if ((nc_err = nc_open_par("ndb.Dmats", NC_NOWRITE, mpi_comms->commR,
                                  MPI_INFO_NULL, &ncid_dmat)))
        {
            ERR(nc_err);
        }
        // get dmat var id for dmats
        if ((nc_err = nc_inq_varid(ncid_dmat, "Dmats", &varid_dmat)))
        {
            ERR(nc_err);
        }
        size_t Dmat_counts[6] = {0, 0, 0, 0, 0, 0};
        // Make a no-op call to nc_get_vara to avoid deadlocks in some
        // suitiations. This happens when a procces doesnot make atleast
        // single read call (for ex when qpool = qiBZ)
        if ((nc_err = nc_get_vara(ncid_dmat, varid_dmat, Dmat_counts,
                                  Dmat_counts, NULL)))
        {
            ERR(nc_err);
        }
        // create elph file. Note: we overwrite any existing file
        if ((nc_err =
                 nc_create_par("ndb.elph", NC_NETCDF4 | NC_CLOBBER,
                               mpi_comms->commR, MPI_INFO_NULL, &ncid_elph)))
        {
            fprintf(stderr, "Error creating ndb.elph file.");
            ERR(nc_err);
        }
        // set no fill mode (to avoid writting twice)
        if ((nc_err = ncsetfill(ncid_elph, NC_NOFILL)))
        {
            fprintf(stderr, "Error setting nc_fill to ndb.elph file.");
            ERR(nc_err);
        }
        def_ncVar(ncid_elph, &varid_eig, 5, ELPH_NC4_IO_FLOAT,
                  (ND_int[]){phonon->nq_BZ, nmodes, nmodes / 3, 3, 2},
                  "POLARIZATION_VECTORS",
                  (char*[]){"nq", "nmodes", "atom", "pol", "re_im"}, NULL);
        def_ncVar(ncid_elph, &varid_omega, 2, ELPH_NC4_IO_FLOAT,
                  (ND_int[]){phonon->nq_BZ, nmodes}, "FREQ",
                  (char*[]){"nq", "nmodes"}, NULL);
        ND_int nk_chunk_size =
            NC4_DEFAULT_CHUCK_KB * 1024;  // now this is in bytes
        // scale with complex number size to get the number of elements
        nk_chunk_size /= (sizeof(ELPH_cmplx) * nmodes * lattice->nspin *
                          lattice->nbnds * lattice->nbnds);
        // chuck the varaible elph_mat with atmost default size
        if (nk_chunk_size == 0)
        {
            nk_chunk_size = 1;
        }
        else if (nk_chunk_size > lattice->nkpts_BZ)
        {
            nk_chunk_size = lattice->nkpts_BZ;
        }
        def_ncVar(ncid_elph, &varid_elph, 7, ELPH_NC4_IO_FLOAT,
                  (ND_int[]){phonon->nq_BZ, lattice->nkpts_BZ, nmodes,
                             lattice->nspin, lattice->nbnds, lattice->nbnds, 2},
                  "elph_mat",
                  (char*[]){"nq", "nk", "nmodes", "nspin", "initial_band",
                            "final_band_PH_abs", "re_im"},
                  (size_t[]){1, nk_chunk_size, nmodes, lattice->nspin,
                             lattice->nbnds, lattice->nbnds, 2});
    }
    ELPH_cmplx* eig_Sq = NULL;
    if (mpi_comms->commQ_rank == 0)
    {
        eig_Sq = calloc(nmodes * nmodes, sizeof(ELPH_cmplx));
        CHECK_ALLOC(eig_Sq);
    }
    print_info_msg(mpi_comms->commW_rank,
                   "=== Computing Electron-phonon matrix elements ===");
    print_info_msg(mpi_comms->commW_rank, "");
    for (ND_int iqpt = 0; iqpt < phonon->nq_iBZ_loc; ++iqpt)
    {
        print_info_msg(mpi_comms->commW_rank, "### q-point : %d/%d",
                       (int)(iqpt + 1), (int)phonon->nq_iBZ_loc);
        ND_int iqpt_iBZg = iqpt + phonon->nq_shift;
        // read dynamical matrix and dvscf for the iBZ qpt
        if (dft_code == DFT_CODE_QE)
        {
            ELPH_cmplx* dvscf_read = NULL;
            if (kernel->screening == ELPH_DFPT_SCREENING)
            {
                dvscf_read = dVscf;
            }
            else
            {
                // zero out the buffer. This is must !
                ND_int dvscf_num = nmodes * lattice->nmag * nfft_loc;
                for (ND_int ix = 0; ix < dvscf_num; ++ix)
                {
                    dVscf[ix] = 0.0;
                }
            }
            //
            get_dvscf_dyn_qe(input_data->ph_save_dir, lattice, iqpt_iBZg,
                             eigVec, dvscf_read, omega_ph, mpi_comms);
            // qe dvscf only contains dV_Ha + dV_xc, we need to add the local
            // part of pseudo
        }
        else
        {
            error_msg("Currently only quantum espresso supported");
        }
        // local part
        ELPH_cmplx* Vlocr = malloc(sizeof(ELPH_cmplx) * nmodes * nfft_loc);
        // buffer to store local part of the pseudo potential
        CHECK_ALLOC(Vlocr);
        //
        // compute the local part of the bare
        dVlocq(phonon->qpts_iBZ + iqpt_iBZg * 3, lattice, pseudo, eigVec, Vlocr,
               mpi_comms->commK);
        if (dft_code == DFT_CODE_QE)
        {
            add_dvscf_qe(dVscf, Vlocr,
                         lattice);  // add bare local to induce part
        }
        else
        {
            error_msg("Currently only quantum espresso supported");
        }
        free(Vlocr);
        // free the local part buffer
        ND_int qpos = 0;  // positon of this iBZ qpoint in full q point list
        for (ND_int i = 0; i < iqpt_iBZg; ++i)
        {
            qpos += phonon->nqstar[i];
        }
        // write eigen vectors and frequencies
        if (mpi_comms->commQ_rank == 0)
        {
            size_t startp[5] = {qpos, 0, 0, 0, 0};
            size_t countp[5] = {1, nmodes, nmodes / 3, 3, 2};
            if ((nc_err =
                     nc_put_vara(ncid_elph, varid_eig, startp, countp, eigVec)))
            {
                ERR(nc_err);
            }
            if ((nc_err = nc_put_vara(ncid_elph, varid_omega, startp, countp,
                                      omega_ph)))
            {
                ERR(nc_err);
            }
            // write down the rotate eigen vectors;
            for (ND_int istar = 1; istar < phonon->nqstar[iqpt_iBZg]; ++istar)
            {
                ND_int qpos_star = qpos + istar;
                struct symmetry* sym_rot =
                    phonon->ph_syms + phonon->qmap[2 * qpos_star + 1];
                rotate_eig_vecs(sym_rot, lattice,
                                phonon->qpts_iBZ + iqpt_iBZg * 3, eigVec,
                                eig_Sq);
                //
                startp[0] = qpos_star;
                if ((nc_err = nc_put_vara(ncid_elph, varid_eig, startp, countp,
                                          eig_Sq)))
                {
                    ERR(nc_err);
                }
                if ((nc_err = nc_put_vara(ncid_elph, varid_omega, startp,
                                          countp, omega_ph)))
                {
                    ERR(nc_err);
                }
                //
            }
        }
        // Now compute and write the electron-phonon matrix elements
        compute_and_write_elphq(wfcs, lattice, pseudo, phonon, iqpt_iBZg,
                                eigVec, dVscf, ncid_elph, varid_elph, ncid_dmat,
                                varid_dmat, kernel->non_loc,
                                input_data->kminusq, mpi_comms);
    }
    free(eig_Sq);
    if (mpi_comms->commK_rank == 0)
    {
        // close files
        if ((nc_err = nc_close(ncid_elph)))
        {
            ERR(nc_err);
        }
        if ((nc_err = nc_close(ncid_dmat)))
        {
            ERR(nc_err);
        }
    }
    // finally write some basic info to ndb.elph file (only master node writes
    // it)
    if (mpi_comms->commW_rank == 0)
    {
        if ((nc_err = nc_open("ndb.elph", NC_WRITE, &ncid_elph)))
        {
            ERR(nc_err);
        }
        char convention_str[32];
        strcpy(convention_str, "standard");
        if (input_data->kminusq)
        {
            strcpy(convention_str, "yambo");
        }
        write_basic_data(ncid_elph, lattice, phonon, input_data->kernel_str,
                         convention_str);
        if ((nc_err = nc_close(ncid_elph)))
        {
            ERR(nc_err);
        }
    }
    int World_rank_tmp = mpi_comms->commW_rank;
    // ELPH_cmplx Ry2Ha = pow(2,-1.5);
    free(omega_ph);
    free(eigVec);
    free(dVscf);
    // cleanup
    free(kernel);
    free_usr_input(input_data);
    free_save_data(wfcs, lattice, pseudo, phonon);
    free(lattice);
    free(pseudo);
    free(phonon);
    free_parallel_comms(mpi_comms);
    free(mpi_comms);
    fftw_fun(cleanup)();
    // print the clocks
    if (0 == World_rank_tmp)
    {
        print_ELPH_clock_summary();
    }
    // cleanup the clocks
    cleanup_ELPH_clocks();
    // done with the calculation
    print_info_msg(World_rank_tmp, "********** Program ended **********");
}
References add_dvscf_qe(), CHECK_ALLOC, cleanup_ELPH_clocks(), ELPH_MPI_Comms::commK, ELPH_MPI_Comms::commK_rank, ELPH_MPI_Comms::commQ_rank, ELPH_MPI_Comms::commR, ELPH_MPI_Comms::commW_rank, compute_and_write_dmats(), compute_and_write_elphq(), create_parallel_comms(), def_ncVar(), DFT_CODE_QE, dVlocq(), ELPH_DFPT_SCREENING, ELPH_NC4_IO_FLOAT, usr_input::end_bnd, ERR, error_msg, Lattice::fft_dims, fftw_fun, free_parallel_comms(), free_save_data(), free_usr_input(), init_ELPH_clocks(), init_kernel(), init_lattice_type(), init_phonon_type(), init_Pseudo_type(), usr_input::kernel_str, usr_input::kminusq, Lattice::nbnds, NC4_DEFAULT_CHUCK_KB, Lattice::nfftz_loc, usr_input::nkpool, Lattice::nkpts_BZ, Lattice::nmag, Lattice::nmodes, kernel_info::non_loc, Phonon::nph_sym, Phonon::nq_BZ, Phonon::nq_iBZ_loc, Phonon::nq_shift, usr_input::nqpool, Phonon::nqstar, Lattice::nspin, usr_input::ph_save_dir, Phonon::ph_syms, print_ELPH_clock_summary(), print_ELPH_logo(), print_info_msg(), print_input_info(), print_lattice_info(), print_phonon_info(), Phonon::qmap, Phonon::qpts_iBZ, read_and_alloc_save_data(), read_input_file(), rotate_eig_vecs(), usr_input::save_dir, kernel_info::screening, set_kernel(), usr_input::start_bnd, and write_basic_data().
Referenced by main().
init_kernel()
void init_kernel (struct kernel_info * kernel)
Definition at line 10 of file set_kernel.c.
{
    strcpy(kernel->name_str, "dfpt");
    kernel->bare_loc = true;
    kernel->non_loc = true;
    kernel->screening = ELPH_DFPT_SCREENING;
}
References kernel_info::bare_loc, ELPH_DFPT_SCREENING, kernel_info::name_str, kernel_info::non_loc, and kernel_info::screening.
Referenced by elph_driver().
set_kernel()
void set_kernel (const char * kernel_str, struct kernel_info * kernel)
Definition at line 18 of file set_kernel.c.
{
    size_t name_str_size = sizeof(kernel->name_str) - 1;
    kernel->name_str[name_str_size] = '\0';
    strncpy_custom(kernel->name_str, kernel_str, name_str_size);
    if (!strcmp(kernel_str, "dfpt"))
    {
        kernel->bare_loc = true;
        kernel->non_loc = true;
        kernel->screening = ELPH_DFPT_SCREENING;
    }
    else if (!strcmp(kernel_str, "dfpt_local"))
    {
        kernel->bare_loc = true;
        kernel->non_loc = false;
        kernel->screening = ELPH_DFPT_SCREENING;
    }
    else if (!strcmp(kernel_str, "bare"))
    {
        kernel->bare_loc = true;
        kernel->non_loc = true;
        kernel->screening = ELPH_NO_SCREENING;
    }
    else if (!strcmp(kernel_str, "bare_local"))
    {
        kernel->bare_loc = true;
        kernel->non_loc = false;
        kernel->screening = ELPH_NO_SCREENING;
    }
    else
    {
        error_msg("invalid value for kernel in the input file");
    }
}
References kernel_info::bare_loc, ELPH_DFPT_SCREENING, ELPH_NO_SCREENING, error_msg, kernel_info::name_str, kernel_info::non_loc, kernel_info::screening, and strncpy_custom().
Referenced by elph_driver().