LetzElPhC: src/common/init_dtypes.h File Reference
init_dtypes.h File Reference
#include "dtypes.h"
#include "elphC.h"
Functions
void init_lattice_type (struct Lattice *lattice)
void init_phonon_type (struct Phonon *phonon)
void init_Vloc_table_type (struct Vloc_table *vloc_tab)
void init_local_pseudo_type (struct local_pseudo *lpseudo)
void init_Pseudo_type (struct Pseudo *pseudo)
Function Documentation
init_lattice_type()
void init_lattice_type (struct Lattice * lattice)
Definition at line 17 of file init_dtypes.c.
{
    memset(lattice, 0, sizeof(*lattice));
    lattice->atomic_pos = NULL;
    lattice->atom_type = NULL;
    lattice->kpt_iredBZ = NULL;
    lattice->kpt_fullBZ = NULL;
    lattice->kpt_fullBZ_crys = NULL;
    lattice->kmap = NULL;
    lattice->syms = NULL;
    return;
}
References Lattice::atom_type, Lattice::atomic_pos, Lattice::kmap, Lattice::kpt_fullBZ, Lattice::kpt_fullBZ_crys, Lattice::kpt_iredBZ, and Lattice::syms.
Referenced by elph_driver(), and interpolation_driver().
init_local_pseudo_type()
void init_local_pseudo_type (struct local_pseudo * lpseudo)
Definition at line 56 of file init_dtypes.c.
{
    memset(lpseudo, 0, sizeof(*lpseudo));
    lpseudo->Vloc_atomic = NULL;
    lpseudo->r_grid = NULL;
    lpseudo->rab_grid = NULL;
    return;
}
References local_pseudo::r_grid, local_pseudo::rab_grid, and local_pseudo::Vloc_atomic.
init_phonon_type()
void init_phonon_type (struct Phonon * phonon)
Definition at line 31 of file init_dtypes.c.
{
    memset(phonon, 0, sizeof(*phonon));
    phonon->qpts_iBZ = NULL;
    phonon->qpts_BZ = NULL;
    phonon->ph_syms = NULL;
    phonon->qmap = NULL;
    phonon->nqstar = NULL;
    phonon->epsilon = NULL;
    phonon->Zborn = NULL;
    phonon->Qpole = NULL;
    return;
}
References Phonon::epsilon, Phonon::nqstar, Phonon::ph_syms, Phonon::qmap, Phonon::Qpole, Phonon::qpts_BZ, Phonon::qpts_iBZ, and Phonon::Zborn.
Referenced by elph_driver(), and interpolation_driver().
init_Pseudo_type()
void init_Pseudo_type (struct Pseudo * pseudo)
Definition at line 66 of file init_dtypes.c.
{
    memset(pseudo, 0, sizeof(*pseudo));
    pseudo->loc_pseudo = NULL;
    pseudo->PP_table = NULL;
    pseudo->Fsign = NULL;
    pseudo->fCoeff = NULL;
    init_Vloc_table_type(pseudo->vloc_table);
    return;
}
References Pseudo::fCoeff, Pseudo::Fsign, init_Vloc_table_type(), Pseudo::loc_pseudo, Pseudo::PP_table, and Pseudo::vloc_table.
Referenced by elph_driver().
init_Vloc_table_type()
void init_Vloc_table_type (struct Vloc_table * vloc_tab)
Definition at line 46 of file init_dtypes.c.
{
    memset(vloc_tab, 0, sizeof(*vloc_tab));
    vloc_tab->g_co = NULL;
    vloc_tab->vlocg = NULL;
    vloc_tab->vploc_co = NULL;
    return;
}
References Vloc_table::g_co, Vloc_table::vlocg, and Vloc_table::vploc_co.
Referenced by init_Pseudo_type().